/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSString, UIView, UIWindow;

@interface _SBAlertAccessoryWindowWrapper : NSObject
{
    UIWindow *window;
    UIView *contextHostView;
    NSString *contextHostRequester;
}

@property(retain, nonatomic) NSString *contextHostRequester; // @synthesize contextHostRequester;
@property(retain, nonatomic) UIView *contextHostView; // @synthesize contextHostView;
- (void)dealloc;
@property(retain, nonatomic) UIWindow *window; // @synthesize window;

@end

