/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBWidgetViewController.h"

@class NSDate, NSMapTable, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSTimer, UIView, _SBBrokenWidgetView, _SBWidgetRemoteViewController;

@interface _SBWidgetViewControllerOutOfProcess : SBWidgetViewController
{
    _Bool _snapshottingEnabled;
    _Bool _requestingRemoteViewController;
    _Bool _disconnectingRemoteViewController;
    _Bool _encodingLayerTree;
    _Bool _didRequestViewInset;
    _Bool _didUpdate;
    _Bool _blacklisted;
    NSObject<OS_dispatch_queue> *_proxyConnectionQueue;
    NSObject<OS_dispatch_queue> *_proxyDisconnectionQueue;
    NSObject<OS_dispatch_queue> *_proxyRequestQueue;
    NSObject<OS_dispatch_queue> *_diskWriteQueue;
    _SBWidgetRemoteViewController *_remoteViewController;
    id <NSCopying> _extensionRequest;
    UIView *_contentProvidingView;
    UIView *_snapshotView;
    NSTimer *_disconnectionTimer;
    NSObject<OS_dispatch_semaphore> *_viewWillAppearSemaphore;
    NSObject<OS_dispatch_semaphore> *_viewWillDisappearSemaphore;
    id _remoteViewControllerDisconnectionHandler;
    NSDate *_lastUnanticipatedDisconnectionDate;
    NSMapTable *_openAppearanceTransactions;
    _SBBrokenWidgetView *_brokenView;
}

+ (void)initialize;
- (_Bool)_attemptReconnectionAfterUnanticipatedDisconnection;
- (void)_beginRemoteViewControllerAppearanceTransitionIfNecessary:(_Bool)arg1 animated:(_Bool)arg2 completion:(id)arg3;
@property(retain, nonatomic, getter=_brokenView, setter=_setBrokenView:) _SBBrokenWidgetView *brokenView; // @synthesize brokenView=_brokenView;
- (id)_cachedStateURLEnsuringDirectoryExists:(_Bool)arg1;
- (_Bool)_canDisconnectRemoteViewController:(id *)arg1;
- (_Bool)_canInsertRemoteView;
- (_Bool)_canRequestRemoteViewController:(id *)arg1;
- (id)_cancelTouches;
- (void)_captureLayerTree:(id)arg1;
@property(retain, nonatomic, getter=_contentProvidingView, setter=_setContentProvidingView:) UIView *contentProvidingView; // @synthesize contentProvidingView=_contentProvidingView;
- (double)_contentWidth;
@property(nonatomic, getter=_didRequestViewInset, setter=_setDidRequestViewInset:) _Bool didRequestViewInset; // @synthesize didRequestViewInset=_didRequestViewInset;
@property(nonatomic, getter=_didUpdate, setter=_setDidUpdate:) _Bool didUpdate; // @synthesize didUpdate=_didUpdate;
- (void)_disconnectRemoteViewController:(id)arg1;
- (void)_disconnectRemoteViewControllerAndCoalesce:(_Bool)arg1 completionHandler:(id)arg2;
- (void)_disconnectRemoteViewControllerImmediatelyWithCompletionHandler:(id)arg1;
@property(nonatomic, getter=_disconnectionTimer, setter=_setDisconnectionTimer:) NSTimer *disconnectionTimer; // @synthesize disconnectionTimer=_disconnectionTimer;
- (void)_disconnectionTimerDidFire:(id)arg1;
@property(readonly, nonatomic, getter=_diskWriteQueue) NSObject<OS_dispatch_queue> *diskWriteQueue; // @synthesize diskWriteQueue=_diskWriteQueue;
- (_Bool)_effectiveHasContent;
- (void)_endRemoteViewControllerAppearanceTransitionIfNecessary;
- (void)_endRequestState:(long long)arg1;
- (void)_enqueueRemoteServiceRequest:(id)arg1 withDescription:(void)arg2;
- (void)_enqueueRequest:(id)arg1 inQueue:(void)arg2 trampolinedToMainQueue:(id)arg3 withDescription:(_Bool)arg4;
@property(copy, nonatomic, getter=_extensionRequest, setter=_setExtensionRequest:) id <NSCopying> extensionRequest; // @synthesize extensionRequest=_extensionRequest;
- (void)_finishDisconnectingRemoteViewControllerWithError:(id)arg1 completion:(id)arg2;
- (void)_handleRequestedViewHeight:(double)arg1 usingAutolayout:(_Bool)arg2 requestIdentifier:(id)arg3;
- (void)_insertAppropriateViewWithContent;
- (void)_insertContentProvidingSubview:(id)arg1 completion:(id)arg2;
- (void)_insertRemoteViewAfterViewWillAppearWithCompletion:(id)arg1;
- (void)_invalidateDisconnectionTimer;
- (void)_invalidateSnapshotWithForce:(_Bool)arg1 completionHandler:(id)arg2;
@property(nonatomic, getter=_isBlacklisted, setter=_setBlacklisted:) _Bool blacklisted; // @synthesize blacklisted=_blacklisted;
@property(nonatomic, getter=_isDisconnectingRemoteViewController, setter=_setDisconnectingRemoteViewController:) _Bool disconnectingRemoteViewController; // @synthesize disconnectingRemoteViewController=_disconnectingRemoteViewController;
@property(nonatomic, getter=_isEncodingLayerTree, setter=_setEncodingLayerTree:) _Bool encodingLayerTree; // @synthesize encodingLayerTree=_encodingLayerTree;
- (_Bool)_isRemoteViewVisible;
@property(nonatomic, getter=_isRequestingRemoteViewController, setter=_setRequestingRemoteViewController:) _Bool requestingRemoteViewController; // @synthesize requestingRemoteViewController=_requestingRemoteViewController;
@property(nonatomic, getter=_isSnapshottingEnabled, setter=_setSnapshottingEnabled:) _Bool snapshottingEnabled; // @synthesize snapshottingEnabled=_snapshottingEnabled;
@property(retain, nonatomic, getter=_lastUnanticipatedDisconnectionDate, setter=_setLastUnanticipatedDisconnectionDate:) NSDate *lastUnanticipatedDisconnectionDate; // @synthesize lastUnanticipatedDisconnectionDate=_lastUnanticipatedDisconnectionDate;
- (void)_loadSnapshotViewFromDiskIfNecessary:(id)arg1;
- (struct UIEdgeInsets)_marginInset;
@property(readonly, nonatomic, getter=_openAppearanceTransactions) NSMapTable *openAppearanceTransactions; // @synthesize openAppearanceTransactions=_openAppearanceTransactions;
- (void)_packageViewFromURL:(id)arg1 reply:(id)arg2;
- (void)_packageViewWithBlock:(id)arg1 reply:(void)arg2;
- (void)_packageViewWithData:(id)arg1 reply:(id)arg2;
@property(readonly, nonatomic, getter=_proxyConnectionQueue) NSObject<OS_dispatch_queue> *proxyConnectionQueue; // @synthesize proxyConnectionQueue=_proxyConnectionQueue;
@property(readonly, nonatomic, getter=_proxyDisconnectionQueue) NSObject<OS_dispatch_queue> *proxyDisconnectionQueue; // @synthesize proxyDisconnectionQueue=_proxyDisconnectionQueue;
@property(readonly, nonatomic, getter=_proxyRequestQueue) NSObject<OS_dispatch_queue> *proxyRequestQueue; // @synthesize proxyRequestQueue=_proxyRequestQueue;
@property(retain, nonatomic, getter=_remoteViewController, setter=_setRemoteViewController:) _SBWidgetRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;
@property(copy, nonatomic, getter=_remoteViewControllerDisconnectionHandler, setter=_setRemoteViewControllerDisconnectionHandler:) id remoteViewControllerDisconnectionHandler; // @synthesize remoteViewControllerDisconnectionHandler=_remoteViewControllerDisconnectionHandler;
- (void)_removeAllSnapshots;
- (void)_removeSnapshotAtURL:(id)arg1;
- (id)_request:(SEL)arg1 withDescription:(id)arg2 forQueue:(void)arg3 trampolinedToMainQueue:(id)arg4;
- (void)_requestRemoteViewController:(id)arg1;
@property(nonatomic, setter=_setImplementsPerformUpdate:) _Bool implementsPerformUpdate;
- (void)_setSemaphoreInstanceVariable:(id *)arg1 toSemaphore:(id)arg2;
@property(retain, nonatomic, getter=_snapshotView, setter=_setSnapshotView:) UIView *snapshotView; // @synthesize snapshotView=_snapshotView;
- (void)_setSnapshotView:(id)arg1 forLayoutMode:(long long)arg2;
@property(retain, nonatomic, getter=_viewWillAppearSemaphore, setter=_setViewWillAppearSemaphore:) NSObject<OS_dispatch_semaphore> *viewWillAppearSemaphore; // @synthesize viewWillAppearSemaphore=_viewWillAppearSemaphore;
@property(retain, nonatomic, getter=_viewWillDisappearSemaphore, setter=_setViewWillDisappearSemaphore:) NSObject<OS_dispatch_semaphore> *viewWillDisappearSemaphore; // @synthesize viewWillDisappearSemaphore=_viewWillDisappearSemaphore;
- (void)_setupRequestQueue;
- (id)_snapshotIdentifierForLayoutMode:(long long)arg1;
- (void)_synchronizeCachedState;
- (struct CGSize)_todayContentMaxSize;
- (double)_updatePreferredContentSizeWithHeight:(double)arg1;
- (id)_valueForCachedStateKey:(id)arg1;
- (id)_widgetSnapshotURLForLayoutMode:(long long)arg1 ensuringDirectoryExists:(_Bool)arg2;
- (void)_writeSnapshotData:(id)arg1 toURLForLayoutMode:(long long)arg2;
- (id)auditToken;
- (void)captureSnapshotWithCompletionHandler:(id)arg1;
- (void)connectRemoteViewControllerWithCompletionHandler:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)disconnectRemoteViewControllerWithCompletionHandler:(id)arg1;
- (void)handleReconnectionRequest:(id)arg1;
- (id)initWithWidgetIdentifier:(id)arg1 bundlePath:(id)arg2;
- (void)insertSnapshotWithCompletionHandler:(id)arg1;
- (void)invalidateCachedSnapshotWithCompletionHandler:(id)arg1;
- (void)performUpdateWithCompletionHandler:(id)arg1;
- (void)requestInsertionOfRemoteViewWithCompletionHandler:(id)arg1;
- (void)setHasContent:(_Bool)arg1;
- (void)setRequestState:(long long)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)validateSnapshotViewForActiveLayoutMode;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)widgetDidTerminateWithError:(id)arg1;

@end

