/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBWidgetViewController.h"

#import "_SBUIWidgetHost-Protocol.h"

@class NSString, _SBUIWidgetViewController;

@interface _SBWidgetViewControllerInProcess : SBWidgetViewController <_SBUIWidgetHost>
{
    _SBUIWidgetViewController *_widgetViewController;
}

- (id)_newWidgetViewControllerWithIdentifier:(id)arg1 bundlePath:(id)arg2;
- (void)dealloc;
- (void)hostDidDismiss;
- (void)hostDidPresent;
- (void)hostWillDismiss;
- (void)hostWillPresent;
- (id)initWithWidgetIdentifier:(id)arg1 bundlePath:(id)arg2;
- (void)invalidatePreferredViewSize;
- (void)requestLaunchOfURL:(id)arg1;
- (void)requestPreferredViewHeightWithHandler:(id)arg1;
- (void)requestPresentationOfViewController:(id)arg1 presentationStyle:(long long)arg2 context:(id)arg3 completion:(id)arg4;
@property(retain, nonatomic) _SBUIWidgetViewController *widgetViewController; // @synthesize widgetViewController=_widgetViewController;
- (void)updateContentWidth:(double)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

