/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "_UIRemoteViewController.h"

#import "_NCWidgetViewController_Host_IPC-Protocol.h"

@class NSObject<OS_dispatch_queue>, _SBWidgetViewControllerOutOfProcess;

@interface _SBWidgetRemoteViewController : _UIRemoteViewController <_NCWidgetViewController_Host_IPC>
{
    _Bool _valid;
    _SBWidgetViewControllerOutOfProcess *_managingHost;
    NSObject<OS_dispatch_queue> *_managingHostQueue;
}

+ (id)exportedInterface;
+ (id)serviceViewControllerInterface;
- (void)__closeTransactionForAppearanceCallWithState:(int)arg1 withIdentifier:(id)arg2;
- (void)__requestLaunchOfURL:(id)arg1;
- (void)__requestPreferredViewHeight:(double)arg1 usingAutolayout:(_Bool)arg2 requestIdentifier:(id)arg3;
- (_Bool)__shouldRemoteViewControllerFenceOperations;
- (void)__viewServiceDidRegisterScrollToTopView;
- (void)__viewServiceDidUnregisterScrollToTopView;
@property(nonatomic, getter=_isValid, setter=_setValid:) _Bool valid; // @synthesize valid=_valid;
- (void)_openTransactionForAppearanceCallWithState:(int)arg1 withIdentifier:(id)arg2;
- (void)_performOutstandingAnimationsWithRequestIdentifier:(id)arg1;
- (void)_performOutstandingCompletionWithRequestIdentifier:(id)arg1;
- (void)_performUpdateWithReplyHandler:(id)arg1;
- (void)_requestEncodedLayerTreeWithReplyHandler:(id)arg1;
- (_Bool)_serviceHasScrollToTopView;
- (void)_setWidgetIdentifier:(id)arg1;
- (void)_viewWillTransitionToSize:(struct CGSize)arg1 requestIdentifier:(id)arg2;
- (void)dealloc;
- (id)disconnect;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) _SBWidgetViewControllerOutOfProcess *managingHost; // @synthesize managingHost=_managingHost;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *managingHostQueue; // @synthesize managingHostQueue=_managingHostQueue;
- (void)viewServiceDidTerminateWithError:(id)arg1;

@end

