/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol FBApplicationLibraryObserver <NSObject>

@optional
- (void)applicationLibrary:(id)arg1 didAddApplications:(id)arg2;
- (void)applicationLibrary:(id)arg1 didAddPlaceholders:(id)arg2;
- (void)applicationLibrary:(id)arg1 didCancelPlaceholders:(id)arg2;
- (void)applicationLibrary:(id)arg1 didRemoveApplications:(id)arg2;
- (void)applicationLibrary:(id)arg1 didReplaceApplications:(id)arg2 withApplications:(id)arg3;
- (void)applicationLibrary:(id)arg1 networkUsageDidChange:(_Bool)arg2;
@end

