/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol FBSystemServiceDelegate <NSObject>
- (void)systemService:(id)arg1 canActivateApplication:(id)arg2 withResult:(id)arg3;
- (void)systemService:(id)arg1 handleOpenApplicationRequest:(id)arg2 options:(id)arg3 origin:(id)arg4 withResult:(id)arg5;
- (void)systemService:(id)arg1 handleOpenURLRequest:(id)arg2 application:(id)arg3 options:(id)arg4 origin:(id)arg5 withResult:(id)arg6;

@optional
- (void)systemService:(id)arg1 handleActions:(id)arg2 origin:(id)arg3 withResult:(id)arg4;
- (void)systemServicePrepareForExit:(id)arg1 andRelaunch:(_Bool)arg2;
- (void)systemServicePrepareForShutdown:(id)arg1 andReboot:(_Bool)arg2;
@end

