/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SBArrayStackAdditions)
- (id)pop;
- (id)popObject:(id)arg1;
- (void)push:(id)arg1;
- (id)top;
@end

