/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "BBRemoteDataProvider-Protocol.h"
#import "SBPushStoreObserver-Protocol.h"

@class BBDataProviderProxy, BBSectionInfo, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface RLNDataProvider : NSObject <SBPushStoreObserver, BBRemoteDataProvider>
{
    NSString *_sectionID;
    NSMutableArray *_publisherBulletinIDs;
    BBSectionInfo *_defaultSectionInfo;
    NSString *_displayName;
    unsigned long long _pushSettings;
    BBDataProviderProxy *_proxy;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (struct CGSize)_sizeFromSizeConstraint:(id)arg1 originalSize:(struct CGSize)arg2;
- (id)_actionsForCategoryIdentifier:(id)arg1 context:(unsigned long long)arg2;
- (id)_allBulletinsWithLimit:(unsigned long long)arg1;
- (id)_bbActionFromUIUserNotificationAction:(id)arg1;
- (unsigned long long)_bbActivationModeFromUIActivationMode:(unsigned long long)arg1;
- (id)_bulletinForNotification:(id)arg1;
- (void)_cleanupMigrationFromBrightonWithLastClearedDate:(id)arg1;
- (id)_defaultActionWithTitle:(id)arg1;
- (id)_imageForRecordID:(id)arg1;
- (_Bool)_isPushDataProvider;
- (id)_latestBulletinInSet:(id)arg1;
- (id)_publisherBulletinIDForNotification:(id)arg1;
- (void)_saveUpdatedSectionInfo;
- (id)_sortKey;
- (id)_supplementaryActionsForPushStoreNotification:(id)arg1 context:(unsigned long long)arg2;
- (float)attachmentAspectRatioForRecordID:(id)arg1;
- (id)attachmentPNGDataForRecordID:(id)arg1 sizeConstraints:(id)arg2;
- (id)bulletinsFilteredBy:(unsigned long long)arg1 count:(unsigned long long)arg2 lastCleared:(id)arg3;
- (id)clearedInfoAndBulletinsForClearingAllBulletinsWithLimit:(unsigned long long)arg1 lastClearedInfo:(id)arg2;
- (id)clearedInfoForBulletins:(id)arg1 lastClearedInfo:(id)arg2;
- (void)dealloc;
- (id)defaultSectionInfo;
- (id)initWithSectionID:(id)arg1 displayName:(id)arg2 queue:(id)arg3;
- (void)invalidate;
- (void)noteSectionInfoDidChange:(id)arg1;
@property(retain, nonatomic) BBDataProviderProxy *proxy; // @synthesize proxy=_proxy;
- (void)pushStoreClearedNotifications;
- (void)pushStoreNotificationsDidChange;
- (void)pushStoreUpdatedPushSettings;
- (void)pushStoreUserAcceptedDelivery;
- (void)pushStoreUserDeclinedDelivery;
- (void)rebuildDefaultSectionInfoForPushSettings:(unsigned long long)arg1;
- (id)sectionDisplayName;
- (id)sectionIdentifier;
- (id)sectionParameters;
- (id)sortDescriptors;
- (_Bool)syncsBulletinDismissal;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

