/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

@class NSString;

@interface SBActivationInfoViewController : UIViewController
{
    NSString *_meid;
    NSString *_imei;
    NSString *_iccid;
    NSString *_csn;
    _Bool _isOnBootstrap;
    double _alertHeight;
}

- (id)_formattedCSN;
- (id)_formattedICCID;
- (id)_formattedIMEI;
- (id)_formattedString:(id)arg1 withSpaceAfterDigits:(unsigned long long)arg2;
- (void)_simStatusChanged:(id)arg1;
- (void)_updateTextView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (id)textView;
- (void)viewWillAppear:(_Bool)arg1;

@end

