/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBWorkspaceTransaction.h"

#import "SBUIAnimationControllerObserver-Protocol.h"

@class NSString, SBAlert, SBUIAnimationController;

@interface SBAlertToAlertWorkspaceTransaction : SBWorkspaceTransaction <SBUIAnimationControllerObserver>
{
    SBAlert *_activatingAlert;
    SBAlert *_deactivatingAlert;
    _Bool _activation;
    SBUIAnimationController *_animation;
    _Bool _animatingAlertDeactivation;
}

- (void)_alertAnimationComplete:(id)arg1;
- (void)_begin;
- (void)_deactivateAlertIfNecessary;
- (void)_didComplete;
- (void)_doAlertTransition;
- (void)_endAnimation;
- (id)_initWithAlertManager:(id)arg1 activatingAlert:(id)arg2 deactivatingAlert:(id)arg3 activation:(_Bool)arg4;
- (void)animationController:(id)arg1 willBeginAnimation:(_Bool)arg2;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
- (id)initActivationWithAlertManager:(id)arg1 from:(id)arg2 to:(id)arg3;
- (id)initDeactivationWithAlertManager:(id)arg1 from:(id)arg2 to:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

