/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

@class NSMutableSet, SBAlert, UIScreen, UIView;

@interface SBAlertWindowViewController : UIViewController
{
    UIScreen *_screen;
    UIView *_contentView;
    SBAlert *_activeAlert;
    UIViewController *_activeViewController;
    NSMutableSet *_childAlerts;
}

@property(retain, nonatomic) SBAlert *activeAlert; // @synthesize activeAlert=_activeAlert;
@property(retain, nonatomic) UIViewController *activeViewController; // @synthesize activeViewController=_activeViewController;
- (void)addAlertController:(id)arg1;
- (void)addView:(id)arg1 toBeObscuredByAlert:(id)arg2;
- (_Bool)alertWindow:(id)arg1 canAnimateInAlert:(id)arg2;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithScreen:(id)arg1;
- (void)loadView;
- (void)noteAlertWindow:(id)arg1 didDisplayAlert:(id)arg2;
- (void)removeAlertController:(id)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (long long)stackedAlertCount;
- (id)stackedAlertsIncludingActiveAlert:(_Bool)arg1;
- (id)stackedViewForAlert:(id)arg1;
- (_Bool)wantsFullScreenLayout;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)window:(id)arg1 willAnimateFromContentFrame:(struct CGRect)arg2 toContentFrame:(struct CGRect)arg3;

@end

