/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlert.h"

@class UIViewController;

@interface SBAlertAdapter : SBAlert
{
    UIViewController *_effectiveViewController;
}

- (id)_basicDescription;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)alertWindow:(id)arg1 resizedFromContentFrame:(struct CGRect)arg2 toContentFrame:(struct CGRect)arg3;
- (void)dealloc;
- (id)display;
- (id)effectiveViewController;
- (id)initWithViewController:(id)arg1;
- (void)setDisplay:(id)arg1;
- (void)setView:(id)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (id)viewControllerForSupportedInterfaceOrientations;

@end

