/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAppSwitcherPeopleButtonAndLabelView.h"

@interface SBAppSwitcherPeopleContactView : SBAppSwitcherPeopleButtonAndLabelView
{
}

+ (double)_layoutLabelFontSizeCompact:(_Bool)arg1;
+ (double)_layoutLabelVerticalPaddingCompact:(_Bool)arg1;
+ (struct CGSize)preferredLayoutSizeForMonogramSize:(double)arg1 compact:(_Bool)arg2;

@end

