/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "SBAppSwitcherPageContentView-Protocol.h"
#import "SBWallpaperObserver-Protocol.h"

@class NSString, SBAppSwitcherStatusBarViewCache, SBFakeStatusBarView;

@interface SBAppSwitcherHomePageCellView : UIView <SBWallpaperObserver, SBAppSwitcherPageContentView>
{
    UIView *_possiblyRotatedContainer;
    UIView *_nonRotatedContainer;
    UIView *_homeScreenView;
    UIView *_homeSnapshot;
    UIView *_wallpaperView;
    SBFakeStatusBarView *_fakeStatusBar;
    SBAppSwitcherStatusBarViewCache *_statusBarCache;
    _Bool _usesSnapshots;
    long long _snapshotOrientation;
    long long _orientation;
}

+ (id)wallpaperSnapshotForZoomFactor:(double)arg1 orientation:(long long)arg2;
- (void)_addHomeScreenViewAsSubview:(id)arg1;
- (void)_statusBarFrameChanging;
- (void)_updateWallpaperView;
- (void)_viewDidAnimatePresentation:(id)arg1;
- (void)_viewDismissing:(id)arg1;
- (void)_viewPresenting:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) UIView *homeScreenView; // @synthesize homeScreenView=_homeScreenView;
@property(readonly, nonatomic) UIView *homeSnapshot; // @synthesize homeSnapshot=_homeSnapshot;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 statusBarCache:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void)setHomeSnapshot:(id)arg1 inOrientation:(long long)arg2;
- (void)setLegibilitySettings:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)wallpaperDidChangeForVariant:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

