/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

#import "SBAppSwitcherPeopleDataSourceConsumer-Protocol.h"
#import "SBAppSwitcherPeopleScrollViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSArray, NSString, SBAppSwitcherPeopleScrollView, SBAppSwitcherSettings, UIPanGestureRecognizer, _UILegibilitySettings;

@interface SBAppSwitcherPeopleViewController : UIViewController <_UISettingsKeyObserver, SBAppSwitcherPeopleDataSourceConsumer, UIGestureRecognizerDelegate, SBAppSwitcherPeopleScrollViewDelegate>
{
    SBAppSwitcherPeopleScrollView *_peopleScrollView;
    UIPanGestureRecognizer *_closeGestureRecognizer;
    SBAppSwitcherSettings *_settings;
    _UILegibilitySettings *_legibilitySettings;
    struct CGPoint _contentOffsetBeforeExpandingItem;
    _Bool _interactivelyClosingItem;
    _Bool _animatingPresentation;
    NSArray *_dataSourceSnapshotLastProvidedToScrollView;
    id <SBAppSwitcherPeopleDataSource> _activeDataSource;
    _Bool _bbHasWarmedFavoritesListManager;
    _Bool _presented;
    _Bool _finishedLoadingAllData;
    id <SBAppSwitcherPeopleDelegate> _delegate;
}

- (void)_configureDataSourceIfNecessaryAndPossible;
- (void)_configureGestureRecognizers;
- (void)_configurePeopleScrollView;
- (void)_deviceUnlockedForFirstTime:(id)arg1;
- (void)_handleClosePanGesture:(id)arg1;
- (void)_switcherDidPresentAnimation:(id)arg1;
- (void)_switcherWillAnimate:(id)arg1;
- (id)activeDataSource;
- (void)bbServerHasInitializedABFavoritesListManagerToWorkaround17689168;
- (void)cachedMonogramImageForPersonID:(int)arg1 generatingIfNecessaryWithResult:(id)arg2;
- (void)cancelTracking;
- (void)dataSourceChanged:(id)arg1;
- (void)dealloc;
@property(nonatomic) id <SBAppSwitcherPeopleDelegate> delegate; // @synthesize delegate=_delegate;
- (id)existingCachedMonogramImageForPersonID:(int)arg1 outIsMask:(_Bool *)arg2;
- (id)expandedItemWrapper;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void)loadView;
- (double)monogramSize;
- (long long)numberOfSectionsInPeopleScrollView:(id)arg1;
- (id)peopleScrollView:(id)arg1 itemAtIndexPath:(id)arg2;
- (long long)peopleScrollView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)peopleScrollView:(id)arg1 placeholderStringForEmptySection:(unsigned long long)arg2;
- (struct CGSize)peopleScrollView:(id)arg1 sizeForItem:(id)arg2 expanded:(_Bool)arg3;
- (struct CGSize)peopleScrollView:(id)arg1 sizeForPlaceholderForSection:(long long)arg2;
- (id)peopleScrollView:(id)arg1 titleForSection:(unsigned long long)arg2;
- (id)peopleScrollView:(id)arg1 viewForItem:(id)arg2;
- (struct CGSize)peopleScrollViewSize;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setActiveDataSource:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (id)silhouetteMonogram;
- (void)switcherWasDismissed:(_Bool)arg1;
- (void)switcherWillBePresented:(_Bool)arg1;
- (void)tappedExpandCollapseForItem:(id)arg1;
- (_Bool)useVerticallyCompactLayoutSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

