/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerGroupObserver-Protocol.h"

@class NSString, SBApplication, SBUIAnimationController;

@interface SBAppToAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerGroupObserver>
{
    SBApplication *_fromApp;
    SBUIAnimationController *_animationController;
    _Bool _animatedActivation;
    _Bool _animatedDeactivation;
    _Bool _deactivatingAppFromAppToAppGesture;
    _Bool _appQuitFromSwitcher;
}

- (void)_begin;
- (void)_beginAnimation;
- (_Bool)_canBeInterrupted;
- (void)_didComplete;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_endAnimation;
- (void)_handleApplicationDidNotChange:(id)arg1;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)arg1;
- (void)_kickOffActivation;
- (void)_setupAnimation;
- (id)_setupAnimationFrom:(id)arg1 to:(id)arg2;
- (id)_setupMilestonesFrom:(id)arg1 to:(id)arg2;
- (void)_synchronizeWithSceneUpdates;
- (void)animationController:(id)arg1 willBeginAnimation:(_Bool)arg2;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)animationControllerDidRevealApplication:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
@property(retain, nonatomic) SBApplication *fromApp; // @synthesize fromApp=_fromApp;
- (id)initWithAlertManager:(id)arg1 exitedApp:(id)arg2;
- (id)initWithAlertManager:(id)arg1 from:(id)arg2 to:(id)arg3 withResult:(id)arg4;
- (_Bool)shouldAnimateOrientationChangeOnCompletion;
- (_Bool)shouldDismissSwitcher;
- (_Bool)shouldPerformToAppStateCleanupOnCompletion;
- (_Bool)shouldRestoreSpringBoardContentOnCleanup;
- (_Bool)shouldToggleSpringBoardStatusBarOnCleanup;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

