/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSMutableSet;

@interface SBAppSwitcherRemoteAlertSet : NSObject <NSCopying>
{
    NSMutableArray *_alerts;
    NSMutableSet *_placeholderIdentifiers;
}

- (void)addPlaceholderForIdentifier:(id)arg1;
- (void)addRemoteAlert:(id)arg1;
- (id)alertAtIndex:(unsigned long long)arg1;
- (id)alertForBundleIdentifier:(id)arg1;
- (id)alertForDisplayLayout:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)count;
- (void)dealloc;
- (id)displayItems;
- (id)initWithAlertSet:(id)arg1 zone:(struct _NSZone *)arg2;
- (id)placeholderBundleIdentifiers;
- (id)placeholderDisplayItems;
- (void)removePlaceholderForIdentifier:(id)arg1;
- (void)removeRemoteAlert:(id)arg1;
- (id)serviceBundleIdentifiers;

@end

