/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSObject<OS_dispatch_queue>, NSString, NSURL;

@interface SBAppSwitcherPeopleContactAction : NSObject <NSCopying>
{
    unsigned long long _contactType;
    int _abRecordID;
    NSString *_label;
    NSString *_destinationID;
    NSObject<OS_dispatch_queue> *_urlUpdateQueue;
    unsigned long long _actionType;
}

@property(readonly, nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
@property(readonly, nonatomic) NSString *destinationID; // @synthesize destinationID=_destinationID;
- (id)initWithType:(unsigned long long)arg1 label:(id)arg2 destinationID:(id)arg3 addressBookRecordID:(int)arg4;
@property(readonly, nonatomic) NSString *label; // @synthesize label=_label;
@property(readonly, nonatomic) NSURL *url;

@end

