/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "SBPeopleScrollViewItemView-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class NSString, SBAppSwitcherPeopleContactView, SBAppSwitcherPeopleViewController, SBMaskEndGradientClippingView, SBScrollViewItemWrapper, UIScrollView, _UILegibilitySettings;

@interface SBAppSwitcherPeopleContactContainer : UIView <UIActionSheetDelegate, SBPeopleScrollViewItemView>
{
    SBAppSwitcherPeopleContactView *_contactView;
    unsigned long long _presentedSheetActionType;
    UIView *_actionButtonClippingContainer;
    UIScrollView *_actionButtonScrollView;
    UIView *_maskView;
    SBMaskEndGradientClippingView *_maskRightGradient;
    SBMaskEndGradientClippingView *_maskLeftGradient;
    SBScrollViewItemWrapper *_itemWrapper;
    SBAppSwitcherPeopleViewController *_peopleController;
}

+ (double)actionButtonItemReferenceSize;
+ (struct CGSize)layoutSizeOfActionButtonArrayContentSizeForItem:(id)arg1 monogramSize:(double)arg2 compact:(_Bool)arg3 forSize:(struct CGSize)arg4;
+ (struct CGSize)layoutSizeOfActionButtonForItem:(id)arg1 action:(id)arg2 monogramSize:(double)arg3 compact:(_Bool)arg4 forSize:(struct CGSize)arg5;
+ (struct CGSize)layoutSizeOfExpandedActionButtonScrollViewForItem:(id)arg1 monogramSize:(double)arg2 compact:(_Bool)arg3 forSize:(struct CGSize)arg4;
+ (struct CGSize)preferredLayoutSizeForItem:(id)arg1 monogramSize:(double)arg2 compact:(_Bool)arg3 expanded:(_Bool)arg4 forSize:(struct CGSize)arg5;
- (void)_addActionButtons;
- (void)_configureActionButtonScrollView;
- (void)_configureClippingContainerMask;
- (id)_contactItem;
- (void)_layoutMaskView;
- (void)_removeActionButtons;
- (void)_removeActionButtonsScrollView;
- (void)_removeClippingContainerMask;
- (void)_tappedContactActionButton:(id)arg1;
- (void)_updateViewContents;
- (void)dealloc;
- (void)didCollapseItem;
- (id)initWithFrame:(struct CGRect)arg1 peopleController:(id)arg2;
@property(retain, nonatomic) SBScrollViewItemWrapper *itemWrapper; // @synthesize itemWrapper=_itemWrapper;
- (void)layoutSubviews;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(nonatomic) SBAppSwitcherPeopleViewController *peopleController; // @synthesize peopleController=_peopleController;
- (void)tappedGestureRecognizerOnContactContainer:(id)arg1;
- (void)willExpandItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

