/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIScrollViewDelegate-Protocol.h"

@protocol SBAppSwitcherPeopleScrollViewDelegate <UIScrollViewDelegate>
- (long long)numberOfSectionsInPeopleScrollView:(id)arg1;
- (id)peopleScrollView:(id)arg1 itemAtIndexPath:(id)arg2;
- (long long)peopleScrollView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)peopleScrollView:(id)arg1 placeholderStringForEmptySection:(unsigned long long)arg2;
- (struct CGSize)peopleScrollView:(id)arg1 sizeForItem:(id)arg2 expanded:(_Bool)arg3;
- (struct CGSize)peopleScrollView:(id)arg1 sizeForPlaceholderForSection:(long long)arg2;
- (id)peopleScrollView:(id)arg1 titleForSection:(unsigned long long)arg2;
- (id)peopleScrollView:(id)arg1 viewForItem:(id)arg2;
@end

