/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface SBAppSwitcherModel : NSObject
{
    NSMutableArray *_recentDisplayLayouts;
    NSTimer *_saveTimer;
}

+ (id)sharedInstance;
- (void)_invalidateSaveTimer;
- (id)_recentsFromLegacyPrefs;
- (id)_recentsFromPrefs;
- (void)_saveRecents;
- (void)_saveRecentsDelayed;
- (void)_verifyAppList;
- (void)addToFront:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)remove:(id)arg1;
- (void)removeDisplayItem:(id)arg1;
- (id)snapshot;
- (id)snapshotOfFlattenedArrayOfAppIdentifiersWhichIsOnlyTemporary;

@end

