/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "SBAppSwitcherPageContentView-Protocol.h"

@class FBWindowContextHostManager, NSString, SBWallpaperEffectView, UIView<FBWindowContextAppearance>;

@interface SBAppSwitcherContextHostWrapperView : UIView <SBAppSwitcherPageContentView>
{
    FBWindowContextHostManager *_contextHostManager;
    UIView *_containerView;
    UIView<FBWindowContextAppearance> *_contextHostView;
    UIView *_snapshotView;
    SBWallpaperEffectView *_wallpaperEffectView;
    long long _orientation;
}

- (struct CGAffineTransform)_rotationTransformForOrientation:(long long)arg1;
- (void)_viewDidAnimateDismissal:(id)arg1;
- (void)_viewDidAnimatePresentation:(id)arg1;
- (void)_viewDismissing:(id)arg1;
- (void)_viewPresenting:(id)arg1;
- (void)dealloc;
- (void)didMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 application:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

