/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "SBAppSwitcherPageContentView-Protocol.h"

@class NSString, SBAppSwitcherStatusBarViewCache, SBWallpaperEffectView, SBZoomView, UIView<SBAppSwitcherCacheVended>;

@interface SBAppSwitcherContinuityAppView : UIView <SBAppSwitcherPageContentView>
{
    UIView *_containerView;
    SBWallpaperEffectView *_wallpaperView;
    UIView<SBAppSwitcherCacheVended> *_fakeStatusBarView;
    SBAppSwitcherStatusBarViewCache *_statusBarCache;
    NSString *_bundleIdentifier;
    SBZoomView *_zoomView;
    long long _orientation;
}

- (struct CGAffineTransform)_rotationTransformForOrientation:(long long)arg1;
- (void)_viewDismissing:(id)arg1;
- (void)_willAnimateDismiss:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 bundleIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

