/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIPluginHost.h"

@class BSEventQueue, FBUIApplicationResignActiveAssertion, NSHashTable, NSMutableSet, NSString, SBAssistantWindow, SBPasscodeLockDisableAssertion, UIViewController<SBUIPluginViewControllerInterface>;

@interface SBAssistantController : SBUIPluginHost
{
    BSEventQueue *_operationQueue;
    NSString *_appDisplayIDBeingHosted;
    SBAssistantWindow *_assistantWindow;
    _Bool _unlockedDevice;
    _Bool _launchedInStark;
    _Bool _isHidingOtherWindows;
    int _activationEvent;
    SBPasscodeLockDisableAssertion *_disableAssertion;
    NSMutableSet *_dismissingReasons;
    long long _pendingDismissViewType;
    NSHashTable *_observers;
    FBUIApplicationResignActiveAssertion *_resignActiveAssertion;
    UIViewController<SBUIPluginViewControllerInterface> *_mainScreenViewController;
}

+ (_Bool)isAssistantRunningHidden;
+ (_Bool)isAssistantViewVisible:(long long)arg1;
+ (_Bool)isAssistantVisible;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
+ (_Bool)shouldEnterAssistant;
+ (_Bool)supportedAndEnabled;
- (void)_activateSiriForPPT;
- (id)_activationSettingsWithDismissalDisallowed:(_Bool)arg1;
- (void)_bioAuthenticated:(id)arg1;
- (double)_defaultAnimatedDismissDurationForMainScreen;
- (void)_dismissForMainScreenWithFactory:(id)arg1 completion:(id)arg2;
- (void)_dismissUIPlugin:(id)arg1 animated:(_Bool)arg2;
- (id)_fakeStatusBarForOrientation:(long long)arg1;
- (_Bool)_isDismissingAllViews;
- (_Bool)_isPluginLoaded;
- (void)_loadPlugin;
- (void)_notePluginVisibilityDidChange;
- (void)_notifyObserversViewDidAppear:(long long)arg1;
- (void)_notifyObserversViewDidDisappear:(long long)arg1;
- (void)_notifyObserversViewWillAppear:(long long)arg1;
- (void)_notifyObserversViewWillDisappear:(long long)arg1;
- (void)_presentForMainScreenAnimated:(_Bool)arg1 completion:(id)arg2;
- (_Bool)_runActivateAssistantTest:(id)arg1;
- (void)_starkSiriDidAppear:(id)arg1;
- (void)_starkSiriDidDisappear:(id)arg1;
- (void)_starkSiriWillAppear:(id)arg1;
- (void)_starkSiriWillDisappear:(id)arg1;
- (void)_viewController:(id)arg1 animateAppearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 animateDisappearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 setShowsStatusBar:(_Bool)arg2;
- (void)_viewController:(id)arg1 willAnimateAppearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 willAnimateDisappearanceWithContext:(id)arg2;
- (void)_viewDidAppearOnMainScreen:(_Bool)arg1;
- (void)_viewDidAppearWithType:(long long)arg1;
- (void)_viewDidDisappearOnMainScreen:(_Bool)arg1;
- (void)_viewDidDisappearWithType:(long long)arg1;
- (void)_viewWillAppearOnMainScreen:(_Bool)arg1;
- (void)_viewWillDisappearOnMainScreen:(_Bool)arg1;
- (_Bool)activateIgnoringTouches;
- (id)activationSettings;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (void)dismissAssistantView:(long long)arg1 forAlertActivation:(id)arg2;
- (void)dismissAssistantViewIfNecessary:(long long)arg1;
- (void)dismissAssistantViewIfNecessary:(long long)arg1 withAnimation:(long long)arg2;
- (void)dismissAssistantViewIfNecessary:(long long)arg1 withAnimation:(long long)arg2 completion:(id)arg3;
- (void)dismissAssistantViewIfNecessary:(long long)arg1 withAnimation:(long long)arg2 factory:(id)arg3 completion:(id)arg4;
- (void)dismissPluginForEvent:(int)arg1;
- (_Bool)handleSiriButtonDownEventFromSource:(int)arg1 activationEvent:(int)arg2;
- (void)handleSiriButtonUpEventFromSource:(int)arg1;
- (void)handleSiriPreheatCommand;
- (id)init;
- (_Bool)isAssistantViewVisible:(long long)arg1;
- (id)mainScreenView;
- (_Bool)pluginSuppressesNotifications;
- (_Bool)pluginWantsActivationEvent:(int)arg1 eventSource:(int)arg2 interval:(double *)arg3;
- (_Bool)pluginWantsInterfaceOrientation:(long long *)arg1;
- (_Bool)pluginWantsScreenDimInterval:(double *)arg1;
- (void)preparePluginForActivationEvent:(int)arg1 eventSource:(int)arg2 afterInterval:(double)arg3;
- (void)removeObserver:(id)arg1;
@property(nonatomic) _Bool unlockedDevice; // @synthesize unlockedDevice=_unlockedDevice;
- (_Bool)shouldShowLockStatusBarTime;
- (id)transferOwnershipOfPasscodeLockDisableAssertion;
- (void)uiPlugin:(id)arg1 forceUpdateToInterfaceOrientation:(long long)arg2 animated:(_Bool)arg3;
- (void)uiPlugin:(id)arg1 isNowRunning:(_Bool)arg2;
- (_Bool)uiPlugin:(id)arg1 launchApplicationWithBundleID:(id)arg2 openURL:(id)arg3 allowDismissal:(_Bool)arg4;
- (_Bool)uiPlugin:(id)arg1 openURL:(id)arg2;
- (_Bool)uiPluginAttemptDeviceUnlock:(id)arg1 withPassword:(id)arg2 lockViewOwner:(id)arg3;
- (void)uiPluginUserEventOccurred:(id)arg1;
- (_Bool)uiPluginWantsActivation:(id)arg1 forEvent:(int)arg2 completion:(id)arg3;
- (id)window;

@end

