/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

#import "_SBUIWidgetHost-Protocol.h"

@class NSString, _SBUIWidgetViewController;

@interface SBAttributionWrapperViewController : UIViewController <_SBUIWidgetHost>
{
    _SBUIWidgetViewController *_attributionViewController;
    id <SBWidgetViewControllerDelegate> _widgetDelegate;
}

+ (id)_loadAttributionAppBundle;
+ (id)_newAttributionViewController;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)invalidatePreferredViewSize;
- (void)requestLaunchOfURL:(id)arg1;
- (void)requestPresentationOfViewController:(id)arg1 presentationStyle:(long long)arg2 context:(id)arg3 completion:(id)arg4;
- (void)setVisibleWidgetsIDs:(id)arg1;
@property(nonatomic) id <SBWidgetViewControllerDelegate> widgetDelegate; // @synthesize widgetDelegate=_widgetDelegate;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

