/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIImageView.h"

@interface SBAutoPurgingImageView : UIImageView
{
    id _block;
}

- (void)dealloc;
- (void)didMoveToWindow;
- (id)initWithImageGenerationBlock:(id)arg1;
- (void)setImage:(id)arg1;

@end

