/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class SBBannerContainerViewController, SBBannerContextView, SBBannerController;

@interface SBBannerGestureHandler : NSObject
{
    id <SBBannerGestureHandlerDelegate> _delegate;
    SBBannerContainerViewController *_bannerViewController;
    SBBannerController *_bannerController;
}

+ (id)notificationCenterHandlerWithBannerController:(id)arg1 bannerViewController:(id)arg2;
+ (id)pullDownHandlerWithBannerController:(id)arg1 bannerViewController:(id)arg2;
@property(readonly, nonatomic) SBBannerController *bannerController; // @synthesize bannerController=_bannerController;
@property(readonly, retain, nonatomic) SBBannerContextView *bannerView;
@property(readonly, retain, nonatomic) SBBannerContainerViewController *bannerViewController; // @synthesize bannerViewController=_bannerViewController;
- (void)dealloc;
@property(nonatomic) id <SBBannerGestureHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)handleGestureType:(long long)arg1 state:(long long)arg2 location:(struct CGPoint)arg3 displacement:(double)arg4 velocity:(double)arg5;
- (id)initWithBannerController:(id)arg1 bannerViewController:(id)arg2;
- (void)invalidate;

@end

