/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableSet, NSTimer;

@interface SBBacklightController : NSObject
{
    double _minimumLockIdleTime;
    NSTimer *_autoLockTimer;
    double _lastTimeIdleCausedDim;
    double _nextLockDurationAfterDim;
    unsigned int _disableAutoDimming:1;
    NSMutableSet *_idleTimerDisabledReasons;
    NSMutableSet *_spuriousScreenUndimmingAssertions;
    _Bool _isPendingScreenUnblankAfterCACommit;
    _Bool _undimmedForBulletinSinceLastUserEvent;
    _Bool _allowIdleTimerToBeReset;
}

+ (id)_sharedInstanceCreateIfNeeded:(_Bool)arg1;
+ (_Bool)deviceSupportsBacklightRamping;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (void)_animateBacklightToFactor:(float)arg1 duration:(double)arg2 source:(int)arg3 silently:(_Bool)arg4 completion:(id)arg5;
- (void)_autoLockTimerFired:(id)arg1;
- (void)_cancelSetBacklightFactorToZeroAfterDelay;
- (void)_clearAutoLockTimer;
- (double)_currentLockScreenIdleTimerInterval;
- (void)_deferredScreenUnblankDone;
- (void)_didIdle;
- (void)_lockScreenDimTimerFired;
- (_Bool)_lockScreenWantsUserEventNotifications;
- (double)_nextIdleTimeDuration;
- (double)_nextLockTimeDuration;
- (void)_performDeferredBacklightRampWorkWithInfo:(id)arg1;
- (void)_requestedUserEventNotificationOccurred;
- (void)_resetIdleTimerAndUndim:(_Bool)arg1 source:(int)arg2;
- (void)_resetLockScreenIdleTimerWithDuration:(double)arg1 mode:(int)arg2;
- (void)_setBacklightFactorToZeroForProx;
- (void)_startAllowingIdleTimer;
- (void)_startFadeOutAnimationIfNecessary;
- (void)_undimFromSource:(int)arg1;
- (void)_userEventOccurred;
- (void)_userEventPresenceTimerExpired;
- (void)_userEventsDidIdle;
- (void)addSpuriousScreenUndimmingAssertion:(id)arg1;
- (void)allowIdleSleep;
- (void)animateBacklightToFactor:(float)arg1 duration:(double)arg2 source:(int)arg3 completion:(id)arg4;
- (void)autoLockPrefsChanged;
- (void)cancelLockScreenIdleTimer;
- (void)clearIdleTimer;
- (double)defaultLockScreenDimInterval;
- (double)defaultLockScreenDimIntervalWhenNotificationsPresent;
- (id)idleTimerDisabledReasons;
- (id)init;
@property(readonly, nonatomic) _Bool isPendingScreenUnblankAfterCACommit; // @synthesize isPendingScreenUnblankAfterCACommit=_isPendingScreenUnblankAfterCACommit;
- (void)preventIdleSleep;
- (void)preventIdleSleepForNumberOfSeconds:(float)arg1;
- (void)removeSpuriousScreenUndimmingAssertion:(id)arg1;
- (void)resetIdleTimerAndUndim:(_Bool)arg1;
- (void)resetIdleTimerAndUndimForBulletin;
- (void)resetLockScreenIdleTimer;
- (void)resetLockScreenIdleTimerWithDuration:(double)arg1;
- (void)restoreBacklightFactorForProx;
@property(readonly, nonatomic) _Bool screenIsOff;
- (void)setBacklightFactor:(float)arg1 source:(int)arg2;
- (void)setBacklightFactorPending:(float)arg1;
- (void)setBacklightFactorToZeroForProx;
- (void)setIdleTimerDisabled:(_Bool)arg1 forReason:(id)arg2;
- (_Bool)shouldTurnOnScreenForBacklightSource:(int)arg1;
- (void)turnOnScreenFullyWithBacklightSource:(int)arg1;

@end

