/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@class SBBannerContextView;

@interface SBBannerContainerView : UIView
{
    _Bool _modal;
    SBBannerContextView *_bannerView;
    UIView *_backgroundView;
    UIView *_inlayView;
    double _maximumHeight;
    UIView *_inlayContainerView;
}

- (struct CGRect)_backgroundFrame;
- (double)_bannerBottomY;
- (struct CGRect)_inlineContainerFrame;
- (void)_layoutBackgroundView;
- (void)_layoutInlayContainerView;
@property(nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) SBBannerContextView *bannerView; // @synthesize bannerView=_bannerView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) UIView *inlayContainerView; // @synthesize inlayContainerView=_inlayContainerView;
@property(nonatomic) UIView *inlayView; // @synthesize inlayView=_inlayView;
@property(nonatomic, getter=isModal) _Bool modal; // @synthesize modal=_modal;
- (void)layoutSubviews;
@property(nonatomic) double maximumHeight; // @synthesize maximumHeight=_maximumHeight;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

