/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertItem.h"

@class SUDescriptor;

@interface SBBaseSoftwareUpdateAlertItem : SBAlertItem
{
    SUDescriptor *_descriptor;
}

- (void)activateDisplayWithURL:(id)arg1;
- (void)activateSoftwareUpdateSettingsDisplay;
- (void)dealloc;
@property(readonly, nonatomic) SUDescriptor *descriptor; // @synthesize descriptor=_descriptor;
- (_Bool)dismissOnLock;
- (_Bool)forcesModalAlertAppearance;
- (id)initWithDescriptor:(id)arg1;
- (_Bool)shouldShowInLockScreen;
- (id)updateName;

@end

