/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBBBBulletinInfo.h"

@class NSString, SBWidgetViewController;

@interface SBBBWidgetBulletinInfo : SBBBBulletinInfo
{
    NSString *_identifier;
    double _preferredViewHeight;
    _Bool _visible;
    struct {
        unsigned int isPreferredViewHeightValid:1;
    } _widgetBulletinInfoFlags;
}

- (void)dealloc;
- (double)heightForReusableViewForBulletinViewController:(id)arg1 layoutMode:(long long)arg2 bulletinLocation:(long long)arg3;
- (id)identifier;
- (id)originalSectionIdentifier;
- (void)populateReusableView:(id)arg1;
@property(nonatomic) double preferredViewHeight;
- (id)representedBulletin;
@property(readonly, nonatomic) SBWidgetViewController *representedWidget;
- (Class)reusableViewClass;
- (id)reusableViewIdentifier;
- (id)widgetIdentifier;

@end

