/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBBulletinBusyClient-Protocol.h"

@class BBObserver, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface SBBulletinSoundController : NSObject <BBObserverDelegate, SBBulletinBusyClient>
{
    BBObserver *_observer;
    NSMutableArray *_blockQueue;
    NSMutableDictionary *_playingSounds;
    NSMutableSet *_internalBulletinsWePlayedSoundsFor;
    NSMutableSet *_bulletinsRequiringExplicitKill;
    _Bool _deviceIsLocked;
    _Bool _quietModeEnabled;
    unsigned long long _quietModeState;
}

+ (id)_sharedInstanceCreateIfNecessary:(_Bool)arg1;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (void)_enqueueBlock:(id)arg1 forBulletin:(void)arg2;
- (void)_hardwareButtonPressed:(id)arg1;
- (_Bool)_playSoundForBulletin:(id)arg1 playedInternally:(_Bool)arg2;
- (_Bool)_shouldHonorPlaySoundRequestForBulletin:(id)arg1;
- (void)_stopSoundWithID:(id)arg1 internalOnly:(_Bool)arg2;
- (void)bulletinWindowStoppedBeingBusy;
- (void)dealloc;
- (id)init;
- (void)killSoundForBulletin:(id)arg1;
- (void)killSounds;
- (void)observer:(id)arg1 addBulletin:(id)arg2 forFeed:(unsigned long long)arg3 playLightsAndSirens:(_Bool)arg4 withReply:(id)arg5;
- (void)observer:(id)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned long long)arg2;
- (void)observer:(id)arg1 noteAlertBehaviorOverridesChanged:(unsigned long long)arg2;
- (void)observer:(id)arg1 noteInvalidatedBulletinIDs:(id)arg2;
- (void)observer:(id)arg1 noteServerConnectionStateChanged:(_Bool)arg2;
- (void)observer:(id)arg1 removeBulletin:(id)arg2;
- (_Bool)playSoundForBulletin:(id)arg1;
- (_Bool)quietModeEnabled;
- (unsigned long long)quietModeState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

