/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSString;

@interface SBBulletinListSubsection : NSObject
{
    _Bool _showsInLockScreen;
    _Bool _showsMessagePreview;
    NSString *_subsectionID;
}

- (void)dealloc;
- (id)initWithBulletinListSection:(id)arg1 subsectionID:(id)arg2;
@property(nonatomic) _Bool showsInLockScreen; // @synthesize showsInLockScreen=_showsInLockScreen;
@property(nonatomic) _Bool showsMessagePreview; // @synthesize showsMessagePreview=_showsMessagePreview;
@property(readonly, nonatomic) NSString *subsectionID; // @synthesize subsectionID=_subsectionID;

@end

