/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinAlertHandler <NSObject>
- (_Bool)bindBulletin:(id)arg1 forRegistry:(id)arg2;
- (void)handleEvent:(int)arg1 withBulletin:(id)arg2 forRegistry:(id)arg3;
@end

