/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinViewControllerDelegate <NSObject>

@optional
- (_Bool)bulletinViewController:(id)arg1 didSelectAction:(id)arg2 forBulletin:(id)arg3 inSection:(id)arg4;
- (_Bool)bulletinViewController:(id)arg1 didSelectBulletin:(id)arg2 inSection:(id)arg3;
- (long long)bulletinViewController:(id)arg1 insertionAnimationForBulletin:(id)arg2 inSection:(id)arg3;
- (long long)bulletinViewController:(id)arg1 removalAnimationForBulletin:(id)arg2 inSection:(id)arg3;
- (long long)bulletinViewController:(id)arg1 replacementAnimationForBulletin:(id)arg2 inSection:(id)arg3;
- (_Bool)bulletinViewController:(id)arg1 shouldHighlightBulletin:(id)arg2 inSection:(id)arg3;
- (long long)layoutModeForBulletinViewController:(id)arg1;
@end

