/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBDosidoAnimator.h"

@class SBStarkScreenController;

@interface SBCarDosidoAnimator : SBDosidoAnimator
{
    SBStarkScreenController *_screenController;
}

- (void)_doRealDosido:(id)arg1 withSpacingBetween:(double)arg2 completion:(id)arg3;
- (void)dealloc;
- (id)initWithParentView:(id)arg1 fromOrientation:(long long)arg2 starkScreenController:(id)arg3;

@end

