/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBControlCenterSectionViewController.h"

#import "MPUSystemMediaControlsDelegate-Protocol.h"

@class MPUSystemMediaControlsViewController, NSString;

@interface SBCCMediaControlsSectionController : SBControlCenterSectionViewController <MPUSystemMediaControlsDelegate>
{
    MPUSystemMediaControlsViewController *_systemMediaViewController;
}

- (struct CGSize)contentSizeForOrientation:(long long)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)sectionIdentifier;
- (void)systemMediaControlsViewController:(id)arg1 didReceiveTapOnControlType:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

