/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBCCSettingModule.h"

@interface SBCCWiFiSetting : SBCCSettingModule
{
}

+ (id)displayName;
+ (id)identifier;
- (void)_tearDown;
- (_Bool)_toggleState;
- (void)_updateState;
- (void)_updateWifiNotification:(id)arg1;
- (void)activate;
- (id)aggdKey;
- (void)deactivate;
- (void)dealloc;
- (id)glyphImageForState:(int)arg1;

@end

