/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBCCShortcutModule.h"

@interface SBCCTimerShortcut : SBCCShortcutModule
{
}

+ (id)displayName;
+ (id)identifier;
- (_Bool)_toggleState;
- (id)aggdKey;
- (id)glyphImageForState:(int)arg1;
- (id)init;

@end

