/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBCCShortcutModule.h"

@interface SBCCPaymentShortcut : SBCCShortcutModule
{
}

+ (id)displayName;
+ (_Bool)enabledByDefault;
+ (id)identifier;
+ (_Bool)isSupported:(int)arg1;
- (void)activateApp;
- (id)aggdKey;
- (id)glyphImageForState:(int)arg1;

@end

