/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBControlCenterSectionViewController.h"

#import "MPAVRoutingControllerDelegate-Protocol.h"
#import "SFAirDropDiscoveryActionSheetDelegate-Protocol.h"
#import "SFAirDropDiscoveryControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class BSTimer, MPAVRoutingController, MPAVRoutingSheet, MPAVRoutingViewController, MPAudioVideoRoutingPopoverController, NSString, SBCCButtonLikeSectionView, SFAirDropDiscoveryController;

@interface SBCCAirStuffSectionController : SBControlCenterSectionViewController <MPAVRoutingControllerDelegate, UIPopoverControllerDelegate, SFAirDropDiscoveryControllerDelegate, SFAirDropDiscoveryActionSheetDelegate, UIActionSheetDelegate>
{
    SBCCButtonLikeSectionView *_airPlaySection;
    SBCCButtonLikeSectionView *_airDropSection;
    MPAVRoutingController *_airPlayController;
    MPAVRoutingSheet *_airPlayModalSheet;
    MPAVRoutingViewController *_airPlayViewController;
    MPAudioVideoRoutingPopoverController *_airPlayPopoverController;
    SFAirDropDiscoveryController *_airDropDiscoveryController;
    _Bool _isVisible;
    _Bool _airPlayWasPreviouslyEnabled;
    BSTimer *_resetTimer;
    BSTimer *_airPlayTimer;
    _Bool _airPlayEnabled;
    _Bool _airDropEnabled;
}

+ (id)defaultFont;
+ (id)defaultFontTight;
+ (Class)viewClass;
- (void)_airDropTapped:(id)arg1;
- (void)_airPlayDoneButtonTapped:(id)arg1;
- (void)_airPlayTapped:(id)arg1;
- (void)_debugAirplaneStateDidChangeNotification:(id)arg1;
- (void)_debugWifiStateDidChangeNotification:(id)arg1;
- (void)_dismissAirplayControllerAnimated:(_Bool)arg1;
- (void)_noteSectionEnabledStateDidChange;
- (void)_showAirPlayView:(id)arg1;
- (void)_updateAirDropControlAsEnabled:(_Bool)arg1;
- (void)_updateAirPlayControlAsEnabled:(_Bool)arg1;
- (void)_updateForAirDropStateChange;
- (void)_updateForAirPlayStateChange;
- (void)_updateLayoutForSizeCategoryChange;
- (void)_updateSubsectionVisibilityAnimated:(_Bool)arg1;
@property(nonatomic) _Bool airDropEnabled; // @synthesize airDropEnabled=_airDropEnabled;
@property(nonatomic) _Bool airPlayEnabled; // @synthesize airPlayEnabled=_airPlayEnabled;
- (struct CGSize)contentSizeForOrientation:(long long)arg1;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)dealloc;
- (void)discoveryController:(id)arg1 actionSheetDidDismiss:(id)arg2;
- (void)discoveryController:(id)arg1 actionSheetWillDismiss:(id)arg2;
- (void)discoveryControllerSettingsDidChange:(id)arg1;
- (void)discoveryControllerVisibilityDidChange:(id)arg1;
- (_Bool)enabledForOrientation:(long long)arg1;
- (id)init;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)routingControllerAvailableRoutesDidChange:(id)arg1;
- (id)sectionIdentifier;
- (id)view;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

