/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBCCButtonSectionController.h"

@interface SBCCSettingsSectionController : SBCCButtonSectionController
{
}

+ (Class)buttonControllerClass;
- (struct CGSize)contentSizeForOrientation:(long long)arg1;
- (id)init;
- (id)sectionIdentifier;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end

