/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "_SBFVibrantView-Protocol.h"

@class NSString, UIColor, _SBFVibrantSettings;

@interface SBChevronView : UIView <_SBFVibrantView>
{
    UIView *_leftGrabberView;
    UIView *_rightGrabberView;
    double _animationDuration;
    long long _state;
    UIColor *_color;
    double _alphaComponent;
    _SBFVibrantSettings *_vibrantSettings;
    UIView *_tintView;
    UIView *_backgroundView;
    _Bool _unified;
    UIView *_alphaContainerView;
}

- (struct CGRect)_frameForGrabberView:(id)arg1 forState:(long long)arg2 unified:(_Bool)arg3;
- (void)_layoutGrabberView:(id)arg1 forState:(long long)arg2;
- (_Bool)_setState:(long long)arg1;
- (_Bool)_setUnified:(_Bool)arg1;
- (struct CGAffineTransform)_transformForGrabberView:(id)arg1 forState:(long long)arg2;
@property(nonatomic) double animationDuration;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)initWithColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setBackgroundView:(id)arg1;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)setState:(long long)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) _SBFVibrantSettings *vibrantSettings; // @synthesize vibrantSettings=_vibrantSettings;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

