/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBLiveIconImageView.h"

@class CALayer;

@interface SBClockApplicationIconImageView : SBLiveIconImageView
{
    CALayer *_seconds;
    CALayer *_minutes;
    CALayer *_hours;
    CALayer *_blackDot;
    CALayer *_redDot;
}

+ (void)_handleTimeChange:(id)arg1;
+ (void)_iconEditingStateChanged:(id)arg1;
+ (void)_timerFired:(id)arg1;
+ (void)initialize;
- (id)_generateSquareContentsImage;
- (void)_setAnimating:(_Bool)arg1;
- (void)_timerFiredWithComponents:(id)arg1 flags:(unsigned long long)arg2;
- (void)_updateUnanimatedWithComponents:(id)arg1;
- (id)contentsImage;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)updateAnimatingState;
- (void)updateUnanimated;

@end

