/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UICollectionViewCell.h"

@interface SBCollectionViewCell : UICollectionViewCell
{
    id <SBCollectionViewCellDelegate> _delegate;
    _Bool _performSetHighlighted;
    _Bool _protectDelayedUnhighlights;
}

- (void)_didSetHighlighted:(_Bool)arg1;
- (void)_performSetHighlighted;
@property(nonatomic) id <SBCollectionViewCellDelegate> delegate;
- (void)prepareForReuse;
@property(nonatomic) _Bool protectDelayedUnhighlights; // @synthesize protectDelayedUnhighlights=_protectDelayedUnhighlights;
- (void)setHighlighted:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1 afterDelay:(double)arg2;

@end

