/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "_UISettings.h"

@class NSString;

@interface SBControlCenterButtonSettings : _UISettings
{
    _Bool _enabled;
    NSString *_displayName;
    NSString *_identifier;
}

+ (id)createWithSettingClass:(Class)arg1;
+ (id)settingsControllerModule;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)setDefaultValues;

@end

