/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class UIColor;

@interface SBControlColorSettings : NSObject
{
    UIColor *_tintColor;
    UIColor *_selectedTintColor;
    UIColor *_textColor;
    UIColor *_selectedTextColor;
}

+ (id)settingsWithTintColor:(id)arg1 selectedTintColor:(id)arg2 textColor:(id)arg3 selectedTextColor:(id)arg4;
- (void)dealloc;
- (id)initWithTintColor:(id)arg1 selectedTintColor:(id)arg2 textColor:(id)arg3 selectedTextColor:(id)arg4;
@property(readonly, retain, nonatomic) UIColor *selectedTextColor; // @synthesize selectedTextColor=_selectedTextColor;
@property(readonly, retain, nonatomic) UIColor *selectedTintColor; // @synthesize selectedTintColor=_selectedTintColor;
@property(readonly, retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;

@end

