/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

#import "SBControlCenterViewControllerDelegate-Protocol.h"
#import "SBCoordinatedPresenting-Protocol.h"

@class FBUIApplicationResignActiveAssertion, NSHashTable, NSMutableSet, NSSet, NSString, SBChevronView, SBControlCenterRootView, SBControlCenterViewController, SBWindow, UIDynamicAnimator, UIImageView, UIView, _UIBackdropView, _UIDynamicValueAnimation;

@interface SBControlCenterController : UIViewController <SBControlCenterViewControllerDelegate, SBCoordinatedPresenting>
{
    SBWindow *_window;
    SBControlCenterRootView *_rootView;
    SBControlCenterViewController *_viewController;
    UIImageView *_coveredContentSnapshot;
    UIView *_fullScreenGrabberContainer;
    _UIBackdropView *_fullScreenGrabberBackdrop;
    SBChevronView *_fullScreenChevron;
    FBUIApplicationResignActiveAssertion *_resignActiveAssertion;
    NSMutableSet *_preventDismissalOnLockReasons;
    _Bool _uiLocked;
    NSHashTable *_observers;
    long long _orientation;
    _Bool _animatingInitialPresentation;
    _Bool _gotFirstBackdropUpdate;
    _Bool _completingTransitionOpen;
    _UIDynamicValueAnimation *_bounceAnimation;
    UIDynamicAnimator *_animator;
    unsigned long long _animatorStopCount;
    struct CGRect _animatorStopFrame;
    _Bool _inGrabberOnlyMode;
    _Bool _presented;
    _Bool _transitioning;
    _Bool _fullyRevealed;
    double _backgroundBrightness;
}

+ (id)_sharedInstanceCreatingIfNeeded:(_Bool)arg1;
+ (void)notifyControlCenterControl:(id)arg1 didActivate:(_Bool)arg2;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (_Bool)_allowShowTransitionSystemGesture;
- (void)_beginPresentation;
- (void)_cleanupAnimator;
- (void)_clearCoveredContentSnapshot;
- (double)_controlCenterHeightForTouchLocation:(struct CGPoint)arg1;
- (void)_dismissOnLock;
- (void)_dismissWithDuration:(double)arg1 additionalAnimations:(id)arg2 completion:(void)arg3;
- (void)_endPresentation;
- (void)_enumerateObservers:(id)arg1;
- (void)_finishPresenting:(_Bool)arg1 completion:(id)arg2;
- (void)_lockStateChangedNotification:(id)arg1;
- (id)_newDynamicAnimationForShow:(_Bool)arg1 currentValue:(double)arg2 velocity:(double)arg3 unitSize:(double)arg4;
- (void)_presentWithDuration:(double)arg1 completion:(id)arg2;
- (void)_revealSlidingViewToHeight:(double)arg1;
- (void)_setLockHUDHidden:(_Bool)arg1;
- (void)_uiRelockedNotification:(id)arg1;
- (void)_updateCoveredContentSnapshot;
- (void)_updateGrabberVisibility;
- (void)_updateRevealPercentage:(double)arg1;
- (double)_verticalPercentageMovedOnScreenForY:(double)arg1 stopY:(double)arg2;
- (id)_window;
- (double)_yValueForClosed;
- (double)_yValueForOpen;
- (void)abortAnimatedTransition;
- (void)addObserver:(id)arg1;
- (_Bool)allowHideTransition;
- (_Bool)allowShowTransition;
- (_Bool)allowShowTransitionSystemGesture;
@property(nonatomic) double backgroundBrightness; // @synthesize backgroundBrightness=_backgroundBrightness;
- (void)beginPresentationWithTouchLocation:(struct CGPoint)arg1;
- (void)beginTransitionWithTouchLocation:(struct CGPoint)arg1;
- (void)cancelTransition;
- (void)controlCenterViewController:(id)arg1 backdropViewDidUpdate:(id)arg2;
- (_Bool)controlCenterViewController:(id)arg1 canHandleGestureRecognizer:(id)arg2;
- (void)controlCenterViewController:(id)arg1 handlePan:(id)arg2;
- (void)controlCenterViewController:(id)arg1 handleTap:(id)arg2;
- (void)controlCenterViewControllerWantsDismissal:(id)arg1;
@property(readonly, nonatomic) long long coordinatedPresentingControllerIdentifier;
- (void)dealloc;
- (void)dismissAnimated:(_Bool)arg1;
- (void)dismissAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)dismissAnimated:(_Bool)arg1 withAdditionalAnimations:(id)arg2 completion:(void)arg3;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 completion:(id)arg2;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 wasCancelled:(_Bool)arg2 completion:(id)arg3;
- (_Bool)handleMenuButtonTap;
- (void)hideGrabberAnimated:(_Bool)arg1;
- (void)hideGrabberAnimated:(_Bool)arg1 completion:(id)arg2;
@property(readonly, nonatomic) double hintDisplacement;
@property(readonly, nonatomic) unsigned long long hintEdge;
@property(nonatomic) _Bool inGrabberOnlyMode; // @synthesize inGrabberOnlyMode=_inGrabberOnlyMode;
- (id)init;
- (_Bool)isAvailableWhileLocked;
@property(nonatomic, getter=isFullyRevealed) _Bool fullyRevealed; // @synthesize fullyRevealed=_fullyRevealed;
- (_Bool)isGrabberVisible;
@property(nonatomic, getter=isPresented) _Bool presented; // @synthesize presented=_presented;
- (_Bool)isPresentingControllerTransitioning;
@property(nonatomic, getter=isTransitioning) _Bool transitioning; // @synthesize transitioning=_transitioning;
@property(nonatomic, getter=isUILocked) _Bool UILocked; // @synthesize UILocked=_uiLocked;
- (_Bool)isVisible;
- (void)loadView;
- (void)presentAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)preventDismissalOnLock:(_Bool)arg1 forReason:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)resetControlAlpha;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)showGrabberAnimated:(_Bool)arg1;
- (void)updateControlAlphaForBrightness:(double)arg1;
- (void)updateTransitionWithTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (_Bool)wantsFullScreenLayout;

// Remaining properties
@property(readonly, nonatomic) NSSet *conflictingGestures;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSSet *gestures;
@property(readonly) unsigned long long hash;
@property(nonatomic) id <SBPresentingDelegate> presentingDelegate;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSSet *tapExcludedViews;

@end

