/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBDismissOnlyAlertItem : SBAlertItem
{
    NSString *_title;
    NSString *_body;
    double _autoDismissInterval;
}

- (double)autoDismissInterval;
- (id)bodyText;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)dealloc;
- (id)dismissButtonText;
- (id)initWithTitle:(id)arg1 body:(id)arg2;
- (void)performUnlockAction;
- (void)setAutoDismissInterval:(double)arg1;
- (void)setBodyText:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end

