/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"
#import "SBActivationSettings-Protocol.h"
#import "SBDeactivationSettings-Protocol.h"
#import "SBStateSettings-Protocol.h"

@protocol SBDisplayProtocol <NSObject, SBActivationSettings, SBDeactivationSettings, SBStateSettings>
- (void)activate;
- (_Bool)allowsEventOnlySuspension;
- (void)clearActivationSettings;
- (void)clearDeactivationSettings;
- (void)clearStateSettings;
- (id)copyDisplaySettings;
- (void)deactivate;
- (id)effectiveStatusBarStyleRequest;
- (long long)starkStatusBarStyle;
- (long long)statusBarStyle;
- (id)statusBarStyleRequest;
- (_Bool)suppressesBanners;
- (_Bool)suppressesControlCenter;
- (_Bool)suppressesNotificationCenter;
@end

