/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertItem.h"

@class NSFileCoordinator, NSTimer, NSURL;

@interface SBDocumentAccessAlertItem : SBAlertItem
{
    _Bool _downloadMessage;
    NSURL *_url;
    NSFileCoordinator *_fileCoordinator;
    NSTimer *_timer;
    id _subscriber;
}

- (void)_activateAlertItem:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)allowMenuButtonDismissal;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)dealloc;
- (_Bool)dismissOnLock;
@property(nonatomic) _Bool downloadMessage; // @synthesize downloadMessage=_downloadMessage;
@property(readonly, retain, nonatomic) NSFileCoordinator *fileCoordinator; // @synthesize fileCoordinator=_fileCoordinator;
- (id)init;
- (id)initWithURL:(id)arg1 fileCoordinator:(id)arg2;
- (void)scheduleToShowWithTimeInterval:(double)arg1;
@property(retain, nonatomic) id subscriber; // @synthesize subscriber=_subscriber;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (_Bool)shouldShowInLockScreen;
@property(readonly, copy, nonatomic) NSURL *url; // @synthesize url=_url;

@end

