/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBLeafIcon.h"

@class SBApplicationPlaceholder;

@interface SBDownloadingIcon : SBLeafIcon
{
    _Bool _wasUninstalledByUser;
    _Bool _isNewsstandDownload;
    SBApplicationPlaceholder *_appPlaceholder;
}

+ (id)leafIdentifierForApplicationPlaceholderBundleID:(id)arg1;
- (id)_darkenedIconImageForImage:(id)arg1;
- (id)appPlaceholder;
- (void)cancelDownload;
- (void)completeUninstall;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)gridCellImage;
- (id)homescreenIconImage;
- (_Bool)iconAppearsInNewsstand;
- (id)initWithApplicationPlaceholder:(id)arg1;
- (_Bool)isDownloadingIcon;
- (_Bool)isNewsstandDownload;
- (id)realDisplayName;
- (void)reloadForStatusChange;
- (void)setApplicationPlaceholder:(id)arg1;
- (void)setNewsstandDownload:(_Bool)arg1;
- (void)setUninstalledByUser:(_Bool)arg1;
- (id)uninstallAlertBody;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
- (_Bool)uninstalledByUser;

@end

