/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAwayViewPluginController.h"

@class NSMutableDictionary;

@interface SBEventObserverRegistry : SBAwayViewPluginController
{
    void *_provider;
    NSMutableDictionary *_observers;
}

+ (id)sharedInstance;
- (void)addObserverWithToken:(unsigned long long)arg1 forEvent:(id)arg2;
- (void)handleEvent:(id)arg1 token:(unsigned long long)arg2 action:(long long)arg3;
- (id)init;
- (void)postEventToInterestedObservers:(struct __CFString *)arg1;
- (void)removeObserverWithToken:(unsigned long long)arg1 forEvent:(id)arg2;
- (void)setValue:(_Bool)arg1 forState:(struct __CFString *)arg2;

@end

