/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBIconImageView.h"

#import "SBFolderIconObserver-Protocol.h"
#import "SBIconBlurryBackgroundViewObserver-Protocol.h"

@class NSMutableArray, NSString, SBFloatyFolderView, SBFolderIconBackgroundView, UIView, _SBIconGridWrapperView;

@interface SBFolderIconImageView : SBIconImageView <SBFolderIconObserver, SBIconBlurryBackgroundViewObserver>
{
    SBFolderIconBackgroundView *_backgroundView;
    UIView *_accessibilityBackgroundView;
    UIView *_pageGridContainer;
    _SBIconGridWrapperView *_leftWrapperView;
    _SBIconGridWrapperView *_rightWrapperView;
    NSMutableArray *_pageElements;
    unsigned long long _currentPageIndex;
    SBFloatyFolderView *_crossfadeFolderView;
    UIView *_crossfadeScalingView;
    _Bool _animating;
}

- (id)_currentPageElement;
- (id)_folderIcon;
- (id)_generateSquareContentsImage;
- (Class)_iconGridImageClass;
- (struct CGSize)_interPageSpacing;
- (struct CGSize)_interiorGridSizeClipRect;
- (void)_performScrollingMovingToLeft:(_Bool)arg1 movingToRight:(_Bool)arg2 targetPageIndex:(unsigned long long)arg3 targetPageScrollRow:(unsigned long long)arg4 newLeftElement:(id)arg5 newRightElement:(id)arg6 animated:(_Bool)arg7;
- (void)_setAnimating:(_Bool)arg1;
- (void)_setPageElements:(id)arg1;
- (void)_setupGridViewsInDefaultConfiguration;
- (void)_showLeftMinigrid;
- (void)_showRightMinigrid;
- (void)_updateAccessibilityBackgroundContrast;
- (void)_updateRasterization;
- (id)backgroundView;
- (void)blurryBackgroundViewDidChangeWhetherBlurring:(id)arg1;
- (unsigned long long)centerVisibleMiniIconIndex;
- (void)cleanupAfterFloatyFolderCrossfade;
- (id)contentsImage;
- (id)darkeningOverlayImage;
- (void)dealloc;
- (unsigned long long)firstVisibleMiniIconIndex;
- (void)folderIcon:(id)arg1 didUpdateGridImage:(id)arg2 forListIndex:(unsigned long long)arg3 forContainedIconImageUpdate:(id)arg4;
- (struct CGRect)frameForMiniIconAtIndex:(unsigned long long)arg1;
- (struct CGRect)frameForMiniIconAtIndexPath:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (unsigned long long)lastVisibleMiniIconIndex;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)prepareToCrossfadeWithFloatyFolderView:(id)arg1 allowFolderInteraction:(_Bool)arg2;
- (void)scrollToFirstGapAnimated:(_Bool)arg1;
- (void)scrollToGapOrTopIfFullOfPage:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)scrollToTopOfFirstPageAnimated:(_Bool)arg1;
- (void)scrollToTopOfPage:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setBackgroundAndIconGridImageAlpha:(double)arg1;
- (void)setBackgroundScale:(double)arg1;
- (void)setFloatyFolderCrossfadeFraction:(double)arg1;
- (void)setIcon:(id)arg1 location:(int)arg2 animated:(_Bool)arg3;
- (void)setIconGridImageAlpha:(double)arg1;
- (void)setSuppressesBlurryBackgroundChanges:(_Bool)arg1;
- (void)setWallpaperRelativeCenter:(struct CGPoint)arg1;
- (id)snapshot;
- (void)updateImageAnimated:(_Bool)arg1;
- (struct CGRect)visibleImageRelativeFrameForMiniIconAtIndex:(unsigned long long)arg1;
- (unsigned long long)visibleMiniIconCount;
- (unsigned long long)visibleMiniIconListIndex;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

