/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBZoomView.h"

@interface SBFullscreenZoomView : SBZoomView
{
    _Bool _hasImage;
    _Bool _hasFullSizedImage;
    id _surface;
}

- (void)_addBlackBackground;
- (id)_initWithFrame:(struct CGRect)arg1;
- (id)_initWithView:(id)arg1 screen:(id)arg2 needsBlackBackground:(_Bool)arg3;
- (id)initWithContextHostSnapshotView:(id)arg1 screen:(id)arg2;
- (id)initWithContextHostView:(id)arg1 screen:(id)arg2;
- (id)initWithImage:(id)arg1 screen:(id)arg2 opaque:(_Bool)arg3;
- (id)initWithSnapshotFrame:(struct CGRect)arg1 screen:(id)arg2 image:(id)arg3 originalImageOrientation:(long long)arg4 currentImageOrientation:(long long)arg5 interfaceOrientation:(long long)arg6 doubleHeightStatusBar:(_Bool)arg7 preventSplit:(_Bool)arg8 needsZoomFilter:(_Bool)arg9 asyncDecodeImage:(_Bool)arg10 opaque:(_Bool)arg11 forceRotationOnPhone:(_Bool)arg12 forJail:(_Bool)arg13;
@property(readonly, nonatomic) id surface;

@end

