/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class CPLRUDictionary;

@interface SBGestureViewVendor : NSObject
{
    CPLRUDictionary *m_cache;
}

+ (id)sharedInstance;
- (void)clearCacheForApp:(id)arg1 reason:(id)arg2;
- (void)clearCacheForReason:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)maskViewIfNeeded:(id)arg1 gestureType:(unsigned long long)arg2 viewType:(int)arg3 contextHostViewRequester:(id)arg4 app:(id)arg5;
- (id)viewForApp:(id)arg1 gestureType:(unsigned long long)arg2 includeStatusBar:(_Bool)arg3;
- (id)viewForApp:(id)arg1 gestureType:(unsigned long long)arg2 includeStatusBar:(_Bool)arg3 decodeImage:(_Bool)arg4;

@end

