/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "_UISettings.h"

@interface SBHomeButtonTimingSettings : _UISettings
{
    double _tapDuration;
    double _delay;
}

+ (id)createWithDuration:(double)arg1 delay:(double)arg2;
+ (id)settingsControllerModule;
@property(nonatomic) double delay; // @synthesize delay=_delay;
- (id)description;
- (id)displayName;
- (void)setDefaultValues;
@property(nonatomic) double tapDuration; // @synthesize tapDuration=_tapDuration;

@end

