/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@class NSString, UIImage, UIImageView, _UIBackdropView;

@interface SBHUDView : UIView
{
    int _level;
    NSString *_title;
    NSString *_subtitle;
    UIImage *_image;
    _Bool _showsProgress;
    float _progress;
    UIView *_blockView;
    _UIBackdropView *_backdropView;
    UIImageView *_backdropMaskImageView;
}

+ (long long)numberOfProgressIndicatorSteps;
+ (float)progressIndicatorStep;
- (id)_blockColorForValue:(float)arg1;
- (void)_updateBackdropMask;
- (void)_updateBlockView;
- (void)_updateBlockView:(id)arg1 value:(float)arg2 blockSize:(struct CGSize)arg3 point:(struct CGPoint)arg4;
- (void)cancelDismissal;
- (void)dealloc;
- (void)dismissWithCompletion:(id)arg1;
- (_Bool)displaysLabel;
@property(retain, nonatomic) UIImage *image;
- (id)initWithHUDViewLevel:(int)arg1;
- (void)layoutSubviews;
@property(nonatomic) int level; // @synthesize level=_level;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(nonatomic) _Bool showsProgress; // @synthesize showsProgress=_showsProgress;
@property(retain, nonatomic) NSString *subtitle;
@property(retain, nonatomic) NSString *title;

@end

