/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@class NSMutableArray;

@interface SBIconContentView : UIView
{
    long long _orientation;
    NSMutableArray *_folderContentViews;
}

- (id)_folderViews;
- (struct CGRect)_frameForFolderView:(id)arg1;
- (void)clearAllFolderContentViews;
- (void)dealloc;
- (void)didAddSubview:(id)arg1;
- (id)initWithOrientation:(long long)arg1;
- (void)layoutSubviews;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void)popFolderContentView:(id)arg1;
- (void)pushFolderContentView:(id)arg1;
- (void)updateLayoutWithDuration:(double)arg1;

@end

