/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIImage.h"

#import "SBCountedMapValue-Protocol.h"

@class NSString, SBIconLabelImageParameters;

@interface SBIconLabelLegibilityImage : UIImage <SBCountedMapValue>
{
    SBIconLabelImageParameters *_parameters;
}

+ (id)_legibilityImageCountedMap;
+ (id)_legibilityImageForIconLabelImage:(id)arg1 parameters:(id)arg2;
+ (id)_legibilityImagePool;
+ (struct CGRect)_legibilityImageRectForLabelImage:(id)arg1 style:(long long)arg2;
+ (struct CGSize)_maxLegibilityImageSizeForLabelSize:(struct CGSize)arg1;
+ (double)_strengthForLegibilityStyle:(long long)arg1;
+ (void)checkinLegibilityImage:(id)arg1;
+ (id)checkoutLegibilityImageWithLabelImage:(id)arg1 parameters:(id)arg2;
- (id)_initWithCGImage:(struct CGImage *)arg1 scale:(double)arg2 orientation:(long long)arg3 parameters:(id)arg4;
- (id)countedMapKey;
- (void)dealloc;
@property(readonly) SBIconLabelImageParameters *parameters; // @synthesize parameters=_parameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

