/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBIconController.h"

@interface SBIconController (Folders)
- (void)_addToFolderAnimation:(id)arg1 didFinish:(id)arg2 context:(id)arg3;
- (void)_animateFolder:(id)arg1 open:(_Bool)arg2 animated:(_Bool)arg3 withCompletion:(id)arg4;
- (void)_cleanupForClosingFolderAnimated:(_Bool)arg1;
- (void)_closeFolderController:(id)arg1 animated:(_Bool)arg2 withCompletion:(id)arg3;
- (void)_compactRootListsAfterFolderCloseWithAnimation:(_Bool)arg1;
- (struct CGRect)_contentViewRelativeFrameForIcon:(id)arg1;
- (void)_disableReachabilityImmediately:(_Bool)arg1;
- (void)_dropIconIntoOpenFolder:(id)arg1 withInsertionPath:(id)arg2;
- (void)_dropIconOutOfClosingFolder:(id)arg1 withInsertionPath:(id)arg2;
- (void)_folderControllerDidReceiveCancelReachabilityAction:(id)arg1;
- (void)_folderDidFinishOpenClose:(_Bool)arg1 animated:(_Bool)arg2;
- (unsigned long long)_folderRowsForFolder:(id)arg1;
- (unsigned long long)_folderRowsForFolder:(id)arg1 inOrientation:(long long)arg2;
- (void)_moveDroppedIconsToLocation:(int)arg1;
- (void)_noteFolderAnimationStateDidChange;
- (void)_presentNotificationCenterForReachability;
- (id)_proposedFolderNameForGrabbedIcon:(id)arg1 recipientIcon:(id)arg2;
- (void)_runFolderCloseTest;
- (void)_runFolderOpenTest;
- (void)_runScrollFolderTest:(long long)arg1;
- (void)_setAnimatingFolderCreation:(_Bool)arg1;
- (void)_setFolderToOpenAfterScrolling:(id)arg1;
- (void)_setHasAnimatingFolder:(_Bool)arg1;
- (void)_snapshotFadeDidStop:(id)arg1 finished:(id)arg2 snapshot:(id)arg3;
- (void)addIcons:(id)arg1 intoFolderIcon:(id)arg2 animated:(_Bool)arg3 openFolderOnFinish:(_Bool)arg4 complete:(id)arg5;
- (void)closeFolderAnimated:(_Bool)arg1;
- (void)closeFolderAnimated:(_Bool)arg1 withCompletion:(id)arg2;
- (id)createNewFolderFromRecipientIcon:(id)arg1 grabbedIcon:(id)arg2;
- (void)getListView:(id *)arg1 folder:(id *)arg2 relativePath:(id *)arg3 forIndexPath:(id)arg4 createIfNecessary:(_Bool)arg5;
- (_Bool)hasAnimatingFolder;
- (_Bool)hasOpenFolder;
- (id)iconListViewAtIndex:(unsigned long long)arg1 inFolder:(id)arg2 createIfNecessary:(_Bool)arg3;
- (_Bool)isDroppingIcon:(id)arg1;
- (_Bool)isDroppingIconsInOrOutOfFolder;
- (_Bool)isNewsstandOpen;
- (id)openFolder;
- (void)openFolder:(id)arg1 animated:(_Bool)arg2;
- (void)replaceFolderIcon:(id)arg1 byContainedIcon:(id)arg2 animated:(_Bool)arg3;
- (void)shiftFolderViewsForKeyboardAppearing:(_Bool)arg1 keyboardHeight:(double)arg2;
@end

