/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBReusableViewMapDelegate-Protocol.h"

@protocol SBIconViewMapDelegate <SBReusableViewMapDelegate>
- (Class)iconViewClassForIcon:(id)arg1 location:(int)arg2;
- (int)viewMap:(id)arg1 locationForIcon:(id)arg2;

@optional
- (unsigned long long)viewMap:(id)arg1 numberOfViewsToPrepareOfClass:(Class)arg2;
- (id)viewMapShouldPrepareViewsOfClasses:(id)arg1;
@end

