/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIImage.h"

@interface SBIconGridImage : UIImage
{
    unsigned long long _numberOfCells;
}

+ (id)_gridImageForNumberOfCells:(unsigned long long)arg1 withPreviousGridImage:(id)arg2 cellImageProviderBlock:(id)arg3;
+ (struct CGSize)cellSize;
+ (struct CGSize)cellSpacing;
+ (id)gridImageForNumberOfCells:(unsigned long long)arg1 withCellImageProviderBlock:(id)arg2;
+ (unsigned long long)numberOfColumns;
+ (unsigned long long)numberOfRowsForNumberOfCells:(unsigned long long)arg1;
+ (struct CGRect)rectAtIndex:(unsigned long long)arg1 maxCount:(unsigned long long)arg2;
+ (struct CGSize)sizeForNumberOfRows:(unsigned long long)arg1;
- (id)gridImageByPatchingWithCellImageProviderBlock:(id)arg1;
- (id)iconImageAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long numberOfCells;
@property(readonly, nonatomic) unsigned long long numberOfColumns;
@property(readonly, nonatomic) unsigned long long numberOfRows;

@end

