/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableArray, NSString, SBFolderController, SBFolderControllerAnimationContext, SBIconAnimationSettings, UIView;

@interface SBIconAnimator : NSObject
{
    double _fraction;
    _Bool _startAnimationAfterRotationEnds;
    _Bool _windowIsRotating;
    _Bool _cleanedUp;
    NSMutableArray *_pendedAnimationContexts;
    SBFolderControllerAnimationContext *_animationContext;
    NSString *_instanceIdentifier;
    _Bool _invalidated;
    _Bool _animatesInnerFolderViews;
    id <SBIconAnimatorDelegate> _delegate;
    SBIconAnimationSettings *_settings;
    SBFolderController *_folderController;
}

- (void)_allowRotationOnMainWindowIfNecessary:(_Bool)arg1;
- (void)_animateToFraction:(double)arg1 afterDelay:(double)arg2 withSharedCompletion:(id)arg3;
- (void)_animateToFractionFromContext:(id)arg1;
- (void)_animateToFractionFromPendingContexts;
- (id)_centralAnimationFactory;
- (void)_cleanupAnimation;
- (void)_invalidateCompletions;
- (_Bool)_isDelayedForRotation;
- (unsigned long long)_numberOfSignificantAnimations;
- (void)_prepareAnimation;
- (void)_setAnimationFraction:(double)arg1;
- (void)_windowFinishedRotating;
- (void)animateToFraction:(double)arg1 afterDelay:(double)arg2 withCompletion:(id)arg3;
@property(nonatomic) _Bool animatesInnerFolderViews; // @synthesize animatesInnerFolderViews=_animatesInnerFolderViews;
@property(readonly, retain, nonatomic) SBFolderControllerAnimationContext *animationContext; // @synthesize animationContext=_animationContext;
- (id)centralAnimationFactory;
- (void)cleanup;
- (void)dealloc;
@property(nonatomic) id <SBIconAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, retain, nonatomic) SBFolderController *folderController; // @synthesize folderController=_folderController;
- (id)initWithFolderController:(id)arg1;
@property(nonatomic) _Bool invalidated; // @synthesize invalidated=_invalidated;
- (void)prepare;
@property(readonly, retain, nonatomic) UIView *referenceView;
- (void)setFraction:(double)arg1;
@property(retain, nonatomic) SBIconAnimationSettings *settings; // @synthesize settings=_settings;

@end

