/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBReusableViewMap.h"

#import "SBIconIndexNodeObserver-Protocol.h"
#import "SBIconObserver-Protocol.h"
#import "SBIconViewObserver-Protocol.h"

@class NSMapTable, NSString, SBIconModel, _UILegibilitySettings;

@interface SBIconViewMap : SBReusableViewMap <SBIconObserver, SBIconIndexNodeObserver, SBIconViewObserver>
{
    SBIconModel *_model;
    NSMapTable *_iconViewsForIcons;
    id <SBIconViewMapDelegate> _delegate;
    id <SBIconViewDelegate> _viewDelegate;
    NSMapTable *_labelsForIcons;
    NSMapTable *_lightLegibilityImagesForIcons;
    NSMapTable *_darkLegibilityImagesForIcons;
    NSMapTable *_accessoryImagesForIcons;
    _UILegibilitySettings *_legibilitySettings;
}

+ (id)homescreenMap;
- (void)_addIconView:(id)arg1 forIcon:(id)arg2;
- (void)_cacheAccessoryImagesForIcon:(id)arg1 location:(int *)arg2;
- (void)_cacheImagesForIcon:(id)arg1;
- (void)_cacheLabelImagesForIcon:(id)arg1 location:(int)arg2;
- (id)_iconViewForIcon:(id)arg1;
- (void)_modelReloadedIcons;
- (void)_modelReloadedState;
- (void)_modelRemovedIcon:(id)arg1;
- (void)_modelWillReloadState;
- (void)_observeIconAndCacheIfNecessary:(id)arg1;
- (void)_recycleIconView:(id)arg1;
- (void)dealloc;
- (id)extraIconViewForIcon:(id)arg1;
- (void)iconAccessoriesDidUpdate:(id)arg1;
@property(readonly, retain, nonatomic) SBIconModel *iconModel; // @synthesize iconModel=_model;
- (void)iconViewDidChangeLocation:(id)arg1;
- (id)iconViewForIcon:(id)arg1;
- (id)initWithIconModel:(id)arg1 delegate:(id)arg2 viewDelegate:(id)arg3;
- (void)invalidate;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (id)mappedIconViewForIcon:(id)arg1;
- (id)newViewOfClass:(Class)arg1;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)purgeIconFromMap:(id)arg1;
- (void)purgeRecycledIconViewsForClass:(Class)arg1;
- (void)recycleAndPurgeAll;
- (void)recycleIconView:(id)arg1;
- (void)recycleViewForIcon:(id)arg1;
- (void)tryToReplaceIcon:(id)arg1 withIcon:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

