/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "SBIconAccessoryView-Protocol.h"

@class NSString, SBDarkeningImageView, SBIconAccessoryImage;

@interface SBIconBadgeView : UIView <SBIconAccessoryView>
{
    NSString *_text;
    SBDarkeningImageView *_incomingTextView;
    _Bool _animating;
    id _queuedAnimation;
    _Bool _displayingAccessory;
    SBIconAccessoryImage *_backgroundImage;
    SBDarkeningImageView *_backgroundView;
    SBIconAccessoryImage *_textImage;
    SBDarkeningImageView *_textView;
}

+ (id)_checkoutBackgroundImage;
+ (id)_checkoutImageForText:(id)arg1 highlighted:(_Bool)arg2;
+ (id)_createImageForText:(id)arg1 highlighted:(_Bool)arg2;
+ (double)_maxTextWidth;
+ (struct CGPoint)_overhang;
+ (id)_textFont;
+ (struct CGPoint)_textOffset;
+ (double)_textPadding;
+ (id)checkoutAccessoryImagesForIcon:(id)arg1 location:(int)arg2;
- (void)_clearText;
- (void)_configureAnimatedForText:(id)arg1 highlighted:(_Bool)arg2 withPreparation:(id)arg3 animation:(void)arg4 completion:(id)arg5;
- (void)_crossfadeToTextImage:(id)arg1 withPreparation:(id)arg2 animation:(void)arg3 completion:(id)arg4;
- (void)_resizeForTextImage:(id)arg1;
- (void)_zoomInWithTextImage:(id)arg1 preparation:(id)arg2 animation:(void)arg3 completion:(id)arg4;
- (void)_zoomOutWithPreparation:(id)arg1 animation:(void)arg2 completion:(id)arg3;
- (struct CGPoint)accessoryOriginForIconBounds:(struct CGRect)arg1;
- (void)configureAnimatedForIcon:(id)arg1 location:(int)arg2 highlighted:(_Bool)arg3 withPreparation:(id)arg4 animation:(void)arg5 completion:(id)arg6;
- (void)configureForIcon:(id)arg1 location:(int)arg2 highlighted:(_Bool)arg3;
- (void)dealloc;
- (_Bool)displayingAccessory;
- (id)init;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)setAccessoryBrightness:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

