/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBIconAnimator.h"

#import "SBIconIndexNodeObserver-Protocol.h"

@class NSMapTable, NSSet, NSString, SBIconListModel, SBIconListView, SBIconZoomSettings;

@interface SBIconZoomAnimator : SBIconAnimator <SBIconIndexNodeObserver>
{
    NSMapTable *_listIconToViewMap;
    NSMapTable *_dockIconToViewMap;
    NSSet *_criticalIconNodeIdentifiers;
    SBIconListModel *_iconListModel;
    SBIconListView *_iconListView;
    SBIconListView *_dockListView;
}

- (void)_animateToFraction:(double)arg1 afterDelay:(double)arg2 withSharedCompletion:(id)arg3;
- (void)_applyLabelAlphaFraction:(double)arg1;
- (void)_cleanupAnimation;
- (void)_clearObservers;
- (void)_iconModelDidRelayout;
- (void)_iconModelDidReload;
- (void)_invalidateAnimationForSignificantIconModelChangesForReason:(id)arg1;
- (unsigned long long)_numberOfSignificantAnimations;
- (void)_prepareAnimation;
- (void)_setAnimationFraction:(double)arg1;
- (void)_setDockListView:(id)arg1;
- (void)_setIconListView:(id)arg1;
@property(retain, nonatomic) NSSet *criticalIconNodeIdentifiers; // @synthesize criticalIconNodeIdentifiers=_criticalIconNodeIdentifiers;
- (void)dealloc;
- (unsigned long long)dockIconCount;
@property(readonly, retain, nonatomic) SBIconListView *dockListView; // @synthesize dockListView=_dockListView;
- (void)enumerateIconsAndIconViewsWithHandler:(id)arg1;
@property(readonly, retain, nonatomic) SBIconListView *iconListView; // @synthesize iconListView=_iconListView;
- (id)iconViewForIcon:(id)arg1;
- (id)initWithFolderController:(id)arg1;
- (unsigned long long)listIconCount;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) SBIconZoomSettings *settings;
@property(readonly) Class superclass;

@end

