/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "NSFastEnumeration-Protocol.h"
#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, NSString, SBFolder, SBIconIndexMutableList;

@interface SBIconListModel : NSObject <SBIconIndexNode, NSFastEnumeration>
{
    SBIconIndexMutableList *_icons;
    unsigned long long _maxIconCount;
    NSHashTable *_nodeObservers;
    NSHashTable *_listObservers;
    _Bool _iconStateIsDirty;
    SBFolder *_folder;
}

- (void)_notifyListObservers:(id)arg1;
- (_Bool)addIcon:(id)arg1;
- (_Bool)addIcon:(id)arg1 asDirty:(_Bool)arg2;
- (void)addListObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (_Bool)allowsAddingIcon:(id)arg1;
- (unsigned long long)compactIcons;
- (id)containedNodeIdentifiers;
- (_Bool)containsIcon:(id)arg1;
- (_Bool)containsLeafIconWithIdentifier:(id)arg1;
- (_Bool)containsNodeIdentifier:(id)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (unsigned long long)firstFreeSlotIndex;
- (unsigned long long)firstFreeSlotIndexForType:(int)arg1;
- (id)folder;
- (id)iconAtIndex:(unsigned long long)arg1;
- (id)icons;
- (id)iconsOfClass:(Class)arg1;
- (unsigned long long)indexForIcon:(id)arg1;
- (unsigned long long)indexForLeafIconWithIdentifier:(id)arg1;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)init;
- (id)initWithFolder:(id)arg1 maxIconCount:(unsigned long long)arg2;
- (id)insertIcon:(id)arg1 atIndex:(unsigned long long *)arg2;
- (_Bool)isEmpty;
- (_Bool)isFull;
- (_Bool)isIconStateDirty;
- (void)list:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)list:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)markIconStateClean;
- (unsigned long long)maxNumberOfIcons;
- (_Bool)needsCompacting;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (id)nodeIdentifier;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(unsigned long long)arg2;
- (unsigned long long)numberOfIcons;
- (id)placeIcon:(id)arg1 atIndex:(unsigned long long *)arg2;
- (void)removeIcon:(id)arg1;
- (void)removeIconAtIndex:(unsigned long long)arg1;
- (void)removeListObserver:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)warmUpIconImagesForLocation:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

