/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol SBIconModelApplicationDataSource <NSObject>
- (id)allApplications;
- (int)appVisibilityOverrideForBundleIdentifier:(id)arg1;
- (id)defaultIconState;
- (id)firstPageLeafIdentifiers;
- (_Bool)isNewsstandEnabled;
- (_Bool)isNewsstandSupported;
- (_Bool)updateAppIconVisibilityOverridesShowing:(id *)arg1 hiding:(id *)arg2;
@end

