/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, NSString, UIImage;

@interface SBIcon : NSObject <SBIconIndexNode>
{
    NSHashTable *_observers;
    id _badgeNumberOrString;
    unsigned int _uninstalled:1;
    UIImage *_cachedIconImages[13];
}

- (id)accessoryTextForLocation:(int)arg1;
- (int)accessoryTypeForLocation:(int)arg1;
- (void)addNodeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (_Bool)allowsUninstall;
- (id)automationID;
- (id)badgeNumberOrString;
- (long long)badgeValue;
- (_Bool)canEllipsizeLabel;
- (_Bool)canReceiveGrabbedIcon;
- (_Bool)canTightenLabel;
- (void)completeUninstall;
- (id)containedNodeIdentifiers;
- (_Bool)containsNodeIdentifier:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)displayName;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)generateIconImage:(int)arg1;
- (id)getGenericIconImage:(int)arg1;
- (id)getIconImage:(int)arg1;
- (id)getStandardIconImageForLocation:(int)arg1;
- (id)getUnmaskedIconImage:(int)arg1;
- (id)gridCellImage;
- (_Bool)hasObserver:(id)arg1;
- (int)iconFormatForLocation:(int)arg1;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)init;
- (_Bool)isBeta;
- (_Bool)isRecentlyUpdated;
- (_Bool)isUninstalled;
- (_Bool)launchEnabled;
- (void)launchFromLocation:(int)arg1;
- (void)localeChanged;
- (long long)localizedCompareDisplayNames:(id)arg1;
- (_Bool)matchesEntity:(id)arg1;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (id)nodeIdentifier;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(unsigned long long)arg2;
- (void)noteBadgeDidChange;
- (_Bool)progressIsPaused;
- (double)progressPercent;
- (long long)progressState;
- (void)purgeCachedImages;
- (void)reloadIconImage;
- (void)reloadIconImagePurgingImageCache:(_Bool)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)setBadge:(id)arg1;
- (void)setUninstalled;
- (_Bool)shouldAnimateProgress;
- (_Bool)shouldCacheImageForFormat:(int)arg1;
@property(readonly, nonatomic) _Bool shouldWarmUp;
- (id)tags;
- (id)uninstallAlertBody;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

