/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBRelaunchAppWorkspaceTransaction.h"

@class SBUIAnimationController, SSKeybagRequest, SSVClaimApplicationsRequest;

@interface SBKeybagNonsenseWorkspaceTransaction : SBRelaunchAppWorkspaceTransaction
{
    SSKeybagRequest *_keybagRequest;
    SSVClaimApplicationsRequest *_claimApplicationsRequest;
    SBUIAnimationController *_zoomDownAnimationController;
    _Bool _keepAliveTillZoomDownFinishes;
}

- (void)_begin;
- (_Bool)_canBeInterrupted;
- (void)_completeKeybagRefetchForApp:(id)arg1 relaunch:(_Bool)arg2;
- (void)_didComplete;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_endAnimation;
- (void)_endKeybagRefetchAndZoomDownNicely;
- (void)_handleAppRelaunch:(id)arg1;
- (id)_setupAnimationForApp:(id)arg1;
- (_Bool)_shouldComplete;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)dealloc;
- (id)initWithAlertManager:(id)arg1 application:(id)arg2;
- (_Bool)shouldWatchdog:(id *)arg1;

@end

