/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol SBLeafIconDataSource <NSObject>
- (id)icon:(id)arg1 defaultImageWithFormat:(int)arg2;
- (id)icon:(id)arg1 imageWithFormat:(int)arg2;
- (_Bool)icon:(id)arg1 launchFromLocation:(int)arg2;
- (int)iconAccessoryType:(id)arg1;
- (_Bool)iconAllowsLaunch:(id)arg1;
- (_Bool)iconAllowsUninstall:(id)arg1;
- (_Bool)iconAppearsInNewsstand:(id)arg1;
- (id)iconBadgeNumberOrString:(id)arg1;
- (_Bool)iconCanEllipsizeLabel:(id)arg1;
- (_Bool)iconCanTightenLabel:(id)arg1;
- (_Bool)iconCompleteUninstall:(id)arg1;
- (id)iconDisplayName:(id)arg1;
- (id)iconFormattedAccessoryString:(id)arg1;
- (_Bool)iconIsBeta:(id)arg1;
- (_Bool)iconIsRecentlyUpdated:(id)arg1;
- (unsigned long long)iconPriority:(id)arg1;
- (_Bool)iconProgressIsPaused:(id)arg1;
- (double)iconProgressPercent:(id)arg1;
- (long long)iconProgressState:(id)arg1;
@end

