/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBLockScreenNotificationBannerItem.h"

@class SBUISound;

@interface SBLockScreenNotificationBulletinBannerItem : SBLockScreenNotificationBannerItem
{
    SBUISound *_sound;
}

- (id)_bulletinListItem;
- (id)attachmentImage;
- (id)attachmentText;
- (void)dealloc;
- (id)iconImage;
- (id)initWithListItem:(id)arg1;
- (id)lockScreenActionContext;
- (id)message;
- (id)sound;
- (id)sourceDate;
- (id)title;

@end

