/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBLockOverlayViewController.h"

@class NSString, SBFDeviceBlockTimer;

@interface SBLockScreenDeviceBlockViewController : SBLockOverlayViewController
{
    SBFDeviceBlockTimer *_blockTimer;
}

@property(retain, nonatomic) SBFDeviceBlockTimer *blockTimer; // @synthesize blockTimer=_blockTimer;
- (void)dealloc;
- (void)loadView;
@property(readonly, nonatomic) NSString *slideToUnlockText;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

