/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBNotificationCell.h"

@class SBLockScreenActionContext, SBLockScreenNotificationScrollView, UIButton, UILabel, UIScrollView;

@interface SBLockScreenNotificationCell : SBNotificationCell
{
    _Bool _isTopCell;
    double _currentContentAlpha;
    id <SBAwayListCellButtonHandler> _actionButtonHandler;
    SBLockScreenNotificationScrollView *_contentScrollView;
    SBLockScreenActionContext *_lockScreenActionContext;
    UILabel *_unlockTextLabel;
    id <UIScrollViewDelegate> _delegate;
    _Bool _resetsScrollOnPluginWillDisable;
    double _contentScrollViewWidth;
}

+ (id)defaultColorForEventDate;
+ (id)defaultColorForPrimaryText;
+ (id)defaultColorForRelevanceDate;
+ (id)defaultColorForSecondaryText;
+ (id)defaultColorForSubtitleText;
+ (double)lastLineBottomPadding;
+ (double)rowHeightForTitle:(id)arg1 subtitle:(id)arg2 body:(id)arg3 maxLines:(unsigned long long)arg4 attachmentSize:(struct CGSize)arg5 secondaryContentSize:(struct CGSize)arg6 datesVisible:(_Bool)arg7 rowWidth:(double)arg8 includeUnlockActionText:(_Bool)arg9;
+ (double)unlockLineBaselineOffsetFromPreviousLine;
+ (_Bool)wantsUnlockActionText;
- (id)_buttonWithLabel:(id)arg1;
- (void)_handleActionButtonPress:(id)arg1;
- (void)_notePluginWillDisable:(id)arg1;
- (id)_secondaryContentView;
- (long long)_separatorBackdropOverlayBlendMode;
- (void)_setSeparatorBackdropOverlayBlendMode:(long long)arg1;
- (double)_unlockTextOriginY;
- (void)_updateUnlockText:(id)arg1;
- (id)_vibrantTextColor;
@property(readonly, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) double contentScrollViewWidth; // @synthesize contentScrollViewWidth=_contentScrollViewWidth;
- (void)dealloc;
@property(nonatomic) id <UIScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) _Bool isTopCell; // @synthesize isTopCell=_isTopCell;
- (void)layoutSubviews;
@property(retain, nonatomic) SBLockScreenActionContext *lockScreenActionContext; // @synthesize lockScreenActionContext=_lockScreenActionContext;
- (void)prepareForReuse;
- (void)resetScrollView;
@property(nonatomic) _Bool resetsScrollOnPluginWillDisable; // @synthesize resetsScrollOnPluginWillDisable=_resetsScrollOnPluginWillDisable;
- (void)scrollToOriginAnimated:(_Bool)arg1;
- (void)setButtonLabel:(id)arg1 handler:(id)arg2;
- (void)setContentAlpha:(double)arg1;
- (void)setRelevanceDateLabel:(id)arg1;
- (_Bool)shouldAnimateHintForTouchInCell:(struct CGPoint)arg1;
- (_Bool)shouldVerticallyCenterContent;

// Remaining properties
@property(retain, nonatomic) UIButton *actionButton;

@end

