/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@interface SBLockStateAggregator : NSObject
{
    unsigned long long _lockState;
}

+ (id)sharedInstance;
- (id)_descriptionForLockState:(unsigned long long)arg1;
- (void)_updateLockState;
- (void)dealloc;
- (id)description;
- (_Bool)hasAnyLockState;
- (id)init;
- (unsigned long long)lockState;

@end

