/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class SBAwayViewPluginController, SBLockOverlayContext, SBLockScreenViewController;

@interface SBLockScreenPluginTransition : NSObject
{
    SBAwayViewPluginController *_fromController;
    SBAwayViewPluginController *_toController;
    SBLockScreenViewController *_lockScreenViewController;
    SBLockOverlayContext *_fromOverlay;
    SBLockOverlayContext *_toOverlay;
}

- (void)_addToView;
- (void)_removeFromView;
- (void)_removeViewFromHierarchy:(id)arg1;
- (void)beginTransition;
- (void)dealloc;
@property(readonly, retain) SBAwayViewPluginController *fromController; // @synthesize fromController=_fromController;
@property(readonly, retain) SBLockOverlayContext *fromOverlay; // @synthesize fromOverlay=_fromOverlay;
- (id)initWithContext:(id)arg1;
@property(readonly, retain) SBLockScreenViewController *lockScreenViewController; // @synthesize lockScreenViewController=_lockScreenViewController;
@property(readonly, retain) SBAwayViewPluginController *toController; // @synthesize toController=_toController;
@property(readonly, retain) SBLockOverlayContext *toOverlay; // @synthesize toOverlay=_toOverlay;

@end

