/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBControlCenterObserver-Protocol.h"
#import "SBPresentingDelegate-Protocol.h"
#import "SBUIBiometricEventObserver-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSDate, NSMapTable, NSMutableSet, NSString, SBLockScreenHintLongPressGestureRecognizer, SBLockScreenHintPanGestureRecognizer, SBLockScreenHintTapGestureRecognizer, SBLockScreenView;

@interface SBLockScreenHintManager : NSObject <UIGestureRecognizerDelegate, SBPresentingDelegate, SBControlCenterObserver, SBUIBiometricEventObserver>
{
    _Bool _gestureHandlingEnabled;
    _Bool _guestGestureActive;
    _Bool _didEvaluatePressDelay;
    _Bool _fingerOnMesa;
    SBLockScreenView *_lockScreenView;
    SBLockScreenHintTapGestureRecognizer *_tapGesture;
    SBLockScreenHintLongPressGestureRecognizer *_longPressGesture;
    SBLockScreenHintPanGestureRecognizer *_panGesture;
    NSMutableSet *_gestures;
    NSMapTable *_controllersToGuestGestures;
    NSMapTable *_controllersToConflictingGuestGestures;
    long long _gestureState;
    id <SBCoordinatedPresenting> _activeController;
    unsigned long long _activeHintEdge;
    NSDate *_initialTouchTimeStamp;
    struct CGPoint _initialPanLocationInViewSpace;
}

- (void)_abortCurrentAnimationForController:(id)arg1;
- (void)_beginControllerPresentationForPan;
- (struct CGRect)_bottomGrabberZone;
- (struct CGRect)_bottomLeftGrabberZone;
- (struct CGRect)_cameraGrabberZone;
- (_Bool)_canControllerWithIdentifier:(long long)arg1 becomeActiveWithTouchAtLocation:(struct CGPoint)arg2;
- (void)_cancelGuestGesturesExcludingController:(id)arg1;
- (long long)_compareControllerWithIdentifier:(long long)arg1 withControllerWithIdentifier:(long long)arg2;
- (id)_controller:(id)arg1 managedGestureLikeGesture:(id)arg2;
- (id)_controllerForGesture:(id)arg1;
- (id)_coordinatedPresentingControllerWithIdentifier:(long long)arg1;
- (void)_dismissControllerForPress:(_Bool)arg1;
- (_Bool)_doesController:(id)arg1 manageGestureLikeGesture:(id)arg2;
- (double)_elapsedTapPeriod;
- (void)_endControllerPresentationForPanInState:(long long)arg1;
- (void)_handlePan:(id)arg1;
- (void)_handlePress:(id)arg1;
- (void)_handleTap:(id)arg1;
- (_Bool)_hasCoordinatedPresentingController:(id)arg1;
- (_Bool)_hasTapPeriodElapsed;
- (_Bool)_hintGestureShouldBegin:(id)arg1;
- (void)_initializeInitialTouchTimeStamp;
- (void)_installLocalGestures;
- (_Bool)_isBounceEnabledForController:(id)arg1 locationInWindow:(struct CGPoint)arg2;
- (_Bool)_isController:(id)arg1 excludingViewsUnderGesture:(id)arg2;
- (_Bool)_isPresentationEnabledForController:(id)arg1 locationInWindow:(struct CGPoint)arg2;
- (id)_lockScreenBottomLeftController;
- (id)_lockScreenCameraController;
- (id)_lockScreenNotificationListController;
- (id)_lockScreenNotificationListView;
- (id)_lockScreenViewController;
- (void)_presentingController:(id)arg1 willHandlePan:(id)arg2;
- (void)_presentingController:(id)arg1 willHandleTap:(id)arg2;
- (void)_reenableGestures;
- (void)_removeAllGestures;
- (void)_resetGesture:(id)arg1;
- (void)_resetGesture:(id)arg1 forController:(id)arg2;
- (void)_resetGestureSequence;
- (void)_resetGestureSequenceAndReenableGestures;
- (void)_resetInitialPanLocation;
- (void)_setLocalGesture:(id)arg1 enabled:(_Bool)arg2;
- (id)_tapGestureForActiveController;
- (void)_tapPeriodElapsed;
- (struct CGRect)_topGrabberZone;
- (void)_updateControllerPresentationForPan;
- (void)_updateControllerPresentationForPress:(_Bool)arg1;
- (void)_updateControllerPresentationForTap;
- (void)_updateControllerPresentationForTapOrPress:(id)arg1 withAnimation:(id)arg2 abortingCurrentAnimation:(void)arg3;
- (void)_updateGrabberStateForControllerIfNecessary:(id)arg1;
- (id)_viewForGestures;
@property(retain, nonatomic) id <SBCoordinatedPresenting> activeController; // @synthesize activeController=_activeController;
@property(nonatomic) unsigned long long activeHintEdge; // @synthesize activeHintEdge=_activeHintEdge;
- (void)addCoordinatedPresentingController:(id)arg1;
- (void)biometricEventMonitor:(id)arg1 handleBiometricEvent:(unsigned long long)arg2;
- (void)controlCenterDidDismiss;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterWillPresent;
@property(retain, nonatomic) NSMapTable *controllersToConflictingGuestGestures; // @synthesize controllersToConflictingGuestGestures=_controllersToConflictingGuestGestures;
@property(retain, nonatomic) NSMapTable *controllersToGuestGestures; // @synthesize controllersToGuestGestures=_controllersToGuestGestures;
- (void)dealloc;
@property(nonatomic) _Bool didEvaluatePressDelay; // @synthesize didEvaluatePressDelay=_didEvaluatePressDelay;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) long long gestureState; // @synthesize gestureState=_gestureState;
@property(retain, nonatomic) NSMutableSet *gestures; // @synthesize gestures=_gestures;
- (id)init;
@property(nonatomic) struct CGPoint initialPanLocationInViewSpace; // @synthesize initialPanLocationInViewSpace=_initialPanLocationInViewSpace;
@property(retain, nonatomic) NSDate *initialTouchTimeStamp; // @synthesize initialTouchTimeStamp=_initialTouchTimeStamp;
@property(nonatomic, getter=isFingerOnMesa) _Bool fingerOnMesa; // @synthesize fingerOnMesa=_fingerOnMesa;
@property(nonatomic, getter=isGestureHandlingEnabled) _Bool gestureHandlingEnabled; // @synthesize gestureHandlingEnabled=_gestureHandlingEnabled;
@property(nonatomic, getter=isGuestGestureActive) _Bool guestGestureActive; // @synthesize guestGestureActive=_guestGestureActive;
@property(retain, nonatomic) SBLockScreenView *lockScreenView; // @synthesize lockScreenView=_lockScreenView;
@property(retain, nonatomic) SBLockScreenHintLongPressGestureRecognizer *longPressGesture; // @synthesize longPressGesture=_longPressGesture;
- (void)notificationCenterDidDismiss:(id)arg1;
@property(retain, nonatomic) SBLockScreenHintPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
- (void)presentingController:(id)arg1 conflictingGestureDidBegin:(id)arg2;
- (void)presentingController:(id)arg1 conflictingGestureDidEnd:(id)arg2;
- (_Bool)presentingController:(id)arg1 gestureRecognizer:(id)arg2 shouldReceiveTouch:(id)arg3;
- (_Bool)presentingController:(id)arg1 gestureRecognizerShouldBegin:(id)arg2;
- (void)presentingController:(id)arg1 willHandleGesture:(id)arg2;
- (void)presentingControllerDidFinishPresentation:(id)arg1;
- (void)removeCoordinatedPresentingController:(id)arg1;
@property(retain, nonatomic) SBLockScreenHintTapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

