/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBLockOverlayViewController.h"

#import "SBLockOverlayViewDelegate-Protocol.h"

@class NSString, SBAwayBulletinListItem, SBLockOverlayView;

@interface SBLockScreenFullscreenBulletinViewController : SBLockOverlayViewController <SBLockOverlayViewDelegate>
{
    SBLockOverlayView *_bulletinView;
    _Bool _performedAction;
    SBAwayBulletinListItem *_bulletinItem;
}

- (id)_alternateAction;
- (id)_calculatedTitleForAlternateActionButton;
- (id)_customTitleForAlternateActionButton;
- (id)_dismissAction;
- (_Bool)_hasAlternateAction;
- (id)_lockScreenActionContext;
- (id)_snoozeAction;
- (id)_titleForAlternateActionButton;
@property(retain, nonatomic) SBAwayBulletinListItem *bulletinItem; // @synthesize bulletinItem=_bulletinItem;
- (void)dealloc;
- (void)handleTapGestureFromView:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)isRepeatingSound;
- (void)loadView;
- (void)lockButtonPressed:(id)arg1;
- (void)performAction:(id)arg1;
- (void)performAlternateAction;
- (void)performDismissAction;
- (void)performSnoozeAction;
- (void)performUnlockAction;
- (id)slideToUnlockText;
- (void)updateContent;
- (void)viewDidAppear:(_Bool)arg1;
- (void)volumeChanged:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

