/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBCoordinatedPresenting-Protocol.h"
#import "SBPresentingDelegate-Protocol.h"
#import "SBUIPasscodeLockViewDelegate-Protocol.h"

@class BBObserver, LSBestAppSuggestion, NSMutableArray, NSSet, NSString, NSURL, SBApplication, SBBounceSettings, SBDisableAppStatusBarAlphaChangesAssertion, SBLockScreenBounceAnimator, SBLockScreenView, SBPasscodeLockDisableAssertion, SBUIPasscodeViewWithLockScreenStyle, SBWallpaperEffectView, UIImage, UIView, _UIDynamicValueAnimation;

@interface SBLockScreenSlideUpToAppController : NSObject <SBPresentingDelegate, SBUIPasscodeLockViewDelegate, SBCoordinatedPresenting>
{
    _Bool _isInScreenOffMode;
    UIView *_slidingStatusBarView;
    SBLockScreenView *_lockScreenView;
    _Bool _currentlySliding;
    SBLockScreenBounceAnimator *_bounceAnimator;
    _UIDynamicValueAnimation *_dynamicAnimation;
    id <SBPresentingDelegate> _presentingDelegate;
    SBBounceSettings *_bounceSettings;
    SBApplication *_targetApp;
    LSBestAppSuggestion *_targetAppInfo;
    _Bool _targetAppIsSiri;
    NSURL *_targetURL;
    UIImage *_grabberImage;
    BBObserver *_bulletinObserver;
    _Bool _attemptingUnlock;
    _Bool _showingPasscodeView;
    _Bool _dismissingPasscodeView;
    _Bool _defaultImagesNeedUpdateUponPasscodeExit;
    NSMutableArray *_deferredAppUpdateBlocks;
    _Bool _executingDeferredAppUpdateBlocks;
    _Bool _waitingToDeactivateForActivityLaunch;
    UIView *_clippingView;
    UIView *_appPortraitDefaultImageView;
    UIView *_appLandscapeDefaultImageView;
    UIView *_appBackgroundView;
    SBWallpaperEffectView *_fakeBlurBackgroundView;
    SBUIPasscodeViewWithLockScreenStyle *_passcodeView;
    UIView *_passcodeOverscrollView;
    UIView *_appContextHostView;
    _Bool _disableGracePeriodForCamera;
    SBPasscodeLockDisableAssertion *_disableGracePeriodForCameraAssertion;
    _Bool _disablingOcclusionsForTargetApp;
    _Bool _launchingAppFromNonOccludedState;
    id <SBLockScreenSlideUpToAppControllerDelegate> _delegate;
    _Bool _didAbortBounce;
    SBDisableAppStatusBarAlphaChangesAssertion *_disableStatusBarAssertion;
    double _boundaryTranslationInY;
}

- (void)_activateApp:(id)arg1 withAppInfo:(id)arg2 andURL:(id)arg3 animated:(_Bool)arg4;
- (void)_addOrRemovePasscodeViewIfNecessary;
- (void)_animateSlideDownWithVelocity:(struct CGPoint)arg1 completion:(id)arg2;
- (void)_animateSlideUpWithVelocity:(struct CGPoint)arg1 completion:(id)arg2;
- (void)_cleanupBackgroundLaunchAndContextHostingNonsense;
- (void)_cleanupFromDismissal;
- (void)_commonGestureCleanup;
- (void)_deviceBlockedStateChanged:(id)arg1;
- (void)_executeDeferredAppUpdateBlocks;
- (void)_finishSlideDownWithCompletion:(id)arg1;
- (double)_foregroundTranslationForLocation:(struct CGPoint)arg1;
- (void)_handleAppLaunchedUnderLockScreenWithResult:(long long)arg1;
- (id)_lockScreenViewFakeStatusBar;
- (id)_newBounceAnimatorWithGrabberView:(id)arg1;
- (id)_newDynamicAnimationForTargetValue:(double)arg1 withInitialVelocity:(double)arg2;
- (id)_newGrabberView;
- (void)_passcodeLockStateChanged;
- (void)_reloadAppDefaultImages;
- (void)_setupBounceAnimatorAndGrabberView;
- (void)abortAnimatedTransition;
- (void)abortDynamicAnimationForScreenOff;
- (void)activate;
- (void)activateTargetApp;
- (void)beginPresentationWithTouchLocation:(struct CGPoint)arg1;
- (id)bounceAnimator;
@property(nonatomic) double boundaryTranslationInY; // @synthesize boundaryTranslationInY=_boundaryTranslationInY;
- (void)cancelGestureRecognizer:(id)arg1;
@property(readonly, nonatomic) long long coordinatedPresentingControllerIdentifier;
- (id)customSlideToUnlockText;
- (void)deactivate;
- (void)dealloc;
@property(nonatomic) id <SBLockScreenSlideUpToAppControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool didAbortBounce; // @synthesize didAbortBounce=_didAbortBounce;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
@property(retain, nonatomic) SBDisableAppStatusBarAlphaChangesAssertion *disableStatusBarAssertion; // @synthesize disableStatusBarAssertion=_disableStatusBarAssertion;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 wasCancelled:(_Bool)arg2 completion:(id)arg3;
- (void)finalizeGesture;
@property(readonly, nonatomic) NSSet *gestures;
- (_Bool)hasActiveUnlockActionContext;
- (void)hideSlidingStatusBar;
@property(readonly, nonatomic) double hintDisplacement;
@property(readonly, nonatomic) unsigned long long hintEdge;
- (id)init;
- (_Bool)isPresentingControllerTransitioning;
- (_Bool)isShowingPasscodeView;
- (id)lockScreenView;
- (void)passcodeLockViewCancelButtonPressed:(id)arg1;
- (void)passcodeLockViewPasscodeDidChange:(id)arg1;
- (void)passcodeLockViewPasscodeEntered:(id)arg1;
- (void)passcodeLockViewPasscodeEnteredViaMesa:(id)arg1;
- (void)performGeneralCleanupForUserAction:(_Bool)arg1;
- (void)prepareForSlideUpAnimation;
- (void)presentTargetAppAnimated:(_Bool)arg1;
- (_Bool)presentingController:(id)arg1 gestureRecognizer:(id)arg2 shouldReceiveTouch:(id)arg3;
- (_Bool)presentingController:(id)arg1 gestureRecognizerShouldBegin:(id)arg2;
- (void)presentingController:(id)arg1 willHandleGesture:(id)arg2;
- (void)presentingControllerDidFinishPresentation:(id)arg1;
@property(nonatomic) id <SBPresentingDelegate> presentingDelegate;
- (void)reenableGestureRecognizer:(id)arg1;
- (void)setDisableGracePeriodForCamera:(_Bool)arg1;
- (void)setGrabberOnLockScreen:(id)arg1;
- (void)setGrabberViewImage:(id)arg1;
- (void)setInScreenOffMode:(_Bool)arg1;
- (void)setLockScreenView:(id)arg1 force:(_Bool)arg2;
- (void)setTargetApp:(id)arg1 withLSInfo:(id)arg2;
- (void)setTargetURL:(id)arg1;
@property(readonly, nonatomic) NSSet *tapExcludedViews;
- (void)translateSlidingViewByY:(double)arg1;
- (void)treatCurrentPositionAsBoundaryforGesture:(id)arg1;
- (void)updateTransitionWithTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (_Bool)wantsToShowCustomSlideToUnlockText;
- (_Bool)wantsToShowStatusBar;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, nonatomic) NSSet *conflictingGestures;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

