/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

@class NSTimer, _UILegibilitySettings;

@interface SBLockScreenDateViewController : UIViewController
{
    NSTimer *_updateTimer;
    _Bool _disablesUpdates;
    _UILegibilitySettings *_legibilitySettings;
}

- (void)_addObservers;
- (void)_backlightChanged;
- (void)_startUpdateTimer;
- (void)_stopUpdateTimer;
- (void)_updateFormat;
- (void)_updateView;
- (id)dateView;
- (id)dateViewIfExists;
- (void)dealloc;
@property(nonatomic) _Bool disablesUpdates; // @synthesize disablesUpdates=_disablesUpdates;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, getter=isDateHidden) _Bool dateHidden;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void)loadView;
- (void)setContentAlpha:(double)arg1 withDateVisible:(_Bool)arg2;
- (void)setCustomSubtitleText:(id)arg1 withColor:(id)arg2;
- (void)setView:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;

@end

