/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBLockOverlayViewController.h"

@class NSString, SBLockScreenTemperatureWarningView;

@interface SBLockScreenTemperatureWarningViewController : SBLockOverlayViewController
{
    SBLockScreenTemperatureWarningView *_warningView;
}

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
@property(readonly, nonatomic) NSString *slideToUnlockText;

@end

