/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSString, SBDismissOnlyAlertItem;

@interface SBLockdownManager : NSObject
{
    int _state;
    _Bool _settingUpActivationState;
    _Bool _isBricked;
    _Bool _isDeveloperDevice;
    _Bool _hasShownMismatchedSIM;
    SBDismissOnlyAlertItem *_activatingAlertItem;
    NSString *_unqiueDeviceIdentifier;
}

+ (id)sharedInstance;
- (void)_activationFailed;
- (_Bool)_hasEverRegistered;
- (_Bool)_isRegisteredToNetwork;
- (void)_postAlertsIfNeeded;
- (void)_resetActivationState;
- (void)_serviceAvailabilityChanged:(id)arg1;
- (void)_setCurrentAlertItem:(id)arg1;
- (void)_setHasEverRegistered:(_Bool)arg1;
- (void)_setupActivationState;
- (_Bool)_shouldShowTelephonyAlerts;
- (_Bool)brickedDevice;
- (void)dealloc;
- (id)developerBuildExpirationDate;
- (id)init;
- (_Bool)isDeveloperDevice;
- (int)lockdownState;

@end

