/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

@protocol SBLockScreenTimerViewControllerDelegate
- (void)timerControllerDidStartTimer:(id)arg1;
- (void)timerControllerDidStopTimer:(id)arg1;
@end

