/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@class NSArray, NSLayoutConstraint, SBLockScreenBatteryFillView, _UIBackdropView, _UILegibilityLabel, _UILegibilitySettings;

@interface SBLockScreenBatteryChargingView : UIView
{
    UIView *_batteryContainerView;
    _UIBackdropView *_batteryBlurView;
    SBLockScreenBatteryFillView *_batteryFillView;
    _UILegibilityLabel *_chargePercentLabel;
    NSArray *_batteryConstraints;
    NSLayoutConstraint *_batteryTopOffset;
    _UILegibilitySettings *_legibilitySettings;
}

- (double)_batteryBaseline;
- (double)_batteryNoseOffset;
- (id)_chargePercentFont;
- (double)_chargingTextBaselineOffset;
- (void)_prepareConstraints;
- (void)_setChargeString:(id)arg1;
@property(nonatomic) _Bool batteryVisible;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void)setChargePercentage:(long long)arg1 detailed:(_Bool)arg2;

@end

