/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBFMappedImageCache.h"

@interface SBMappedImageCache : SBFMappedImageCache
{
}

+ (id)imageNamed:(id)arg1;
+ (id)imageNamed:(id)arg1 options:(int)arg2;
+ (id)persistentCache;
+ (id)sessionCache;

@end

