/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class CMGestureManager, NSMutableDictionary;

@interface SBMotionGestureController : NSObject
{
    NSMutableDictionary *_observersByPriority;
    CMGestureManager *_motionGestureManager;
}

+ (void)initialize;
+ (id)sharedInstance;
- (void)_addGestureManager;
- (void)_addGestureObserver:(id)arg1 withPriority:(unsigned long long)arg2;
- (void)_enumerateObserversByPriority:(id)arg1;
- (_Bool)_hasObservers;
- (id)_highestPriorityObservers;
- (void)_notifyObserversOfGesture:(int)arg1;
- (id)_observersForPriority:(unsigned long long)arg1;
- (void)_removeGestureManager;
- (void)_removeGestureObserver:(id)arg1;
- (void)_updateGestureManager;
- (void)addGestureObserver:(id)arg1;
- (void)addGestureObserver:(id)arg1 withPriority:(unsigned long long)arg2;
- (void)dealloc;
- (id)init;
- (void)removeGestureObserver:(id)arg1;

@end

