/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

#import "SBUISizeObservingViewDelegate-Protocol.h"
#import "_UISettingsKeyPathObserver-Protocol.h"

@class NSArray, NSString, SBBulletinObserverViewController, SBModeControlManager, SBNotificationSeparatorView, UIScrollView, UISwipeGestureRecognizer, UIView, UIViewController<SBModeViewControllerContentProviding>;

@interface SBModeViewController : UIViewController <SBUISizeObservingViewDelegate, _UISettingsKeyPathObserver>
{
    id <SBBulletinActionHandler> _delegate;
    SBBulletinObserverViewController *_selectedViewController;
    SBBulletinObserverViewController *_deselectedViewController;
    UIScrollView *_contentView;
    UIView *_headerView;
    SBModeControlManager *_modeControl;
    UISwipeGestureRecognizer *_leftSwipeGestureRecognizer;
    UISwipeGestureRecognizer *_rightSwipeGestureRecognizer;
    SBNotificationSeparatorView *_separator;
    struct {
        unsigned int isContentLayoutValid:1;
        unsigned int isSegmentLayoutValid:1;
        unsigned int isRequestHandlingEnabled:1;
        unsigned int shouldLoadAllChildViews:1;
    } _modeViewControllerFlags;
}

+ (id)_buttonTitleFont;
- (_Bool)_addBulletinObserverViewController:(id)arg1;
- (void)_backgroundContrastDidChange:(id)arg1;
- (_Bool)_contentOffset:(struct CGPoint *)arg1 forChildViewController:(id)arg2;
- (double)_headerViewHeightForMode:(long long)arg1;
- (void)_invalidateContentLayout;
- (void)_invalidateSegmentLayout;
- (_Bool)_isChildViewControllerViewLoadedInContentView:(id)arg1;
- (_Bool)_isRequestHandlingEnabled;
- (void)_layoutContentIfNecessary;
- (void)_layoutHeaderViewIfNecessary;
- (void)_layoutSegmentsIfNecessary;
- (void)_loadContentView;
- (void)_loadHeaderView;
- (struct CGRect)_modeControlFrameWithHeaderBounds:(struct CGRect)arg1 forMode:(long long)arg2;
- (id)_newSwipeGestureRecognizerWithDirection:(unsigned long long)arg1;
- (void)_setContentViewContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)_setSelectedBulletinObserverViewController:(id)arg1 animated:(_Bool)arg2;
- (void)_setSelectedSegmentIndex:(long long)arg1;
- (id)_viewIfLoaded;
- (void)addViewController:(id)arg1;
- (void)dealloc;
@property(nonatomic) id <SBBulletinActionHandler> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBBulletinObserverViewController *deselectedViewController; // @synthesize deselectedViewController=_deselectedViewController;
- (_Bool)handleAction:(id)arg1 forBulletin:(id)arg2 withCompletion:(id)arg3;
- (void)handleModeChange:(id)arg1;
- (void)hostDidDismiss;
- (void)hostDidPresent;
- (void)hostWillDismiss;
- (void)hostWillPresent;
@property(nonatomic, getter=isRequestHandlingEnabled) _Bool requestHandlingEnabled;
- (long long)layoutMode;
- (void)loadView;
- (struct CGRect)rectForBulletin:(id)arg1;
- (void)removeViewController:(id)arg1;
@property(nonatomic) UIViewController<SBModeViewControllerContentProviding> *selectedViewController;
- (void)setSelectedViewController:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSArray *viewControllers;
- (void)setWidgetDelegate:(id)arg1;
- (void)settings:(id)arg1 changedValueForKeyPath:(id)arg2;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)sizeObservingView:(id)arg1 didChangeSize:(struct CGSize)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (id)widgetDelegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

