/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBIconImageView.h"

@interface SBNewsstandItemIconImageView : SBIconImageView
{
}

+ (int)_defaultIconFormat;
+ (double)cornerRadius;
- (id)_generateSquareContentsImage;
- (id)contentsImage;
- (id)darkeningOverlayImage;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)squareDarkeningOverlayImage;
- (struct CGRect)visibleBounds;

@end

