/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUserInstalledApplicationIcon.h"

@class SBNewsstandApplication;

@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon
{
    SBNewsstandApplication *_fakeApp;
}

- (id)application;
- (void)dealloc;
@property(retain, nonatomic) SBNewsstandApplication *fakeApp; // @synthesize fakeApp=_fakeApp;
- (id)getGenericIconImage:(int)arg1;
- (_Bool)iconAppearsInNewsstand;
- (int)iconFormatForLocation:(int)arg1;
- (id)initWithApplication:(id)arg1;
- (_Bool)isNewsstandApplicationIcon;
- (_Bool)launchEnabled;
- (void)launchFromLocation:(int)arg1;
- (_Bool)shouldWarmUp;

@end

