/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBFolder.h"

@interface SBNewsstandFolder : SBFolder
{
}

+ (_Bool)isNewsstandFolderClass;
- (_Bool)canAddIcon;
- (_Bool)canEditDisplayName;
- (_Bool)canRemoveIcons;
- (id)icon;
- (id)initWithMaxListCount:(unsigned long long)arg1 maxIconCountInLists:(unsigned long long)arg2;
- (_Bool)isNewsstandFolder;
- (Class)listModelClass;
- (id)nodeIdentifier;
- (void)setDisplayName:(id)arg1;
- (void)setIsOpen:(_Bool)arg1;
- (_Bool)shouldRemoveWhenEmpty;

@end

