/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBFolderController.h"

@interface SBNewsstandFolderController : SBFolderController
{
}

+ (Class)listViewClass;
- (Class)_contentViewClass;
- (unsigned long long)_depth;
- (id)_statusBarColor;
- (id)legibilitySettings;
- (struct UIEdgeInsets)statusBarInsetsForOrientation:(long long)arg1;

@end

