/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBGradientView.h"

@class SBHighlightView, UIColor, UIView;

@interface SBNewsstandShelfView : SBGradientView
{
    UIView *_tintView;
    double _tintAlpha;
    SBHighlightView *_highlightView;
    unsigned long long _shelfIndex;
}

- (void)dealloc;
- (void)layoutSubviews;
@property(nonatomic) unsigned long long shelfIndex; // @synthesize shelfIndex=_shelfIndex;
@property(nonatomic) double tintAlpha;
@property(retain, nonatomic) UIColor *tintColor;

@end

