/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "NSXPCListenerDelegate-Protocol.h"
#import "_NCWidgetController_Host_IPC-Protocol.h"

@class NSString, NSXPCListener;

@interface SBNotificationCenterWidgetController : NSObject <_NCWidgetController_Host_IPC, NSXPCListenerDelegate>
{
    NSXPCListener *_listener;
}

+ (id)_sharedInstanceCreateIfNecessary:(_Bool)arg1;
+ (id)containingBundleIdentifierForWidgetWithBundleIdentifer:(id)arg1;
+ (id)defaultWidgetController;
- (void)__setHasContent:(_Bool)arg1 forWidgetWithBundleIdentifier:(id)arg2;
- (void)dealloc;
- (id)init;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

