/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@interface SBNotificationSeparatorView : UIView
{
    double _height;
}

+ (long long)blendMode;
+ (id)color;
+ (id)separatorForCurrentState;
+ (long long)separatorViewModeForCurrentState;
+ (id)separatorWithScreenScale:(double)arg1 mode:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 mode:(long long)arg2;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateForCurrentState;

@end

