/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class SBControlColorSettings;

@interface SBNotificationControlColorSettings : NSObject
{
    SBControlColorSettings *_vibrantSettings;
    SBControlColorSettings *_overlaySettings;
}

+ (id)actionButtonSettingsWithGraphicsQuality:(long long)arg1;
+ (id)editButtonSettingsWithGraphicsQuality:(long long)arg1;
+ (id)settingsWithGraphicsQuality:(long long)arg1;
- (void)dealloc;
- (id)initWithVibrantSettings:(id)arg1 overlaySettings:(id)arg2;
@property(readonly, retain, nonatomic) SBControlColorSettings *overlaySettings; // @synthesize overlaySettings=_overlaySettings;
@property(readonly, retain, nonatomic) SBControlColorSettings *vibrantSettings; // @synthesize vibrantSettings=_vibrantSettings;

@end

