/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIButton.h"

@interface SBNotificationVibrantButton : UIButton
{
    UIButton *_vibrantButton;
    UIButton *_overlayButton;
}

- (id)_buttonFont;
- (id)_buttonImageForColor:(id)arg1 selected:(_Bool)arg2;
- (void)_buttonPushed:(id)arg1;
- (void)_buttonStateChanged:(id)arg1;
- (void)_configureButton:(id *)arg1 withSettings:(id)arg2;
- (void)_configureOverlayViewWithSettings:(id)arg1;
- (void)_configureVibrantViewWithSettings:(id)arg1;
- (id)_newButtonWithBackgroundImage:(id)arg1 selectedImage:(id)arg2 titleColor:(id)arg3 selectedTitleColor:(id)arg4;
- (void)dealloc;
- (id)initWithColorSettings:(id)arg1;
- (void)layoutSubviews;
- (void)setHighlighted:(_Bool)arg1;
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)titleLabel;
- (void)updateForContenteCategorySizeChange;

@end

