/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBBulletinWindowClient-Protocol.h"
#import "SBCoordinatedPresenting-Protocol.h"
#import "SBExtensionHandling-Protocol.h"
#import "SBNotificationCenterViewControllerDelegate-Protocol.h"
#import "SBReachabilityObserver-Protocol.h"
#import "SBWidgetViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class FBUIApplicationResignActiveAssertion, NCLaunchStats, NSSet, NSString, NSTimer, SBChevronView, SBLockScreenActionContext, SBNotificationCenterSettings, SBNotificationCenterViewController, SBWindow, UILongPressGestureRecognizer, UIView;

@interface SBNotificationCenterController : NSObject <SBBulletinWindowClient, SBNotificationCenterViewControllerDelegate, SBWidgetViewControllerDelegate, _UISettingsKeyObserver, UIGestureRecognizerDelegate, SBExtensionHandling, SBReachabilityObserver, SBCoordinatedPresenting>
{
    SBNotificationCenterViewController *_viewController;
    UIView *_coveredContentSnapshot;
    SBChevronView *_borrowedGrabberView;
    id _borrowedGrabberWillPresentBlock;
    id _borrowedGrabberHideBlock;
    id _borrowedGrabberCompletionBlock;
    UILongPressGestureRecognizer *_grabberPressGesture;
    id _keyboardNotificationObserverToken;
    SBLockScreenActionContext *_lockScreenActionContext;
    long long _transitionState;
    long long _presentedState;
    SBNotificationCenterSettings *_settings;
    _Bool _grabberEnabled;
    _Bool _didCoalesceWidgetsConnections;
    NSTimer *_widgetConnectionsTimer;
    FBUIApplicationResignActiveAssertion *_resignActiveAssertion;
    NCLaunchStats *_launchStats;
}

+ (id)_sharedInstanceCreateIfNecessary:(_Bool)arg1;
+ (id)newDynamicAnimationForShow:(_Bool)arg1 targetValue:(double)arg2 withInitialValue:(double)arg3 velocity:(double)arg4 extraPull:(_Bool)arg5;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
+ (double)transitionAnimationDuration;
- (void)_beginPresentationWithTouchLocation:(struct CGPoint)arg1 setupPrelude:(id)arg2 setupPostlude:(void)arg3 animationPrelude:(id)arg4;
- (void)_cleanupAfterTransition:(_Bool)arg1;
- (void)_didCoalesceWidgetsConnections:(id)arg1;
- (void)_endTransitionWithVelocity:(struct CGPoint)arg1 additionalValueApplier:(id)arg2 animationPostlude:(void)arg3 completion:(id)arg4;
- (void)_handleActionContextRequiringAuthentication:(id)arg1;
- (void)_handleActionContextRequiringUIUnlock:(id)arg1;
- (_Bool)_handleActionOrRequestWithDefaultAction:(id)arg1 lockedAction:(void)arg2;
- (void)_handleWidgetLaunchRecommendation:(id)arg1 completion:(id)arg2;
- (void)_insertCoveredContentSnapshotIfNecessary:(id)arg1;
- (void)_invalidateCoveredContentSnapshot;
- (_Bool)_isNotificationCenterViewAvailableWhileLockedWithProfileBlock:(id)arg1 counterpartBlock:(void)arg2;
- (_Bool)_isNotificationCenterViewWithFeatureKeyAvailableWhileLocked:(id)arg1 isLockedDownByRestrictions:(_Bool *)arg2;
- (void)_loadViewForWidget:(id)arg1 prelude:(id)arg2 completion:(void)arg3;
- (id)_lockScreenViewController;
- (void)_makeVisibleWidgetWithIdentifier:(id)arg1 completion:(id)arg2;
- (void)_present:(_Bool)arg1 stepper:(id)arg2;
- (void)_present:(_Bool)arg1 withStandardAnimation:(_Bool)arg2 stepper:(id)arg3 completion:(void)arg4 fromCurrentState:(id)arg5;
- (void)_presentAnimated:(_Bool)arg1 setupPrelude:(id)arg2 setupPostlude:(void)arg3 animationPrelude:(id)arg4 animationPostlude:(void)arg5 completion:(id)arg6;
- (void)_removeCoveredContentSnapshot;
- (_Bool)_requiresAuthenticationForActionContext:(id)arg1;
- (_Bool)_requiresUIUnlockForActionContext:(id)arg1;
- (void)_setGrabberEnabled:(_Bool)arg1;
- (void)_setViewUserInteractionEnabled:(_Bool)arg1;
- (void)_setupForDismissal;
- (void)_setupForPresentationWithTouchLocation:(struct CGPoint)arg1;
- (void)_setupForViewPresentation;
- (_Bool)_shouldSelectViewControllerAtTouchLocation;
- (void)_updateCoveredContentSnapshot;
- (void)_updateForChangeInMessagePrivacy;
- (void)abortAnimatedTransition;
- (void)beginDismissalWithTouchLocation:(struct CGPoint)arg1;
- (void)beginPresentationWithTouchLocation:(struct CGPoint)arg1;
- (void)biometricEventMonitorDidAuthenticate:(id)arg1;
@property(nonatomic) _Bool blursBackground;
- (void)bulletinWindowDidRotateFromOrientation:(long long)arg1;
- (void)bulletinWindowIsAnimatingRotationToOrientation:(long long)arg1 duration:(double)arg2;
- (void)bulletinWindowWillRotateToOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)canShowHideGrabberView;
- (void)cancelTransition;
@property(readonly, nonatomic) long long coordinatedPresentingControllerIdentifier;
- (void)dealloc;
- (void)dismissAnimated:(_Bool)arg1;
- (void)dismissAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)dismissAnimated:(_Bool)arg1 withStepper:(id)arg2 completion:(void)arg3 fromCurrentState:(id)arg4;
- (void)dismissPresentedWidgetContentAnimated:(_Bool)arg1;
- (_Bool)doesSectionWithIdentifierUpdateMessagePrivacyViaSectionParameters:(id)arg1;
- (void)enableAllWidgets:(id)arg1;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 additionalValueApplier:(id)arg2 completion:(void)arg3;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 completion:(id)arg2;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 wasCancelled:(_Bool)arg2 completion:(id)arg3;
- (void)finishedScrollTest;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)handleAction:(id)arg1 forBulletin:(id)arg2 withCompletion:(id)arg3;
- (void)handleGrabberPress:(id)arg1;
- (_Bool)handleMenuButtonTap;
- (void)handleReachabilityModeActivated;
- (void)handleReachabilityModeDeactivated;
- (void)hideGrabberAnimated:(_Bool)arg1 completion:(id)arg2;
@property(readonly, nonatomic) double hintDisplacement;
@property(readonly, nonatomic) unsigned long long hintEdge;
- (id)init;
- (void)invalidateLockScreenActionContext;
@property(readonly, nonatomic, getter=isAvailableWhileLocked) _Bool availableWhileLocked;
@property(nonatomic, getter=isGrabberEnabled) _Bool grabberEnabled; // @synthesize grabberEnabled=_grabberEnabled;
@property(readonly, nonatomic, getter=isGrabberVisible) _Bool grabberVisible;
@property(readonly, nonatomic, getter=isNotificationsViewAvailableWhileLocked) _Bool notificationsViewAvailableWhileLocked;
- (_Bool)isPresentingControllerTransitioning;
@property(readonly, nonatomic, getter=isPresentingWidgetContent) _Bool presentingWidgetContent;
@property(readonly, nonatomic, getter=isTodayViewAvailableWhileLocked) _Bool todayViewAvailableWhileLocked;
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
@property(readonly, nonatomic, getter=isVisible) _Bool visible;
- (void)launchExtensionWithBundleID:(id)arg1 options:(id)arg2 completion:(id)arg3;
@property(readonly, nonatomic) long long layoutMode;
@property(readonly, nonatomic) SBLockScreenActionContext *lockScreenActionContext; // @synthesize lockScreenActionContext=_lockScreenActionContext;
- (void)prepareLayoutForPresentationFromBanner;
- (void)presentAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)registerSharedGrabberView:(id)arg1 withWillPresentBlock:(id)arg2 hideBlock:(void)arg3 andCompletion:(id)arg4;
- (void)reloadAllWidgets;
- (void)remoteViewControllerDidConnectForWidget:(id)arg1;
- (void)runScrollTest:(id)arg1 iterations:(long long)arg2 delta:(long long)arg3 useAAGView:(_Bool)arg4;
- (void)runWidgetLaunchTestWithWidgetWithIdentifier:(id)arg1 prelude:(id)arg2 completion:(void)arg3;
@property(readonly, nonatomic) SBNotificationCenterSettings *settings; // @synthesize settings=_settings;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (_Bool)shouldRequestWidgetRemoteViewControllers;
- (void)showGrabberAnimated:(_Bool)arg1;
@property(readonly, nonatomic) struct UIEdgeInsets todayContentEdgeInsets;
@property(readonly, nonatomic) struct CGSize todayContentMaxSize;
- (void)unregisterSharedGrabberView;
- (void)updateTransitionWithTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
@property(readonly, retain, nonatomic) SBNotificationCenterViewController *viewController; // @synthesize viewController=_viewController;
- (void)widget:(id)arg1 requestsLaunchOfURL:(id)arg2;
- (void)widget:(id)arg1 requestsPresentationOfViewController:(id)arg2 presentationStyle:(long long)arg3 context:(id)arg4 completion:(id)arg5;
- (id)widgetViewControllerHostDelegate:(id)arg1;
@property(readonly, nonatomic) SBWindow *window;

// Remaining properties
@property(readonly, nonatomic) NSSet *conflictingGestures;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSSet *gestures;
@property(readonly) unsigned long long hash;
@property(nonatomic) id <SBPresentingDelegate> presentingDelegate;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSSet *tapExcludedViews;

@end

