/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBBBBulletinInfo.h"

@class SBItemInfoLayoutCache, SBNotificationCenterSectionInfo, UIColor, UIImage, UIViewController;

@interface SBNotificationsBulletinInfo : SBBBBulletinInfo
{
    SBNotificationCenterSectionInfo *_sectionInfo;
    SBItemInfoLayoutCache *_layoutCache;
    UIImage *_icon;
    UIImage *_attachmentImage;
    struct CGSize _attachmentImageSize;
    double _secondaryTextHeight;
    _Bool _suppressingMessageForPrivacy;
    _Bool _isCachedMessageSuppressionValid;
    UIViewController *_secondaryContentViewController;
    UIColor *_secondaryTextColor;
}

- (id)_attachmentImageToDisplay;
- (void)_configureEventDateLabel:(id)arg1;
- (void)_configureRelevanceDateLabel:(id)arg1;
- (struct CGSize)_effectiveAttachmentImageSize;
- (id)_endDate;
- (id)_eventDateLabel;
- (id)_eventDateLabelForDisplay;
- (id)_primaryText;
- (id)_primaryTextColor;
- (id)_relevanceDateLabel;
- (CDStruct_89ddc8e1)_relevanceDateLabelDescription;
- (id)_relevanceDateTextColor;
- (id)_secondaryContentView;
- (id)_secondaryText;
- (id)_secondaryTextColor;
- (id)_secondaryTextToDisplay;
- (id)_subtitleText;
- (id)_subtitleTextColor;
- (id)_subtitleTextToDisplay;
@property(retain, nonatomic) UIImage *attachmentImage; // @synthesize attachmentImage=_attachmentImage;
@property(nonatomic) struct CGSize attachmentImageSize; // @synthesize attachmentImageSize=_attachmentImageSize;
- (void)dealloc;
- (double)heightForReusableViewForBulletinViewController:(id)arg1 layoutMode:(long long)arg2 bulletinLocation:(long long)arg3;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (id)identifier;
- (void)invalidateCachedLayoutData;
@property(readonly, nonatomic, getter=isSuppressingMessageForPrivacy) _Bool suppressingMessageForPrivacy; // @synthesize suppressingMessageForPrivacy=_suppressingMessageForPrivacy;
- (void)populateReusableView:(id)arg1;
- (void)prepareWithCompletion:(id)arg1;
- (Class)reusableViewClass;
@property(readonly, nonatomic) UIViewController *secondaryContentViewController; // @synthesize secondaryContentViewController=_secondaryContentViewController;
@property(readonly, nonatomic) UIColor *secondaryTextColor; // @synthesize secondaryTextColor=_secondaryTextColor;
@property(retain, nonatomic) SBNotificationCenterSectionInfo *sectionInfo; // @synthesize sectionInfo=_sectionInfo;

@end

