/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "_SBFVibrantTableViewCell.h"

#import "SBDateLabelDelegate-Protocol.h"
#import "SBModalLayoutCaching-Protocol.h"

@class NSString, UIButton, UIColor, UIImage, UIImageView, UILabel, UILabel<SBBulletinDateLabel>, UIView, UIViewController;

@interface SBNotificationCell : _SBFVibrantTableViewCell <SBDateLabelDelegate, SBModalLayoutCaching>
{
    UIView *_realContentView;
    UIImageView *_iconImageView;
    UILabel *_primaryLabel;
    UILabel *_subtitleLabel;
    UILabel *_secondaryLabel;
    UILabel<SBBulletinDateLabel> *_relevanceDateLabel;
    UILabel<SBBulletinDateLabel> *_eventDateLabel;
    UIButton *_actionButton;
    UIImageView *_attachmentView;
    struct CGSize _attachmentSize;
    long long _layoutMode;
    UIViewController *_secondaryContentViewController;
    _Bool _secondaryTextNumberOfLinesIsUpperBound;
    unsigned long long _secondaryTextNumberOfLines;
    double _secondaryTextHeight;
    UIImage *_icon;
}

+ (double)actionButtonPaddingLeft;
+ (double)contentWidthWithRowWidth:(double)arg1 andAttachmentSize:(struct CGSize)arg2 forLayoutMode:(long long)arg3;
+ (id)defaultColorForEventDate;
+ (id)defaultColorForPrimaryText;
+ (id)defaultColorForRelevanceDate;
+ (id)defaultColorForSecondaryText;
+ (id)defaultColorForSubtitleText;
+ (id)defaultFontForEventDate;
+ (id)defaultFontForPrimaryText;
+ (id)defaultFontForRelevanceDate;
+ (id)defaultFontForSecondaryText;
+ (id)defaultFontForSubtitleText;
+ (double)firstLineBaselineOffsetFromTop;
+ (double)firstLineBaselineOffsetFromTopNoIcon;
+ (double)paddingBetweenTitleAndRelevanceDate;
+ (id)preferredFontForTextStyle:(id)arg1 symbolicTraits:(unsigned int)arg2;
+ (double)secondLineBaselineOffsetFromFirstLine;
+ (void)setupEventDateLabel:(id)arg1;
+ (void)setupRelevanceDateLabel:(id)arg1;
- (void)_setShouldHaveFullLengthBottomSeparator:(_Bool)arg1;
- (void)_setShouldHaveFullLengthTopSeparator:(_Bool)arg1;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(nonatomic) double attachmentAlpha;
@property(readonly, nonatomic) UIView *attachmentView; // @synthesize attachmentView=_attachmentView;
@property(readonly, nonatomic) struct CGRect contentBounds;
- (void)dateLabelDidChange:(id)arg1;
- (void)dealloc;
@property(nonatomic) double eventDateAlpha;
@property(retain, nonatomic) UIColor *eventDateColor;
@property(retain, nonatomic) UILabel<SBBulletinDateLabel> *eventDateLabel;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(nonatomic) double iconAlpha;
@property(readonly, nonatomic) UIView *iconView; // @synthesize iconView=_iconImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) long long layoutMode; // @synthesize layoutMode=_layoutMode;
- (void)layoutSubviews;
@property(readonly, nonatomic) UILabel *primaryLabel; // @synthesize primaryLabel=_primaryLabel;
@property(copy, nonatomic) NSString *primaryText;
@property(nonatomic) double primaryTextAlpha;
@property(retain, nonatomic) UIColor *primaryTextColor;
@property(readonly, nonatomic) UIView *realContentView; // @synthesize realContentView=_realContentView;
@property(nonatomic) double relevanceDateAlpha;
@property(retain, nonatomic) UIColor *relevanceDateColor;
@property(retain, nonatomic) UILabel<SBBulletinDateLabel> *relevanceDateLabel;
@property(retain, nonatomic) UIViewController *secondaryContentViewController; // @synthesize secondaryContentViewController=_secondaryContentViewController;
@property(readonly, nonatomic) UILabel *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
@property(copy, nonatomic) NSString *secondaryText;
@property(nonatomic) double secondaryTextAlpha;
@property(retain, nonatomic) UIColor *secondaryTextColor;
@property(nonatomic) double secondaryTextHeight; // @synthesize secondaryTextHeight=_secondaryTextHeight;
@property(readonly, nonatomic) unsigned long long secondaryTextNumberOfLines; // @synthesize secondaryTextNumberOfLines=_secondaryTextNumberOfLines;
@property(readonly, nonatomic) _Bool secondaryTextNumberOfLinesIsUpperBound; // @synthesize secondaryTextNumberOfLinesIsUpperBound=_secondaryTextNumberOfLinesIsUpperBound;
- (void)setAttachmentImage:(id)arg1;
- (void)setSecondaryTextNumberOfLines:(unsigned long long)arg1 treatAsUpperBound:(_Bool)arg2;
@property(copy, nonatomic) NSString *subtitleText;
@property(nonatomic) double subtitleTextAlpha;
@property(retain, nonatomic) UIColor *subtitleTextColor;
@property(readonly, nonatomic) _Bool shouldVerticallyCenterContent;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

