/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableSet;

@interface SBOrientationLockManager : NSObject
{
    NSMutableSet *_lockOverrideReasons;
    long long _userLockedOrientation;
}

+ (id)sharedInstance;
- (_Bool)_effectivelyLocked;
- (void)_updateLockStateWithChanges:(id)arg1;
- (void)_updateLockStateWithOrientation:(long long)arg1 forceUpdateHID:(_Bool)arg2 changes:(id)arg3;
- (void)dealloc;
- (void)enableLockOverrideForReason:(id)arg1 forceOrientation:(long long)arg2;
- (void)enableLockOverrideForReason:(id)arg1 suggestOrientation:(long long)arg2;
- (id)init;
- (_Bool)isLocked;
- (void)lock;
- (void)lock:(long long)arg1;
- (_Bool)lockOverrideEnabled;
- (void)restoreStateFromPrefs;
- (void)setLockOverrideEnabled:(_Bool)arg1 forReason:(id)arg2;
- (void)unlock;
- (void)updateLockOverrideForCurrentDeviceOrientation;
- (long long)userLockOrientation;

@end

