/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSDate, NSString, SBPasscodeAlertItem, SBPasscodeComplianceAlertItem;

@interface SBPasscodeController : NSObject
{
    SBPasscodeAlertItem *_passcodeAlertItem;
    int _mode;
    NSString *_previousPasscode;
    NSString *_newPasscode;
    int _unlockScreenType;
    SBPasscodeComplianceAlertItem *_complianceAlertItem;
    NSDate *_forcedComplianceDate;
    id _telephonyNotificationObserver;
    int _restoreCompletedAlertStateChangedToken;
    _Bool _delayedComplianceAlertUntilAfterRestoreCompletedAlert;
}

+ (id)sharedInstance;
- (void)_abort;
- (void)_activateComplianceAlert;
- (void)_didEndCall;
- (_Bool)_isRestoreCompletedAlertActive;
- (void)_passwordEntered:(id)arg1;
- (void)_startListeningToRestoreCompletedAlertStateChangedNotifications;
- (void)_startListeningToTelephonyNotifications;
- (void)_stopListeningToRestoreCompletedAlertStateChangedNotifications;
- (void)_stopListeningToTelephonyNotifications;
- (void)_userWantsToComplyNow:(_Bool)arg1;
- (void)checkPasscodeCompliance;
- (void)dealloc;
- (void)forceUserToChangePasscode;
- (id)init;

@end

