/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SBPluginManager : NSObject
{
    NSString *_pluginsDirectory;
    NSMutableDictionary *_plugins;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (void)loadAllLaunchPlugins;
- (Class)loadPluginBundle:(id)arg1;
- (Class)loadPluginNamed:(id)arg1;
- (id)springBoardPluginsDirectory;

@end

