/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBIcon.h"

@interface SBPlaceholderIcon : SBIcon
{
    id _nodeIdentifier;
    SBIcon *_icon;
}

+ (id)emptyPlaceholder;
+ (id)grabbedIconPlaceholder;
+ (id)placeholderForIcon:(id)arg1;
+ (id)placeholderNodeIdentifierForIcon:(id)arg1;
+ (void)setGrabbedIcon:(id)arg1;
- (id)_initWithNodeIdentifier:(id)arg1 icon:(id)arg2;
- (id)automationID;
- (void)dealloc;
- (id)generateIconImage:(int)arg1;
- (_Bool)isEmptyPlaceholder;
- (_Bool)isGrabbedIconPlaceholder;
- (_Bool)isPlaceholder;
- (id)nodeIdentifier;
- (id)referencedIcon;
- (_Bool)shouldCacheImageForFormat:(int)arg1;

@end

