/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertView.h"

#import "SBPowerDownViewInterface-Protocol.h"
#import "_UIActionSliderDelegate-Protocol.h"

@class NSString, NSTimer, SBShapeView, UIButton, UILabel, UIView, _UIActionSlider;

@interface SBPowerDownView : SBAlertView <_UIActionSliderDelegate, SBPowerDownViewInterface>
{
    NSTimer *_autoDismissTimer;
    id <SBPowerDownViewDelegate> _delegate;
    UIView *_backdropView;
    SBShapeView *_darkeningUnderlayView;
    UIView *_darkeningOverlayView;
    _UIActionSlider *_actionSlider;
    UIButton *_cancelButton;
    UILabel *_cancelLabel;
    _Bool _hiddenLockScreenForeground;
    _Bool _canAlterScreenBrightness;
}

- (void)_animatePowerDown;
- (void)_cancelAutoDismissTimer;
- (id)_lockScreenView;
- (void)_notifyDelegateCancelled;
- (void)_notifyDelegatePowerDown;
- (void)_resetAutoDismissTimer;
- (void)_resetScreenBrightness;
- (void)_saveScreenBrightnessInformation;
- (void)_updateSliderExclusionPath;
- (void)actionSlider:(id)arg1 didUpdateSlideWithValue:(double)arg2;
- (void)actionSliderDidBeginSlide:(id)arg1;
- (void)actionSliderDidCancelSlide:(id)arg1;
- (void)actionSliderDidCompleteSlide:(id)arg1;
- (void)animateIn;
- (void)animateOut;
@property(nonatomic) _Bool canAlterScreenBrightness; // @synthesize canAlterScreenBrightness=_canAlterScreenBrightness;
- (void)dealloc;
@property(nonatomic) id <SBPowerDownViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismiss;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutForInterfaceOrientation:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

