/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@interface SBPolygon : NSObject
{
    int m_pointCount;
    struct CGPoint m_points[5];
    unsigned long long m_pathIDs[5];
    double m_weights[5];
    struct CGPoint m_centroid;
    struct CGPoint m_weightedCentroid;
    unsigned long long m_baseLeftVertex;
    unsigned long long m_bottomRightVertex;
}

+ (_Bool)candidate:(id)arg1 matchesTemplate:(id)arg2 transforms:(int)arg3 acceptFactor:(double)arg4;
- (void)addPoint:(struct CGPoint)arg1;
- (void)addPoint:(struct CGPoint)arg1 pathIndex:(unsigned long long)arg2;
- (double)baseOrientation;
- (void)beginPointUpdate;
- (struct CGPoint)calculateCentroid;
- (struct CGPoint)calculateWeightedCentroid;
@property(nonatomic) struct CGPoint centroid; // @synthesize centroid=m_centroid;
- (void)clear;
- (void)commonInit;
- (void)endPointUpdate;
- (double)findLongestOutsideEdge;
- (void)flipHorizontally;
- (double)height;
@property(readonly, nonatomic) _Bool isLeftHanded;
- (void)makeLike:(id)arg1;
- (double)meanFingertipRowAngle;
- (double)meanRadius;
@property(readonly, nonatomic) int pointCount; // @synthesize pointCount=m_pointCount;
- (void)rotate:(double)arg1;
- (void)scale:(double)arg1;
@property(nonatomic) struct CGPoint weightedCentroid; // @synthesize weightedCentroid=m_weightedCentroid;
- (void)sortAlongOutsideEdge;
- (unsigned long long)thumbIndex;
- (double)weightAtIndex:(int)arg1;
- (double)width;

@end

