/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBVolumePressBandit-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSArray, NSString, PTSettingsController, SBRootSettings, UIWindow;

@interface SBPrototypeController : NSObject <SBVolumePressBandit, _UISettingsKeyObserver>
{
    SBRootSettings *_rootSettings;
    UIWindow *_settingsWindow;
    PTSettingsController *_settingsController;
    NSArray *_testRecipeClassNames;
    id <SBTestRecipe> _activeTestRecipe;
    _Bool _showingSettings;
    _Bool _hasPreviousSettings;
}

+ (void)migrateSettings;
+ (void)reloadDefaults;
+ (id)sharedInstance;
- (void)_changeActiveTestRecipeIfNecessary;
- (void)_configureForDefaults;
- (_Bool)_hasPreviousSettings;
- (void)_hideSettings;
- (struct CGRect)_offscreenFrame;
- (_Bool)_restorePreviousSettings;
- (void)_showSettings;
- (void)_tearDownSettingsWindow;
- (id)_testRecipeClassNames;
- (void)_updatePreventingLockover;
@property(retain, nonatomic) id <SBTestRecipe> activeTestRecipe;
- (void)dealloc;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (id)init;
- (_Bool)isPrototypingEnabled;
- (_Bool)isShowingSettingsUI;
- (id)rootSettings;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)showOrHide;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

