/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@class NSString, SBApplication;

@interface SBProxyRemoteView : UIView
{
    id _delegate;
    SBApplication *_app;
    NSString *_remoteViewIdentifier;
    _Bool _remoteViewOpaque;
    NSString *_hostRequester;
}

+ (Class)layerClass;
- (void)_setIsConnected:(_Bool)arg1;
- (void)connectToContextID:(unsigned int)arg1 forIdentifier:(id)arg2 application:(id)arg3;
- (void)dealloc;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void)didMoveToSuperview;
- (void)disconnect;
- (id)init;
- (void)noteConnectionLost;
@property(retain, nonatomic) NSString *remoteViewIdentifier; // @synthesize remoteViewIdentifier=_remoteViewIdentifier;
@property(nonatomic) _Bool remoteViewOpaque; // @synthesize remoteViewOpaque=_remoteViewOpaque;

@end

