/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerObserver-Protocol.h"

@class NSString, SBDisableActiveInterfaceOrientationChangeAssertion, SBStarkScreenController, SBUIAnimationController;

@interface SBRelaunchAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerObserver>
{
    SBUIAnimationController *_animationController;
    _Bool _relaunchSuspended;
    _Bool _willBeOccluded;
    SBDisableActiveInterfaceOrientationChangeAssertion *_disableActiveOrientationChangeAssertion;
    SBStarkScreenController *_starkScreenController;
}

- (id)_animationForApp:(id)arg1;
- (void)_begin;
- (void)_didComplete;
- (void)_endAnimation;
- (void)_handleAppRelaunch:(id)arg1;
- (id)_setupAnimationForApp:(id)arg1;
- (void)animationController:(id)arg1 willBeginAnimation:(_Bool)arg2;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
- (id)initWithAlertManager:(id)arg1 application:(id)arg2;
@property(retain, nonatomic) SBStarkScreenController *starkScreenController; // @synthesize starkScreenController=_starkScreenController;
- (_Bool)shouldToggleSpringBoardStatusBarOnCleanup;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

