/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSData, NSDate, NSString;

@interface SBRemoteNotificationClient : NSObject <NSCoding>
{
    NSString *_bundleIdentifier;
    NSString *_environment;
    NSData *_lastKnownDeviceToken;
    NSDate *_missingDate;
    _Bool _backgroundDeliveryDisabled;
    long long _dayOfLastNewsstandPush;
    unsigned long long _dailyCountOfNewsstandPushes;
    _Bool _backgroundAppRefreshAllowed;
    _Bool _wantsPush;
    NSString *_pushDisabledReason;
}

- (_Bool)allowsUserNotifications;
- (id)application;
- (_Bool)backgroundAppRefreshAllowedForBundleIdentifier:(id)arg1;
@property(nonatomic) _Bool backgroundDeliveryDisabled; // @synthesize backgroundDeliveryDisabled=_backgroundDeliveryDisabled;
@property(readonly, retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(nonatomic) unsigned long long dailyCountOfNewsstandPushes; // @synthesize dailyCountOfNewsstandPushes=_dailyCountOfNewsstandPushes;
@property(nonatomic) long long dayOfLastNewsstandPush; // @synthesize dayOfLastNewsstandPush=_dayOfLastNewsstandPush;
- (void)dealloc;
@property(nonatomic, getter=doesWantPush) _Bool wantsPush; // @synthesize wantsPush=_wantsPush;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *environment; // @synthesize environment=_environment;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, getter=isBackgroundAppRefreshAllowed) _Bool backgroundAppRefreshAllowed; // @synthesize backgroundAppRefreshAllowed=_backgroundAppRefreshAllowed;
@property(readonly, nonatomic, getter=isNewsstandApplication) _Bool newsstandApplication;
- (_Bool)isNewsstandPushEnabled;
@property(readonly, nonatomic, getter=isPushEnabled) _Bool pushEnabled;
@property(retain, nonatomic) NSData *lastKnownDeviceToken; // @synthesize lastKnownDeviceToken=_lastKnownDeviceToken;
@property(retain, nonatomic) NSDate *missingDate; // @synthesize missingDate=_missingDate;
@property(retain, nonatomic) NSString *pushDisabledReason; // @synthesize pushDisabledReason=_pushDisabledReason;
@property(readonly, nonatomic) _Bool supportsBackgroundAppRefresh;
- (_Bool)wantsPushWithCoder:(id)arg1;

@end

