/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBReachabilityTrigger.h"

@class NSTimer;

@interface SBReachabilityHoldTrigger : SBReachabilityTrigger
{
    NSTimer *_fingerOnMesaTimer;
}

- (void)_clearFingerOnMesaTimer;
- (void)_fingerOnMesaTimerFired:(id)arg1;
- (void)_setFingerOnMesaTimer;
- (void)biometricEventMonitor:(id)arg1 handleBiometricEvent:(unsigned long long)arg2;
- (void)clearPendingReachabilityTrigger;
- (void)dealloc;

@end

