/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertAdapter.h"

#import "_SBRemoteAlertHostViewControllerDelegate-Protocol.h"

@class NSMutableSet, NSString, _SBRemoteAlertHostViewController;

@interface SBRemoteAlertAdapter : SBAlertAdapter <_SBRemoteAlertHostViewControllerDelegate>
{
    _SBRemoteAlertHostViewController *_remoteAlertHostViewController;
    NSString *_impersonatedApplicationBundleID;
    _Bool _activated;
    _Bool _dismissWithHomeButton;
    _Bool _userRequestedHomeButtonDismissal;
    long long _desiredButtonEvents;
    _Bool _wantsWallpaperTunnel;
    _Bool _hasTranslucentBackground;
    long long _requestedBackgroundStyle;
    _Bool _allowsAlertStacking;
    long long _dismissalAnimationStyle;
    _Bool _disableFadeInAnimation;
    NSMutableSet *_idleTimerDisabledReasons;
    double _requestedAutoLockTime;
    _Bool _hasCustomStatusBarStyle;
    long long _customStatusBarStyle;
    int _desiredStatusBarStyleOverrides;
    _Bool _wantsToShowStatusBar;
    _Bool _suppressesSiri;
    _Bool _dismissOnUILock;
    long long _desiredLaunchingInterfaceOrientation;
    _Bool _dontCancelStatusBarStyleOverrides;
    id _lockUIAndDismissActions;
    id _clientActivationHandler;
    id _clientDeactivationHandler;
    _Bool _beingPresentedObscured;
}

+ (void)requestRemoteViewService:(id)arg1 options:(id)arg2 completion:(id)arg3;
- (void)_cleanupIdleTimerDisabledReasons;
- (id)_impersonatesApplicationWithBundleID;
- (id)_initWithRemoteAlertHostViewController:(id)arg1;
- (void)_setCustomStatusBarStyle:(long long)arg1;
- (void)_setDismissWithHomeButton:(_Bool)arg1;
- (void)_setDismissalAnimationStyle:(long long)arg1;
- (void)_setHasTranslucentBackground:(_Bool)arg1;
- (void)_setImpersonatedApplicationBundleID:(id)arg1;
- (void)_setLaunchingInterfaceOrientation:(long long)arg1;
- (void)_setShouldDisableFadeInAnimation:(_Bool)arg1;
- (void)_setSuppressesSiri:(_Bool)arg1;
- (void)_setWantsWallpaperTunnel:(_Bool)arg1 immediately:(_Bool)arg2;
- (void)activate;
- (_Bool)allowsStackingOfAlert:(id)arg1;
- (double)autoLockTime;
- (void)deactivate;
- (void)dealloc;
@property(readonly, nonatomic) _Bool disablesFadeInAnimation; // @synthesize disablesFadeInAnimation=_disableFadeInAnimation;
@property(readonly, nonatomic) _Bool dismissOnUILock; // @synthesize dismissOnUILock=_dismissOnUILock;
@property(readonly, nonatomic) long long dismissalAnimationStyle; // @synthesize dismissalAnimationStyle=_dismissalAnimationStyle;
- (void)handleDoubleHeightStatusBarTap;
- (_Bool)handleHeadsetButtonPressed:(_Bool)arg1;
- (_Bool)handleLockButtonPressed;
- (_Bool)handleMenuButtonTap;
- (_Bool)handleVolumeDownButtonPressed;
- (_Bool)handleVolumeUpButtonPressed;
- (_Bool)hasTranslucentBackground;
- (id)initWithViewController:(id)arg1;
- (long long)interfaceOrientationForActivation;
@property(nonatomic, getter=isBeingPresentedObscured) _Bool beingPresentedObscured; // @synthesize beingPresentedObscured=_beingPresentedObscured;
- (_Bool)isRemote;
- (_Bool)matchesAnyInCallService;
- (_Bool)matchesInCallUIService;
- (_Bool)matchesRemoteAlertService:(id)arg1 options:(id)arg2;
- (void)noteActivatedForCustomReason:(id)arg1;
- (void)noteShouldStopDisablingStatusBarOverrides;
- (void)remoteAlertDidTerminateWithError:(id)arg1;
- (void)remoteAlertWantsMenuButtonDismissal:(_Bool)arg1;
- (void)remoteAlertWantsToAllowAlertStacking:(_Bool)arg1;
- (void)remoteAlertWantsToAllowBanners:(_Bool)arg1;
- (void)remoteAlertWantsToDisableFadeInAnimation:(_Bool)arg1;
- (void)remoteAlertWantsToDismissOnUILock:(_Bool)arg1;
- (void)remoteAlertWantsToLockUIAndDismiss;
- (void)remoteAlertWantsToSetAutoLockDuration:(double)arg1;
- (void)remoteAlertWantsToSetBackgroundStyle:(long long)arg1 withDuration:(double)arg2;
- (void)remoteAlertWantsToSetDesiredStatusBarStyleOverrides:(int)arg1;
- (void)remoteAlertWantsToSetIdleTimerDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)remoteAlertWantsToSetStatusBarHidden:(_Bool)arg1 withDuration:(double)arg2;
- (void)remoteAlertWantsToUpdateAllowedHardwareButtonEvents:(long long)arg1;
- (void)remoteAlertWantsWallpaperTunnelActive:(_Bool)arg1;
- (void)remoteAlertWantstoSetDismissalAnimationStyle:(long long)arg1;
- (void)remoteAlertWantstoSetSupportedInterfaceOrientationOverride:(unsigned long long)arg1;
@property(nonatomic) long long requestedBackgroundStyle; // @synthesize requestedBackgroundStyle=_requestedBackgroundStyle;
@property(readonly, nonatomic) NSString *serviceBundleIdentifier;
- (void)setActivationHandler:(id)arg1 deactivationHandler:(void)arg2;
- (void)setLockUIAndDismissActions:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)showsSpringBoardStatusBar;
- (long long)statusBarStyle;
- (int)statusBarStyleOverridesToCancel;
- (_Bool)suppressesControlCenter;
- (_Bool)suppressesNotificationCenter;
- (_Bool)suppressesSiri;
@property(readonly, nonatomic) _Bool userRequestedHomeButtonDismissal; // @synthesize userRequestedHomeButtonDismissal=_userRequestedHomeButtonDismissal;
@property(readonly, nonatomic) _Bool wantsWallpaperTunnel; // @synthesize wantsWallpaperTunnel=_wantsWallpaperTunnel;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

