/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertItem.h"

@class SBApplication;

@interface SBRemoteNotificationNeedIdentityAlert : SBAlertItem
{
    SBApplication *_app;
}

- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)dealloc;
- (_Bool)dismissOnLock;
- (_Bool)dismissOnModalDisplayActivation;
- (id)initWithApplication:(id)arg1;

@end

