/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBReachabilityTriggerDelegate-Protocol.h"

@class NSMutableSet, NSString, NSTimer, SBReachabilityTrigger;

@interface SBReachabilityManager : NSObject <SBReachabilityTriggerDelegate>
{
    NSMutableSet *_observers;
    _Bool _keepAliveForEndedInteraction;
    _Bool _reachabilityModeActive;
    _Bool _reachabilityModeEnabled;
    NSTimer *_keepAliveTimer;
    NSMutableSet *_temporaryDisabledReasons;
    SBReachabilityTrigger *_trigger;
}

+ (_Bool)reachabilitySupported;
+ (id)sharedInstance;
- (void)_clearKeepAliveTimer;
- (void)_handleReachabilityActivated;
- (void)_handleReachabilityDeactivated;
- (void)_handleSignificantTimeChanged;
- (void)_keepAliveTimerFired:(id)arg1;
- (void)_notifyObserversReachabilityModeActive:(_Bool)arg1 excludingObserver:(id)arg2;
- (void)_setKeepAliveTimerForDuration:(double)arg1;
- (void)_toggleReachabilityModeWithRequestingObserver:(id)arg1;
- (void)_updateReachabilityModeActive:(_Bool)arg1 withRequestingObserver:(id)arg2;
- (void)addObserver:(id)arg1;
- (void)cancelPendingReachabilityRequests;
- (void)deactivateReachabilityModeForObserver:(id)arg1;
- (void)dealloc;
- (void)disableExpirationTimerForInteraction;
- (void)enableExpirationTimerForEndedInteraction;
- (id)init;
@property(nonatomic) _Bool reachabilityEnabled;
@property(readonly, nonatomic) _Bool reachabilityModeActive; // @synthesize reachabilityModeActive=_reachabilityModeActive;
- (void)removeObserver:(id)arg1;
- (void)setReachabilityTemporarilyDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)triggerDidTriggerReachability:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

