/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBFolderController.h"

@class SBRootFolder, SBRootFolderView, UIWindow;

@interface SBRootFolderController : SBFolderController
{
    _Bool _managesStatusBarWidth;
    UIWindow *_dockAnimationWindow;
}

+ (Class)listViewClass;
- (struct CGRect)_autoscrollExclusionRegion;
- (void)_configureAppStatusBarInsets;
- (void)_configureAppStatusBarInsetsAnimated:(_Bool)arg1;
- (void)_configureAppStatusBarInsetsForOrientation:(long long)arg1;
- (void)_configureDockViewForOrientationDuringAnimation:(long long)arg1;
- (void)_configureDockViewForOrientationWithoutAnimation:(long long)arg1;
- (Class)_contentViewClass;
- (unsigned long long)_depth;
- (unsigned long long)_dockEdgeForInterfaceOrientation:(long long)arg1;
- (_Bool)_dockLayoutReversedForInterfaceOrientation:(long long)arg1;
- (_Bool)_isDockSwitchedForOrientation:(long long)arg1;
- (_Bool)_listIndexIsVisible:(unsigned long long)arg1;
- (_Bool)_shouldSlideDockOutDuringRotationFromOrientation:(long long)arg1 toOrientation:(long long)arg2;
- (void)addAdditionalInnerFolderAnimations;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
@property(retain, nonatomic) UIWindow *dockAnimationWindow; // @synthesize dockAnimationWindow=_dockAnimationWindow;
@property(nonatomic) unsigned long long dockEdge;
- (id)dockListView;
- (id)folderControllers;
- (id)initWithFolder:(id)arg1 orientation:(long long)arg2 viewMap:(id)arg3;
- (_Bool)isDisplayingIcon:(id)arg1;
@property(nonatomic) _Bool managesStatusBarWidth; // @synthesize managesStatusBarWidth=_managesStatusBarWidth;
- (_Bool)popFolderAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)prepareToClose;
- (void)prepareToOpen;
- (_Bool)pushFolder:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (_Bool)setCurrentPageIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)setDockOffscreenFraction:(double)arg1;
- (void)setDockVerticalStretch:(double)arg1;
- (void)setIdleText:(id)arg1;
- (struct UIEdgeInsets)statusBarInsetsForOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, retain, nonatomic) SBRootFolderView *contentView;
@property(retain, nonatomic) SBRootFolder *folder;

@end

