/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableArray, UIScreen, UIView, UIWindow;

@interface SBScreenFlash : NSObject
{
    NSMutableArray *_flashCompletionBlocks;
    UIScreen *_screen;
    UIWindow *_flashWindow;
    UIView *_flashView;
    _Bool _windowVisible;
}

+ (id)mainScreenFlasher;
- (void)_animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_createUIWithColor:(id)arg1;
- (void)_orderWindowFront:(id)arg1 withColor:(id)arg2;
- (void)_orderWindowOut:(id)arg1;
- (void)_tearDown;
- (void)dealloc;
- (void)flashColor:(id)arg1 withCompletion:(id)arg2;
- (void)flashWhiteWithCompletion:(id)arg1;
- (id)initWithScreen:(id)arg1;

@end

