/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class SBAppSwitcherPeopleContactItem;

@interface SBScrollViewItemWrapper : NSObject <NSCopying>
{
    unsigned long long _section;
    SBAppSwitcherPeopleContactItem *_item;
    unsigned long long _itemIndex;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (unsigned long long)hash;
- (id)initWithSection:(unsigned long long)arg1 itemIndex:(unsigned long long)arg2 item:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) SBAppSwitcherPeopleContactItem *item; // @synthesize item=_item;
@property(readonly, nonatomic) unsigned long long itemIndex; // @synthesize itemIndex=_itemIndex;
@property(readonly, nonatomic) unsigned long long section; // @synthesize section=_section;

@end

