/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBSearchResultsViewControllerAction.h"

#import "SBSearchResultDetailsViewControllerDelegate-Protocol.h"

@class NSLayoutConstraint, NSString;

@interface SBSearchResultsDetailsViewControllerAction : SBSearchResultsViewControllerAction <SBSearchResultDetailsViewControllerDelegate>
{
    NSLayoutConstraint *_leftMargin;
    NSLayoutConstraint *_rightMargin;
    NSLayoutConstraint *_topMargin;
}

+ (Class)viewControllerClass;
- (void)cancel:(id)arg1;
- (void)cancelAnimated:(_Bool)arg1 withCompletionBlock:(id)arg2;
- (void)dealloc;
- (id)performWithCompletionBlock:(id)arg1;
- (void)searchResultDetailsViewController:(id)arg1 openURLs:(id)arg2;
- (void)updateConstraintConstants;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

