/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@class NSDictionary, NSString, SBObservingLabel;

@interface SBSearchTableHeaderView : UIView
{
    NSString *_reuseIdentifier;
    SBObservingLabel *_titleLabel;
    UIView *_separatorView;
    NSDictionary *_titleTextAttributes;
}

+ (id)lineColor;
+ (_Bool)requiresConstraintBasedLayout;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;
- (_Bool)isUserInteractionEnabled;
- (void)prepareForReuse;
@property(readonly, copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) NSString *title;
@property(retain, nonatomic) SBObservingLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSDictionary *titleTextAttributes; // @synthesize titleTextAttributes=_titleTextAttributes;
- (void)updateFonts;

@end

