/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBSearchResultsAction.h"

@class UIViewController;

@interface SBSearchResultsViewControllerAction : SBSearchResultsAction
{
    id _completionBlock;
    UIViewController *_viewController;
}

@property(copy, nonatomic) id completionBlock; // @synthesize completionBlock=_completionBlock;
- (void)dealloc;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(id)arg2;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;

@end

