/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@class UIColor;

@protocol SBSearchResultDetailsViewController <NSObject>
+ (id)viewControllerForResult:(id)arg1 inSection:(id)arg2;
@property id <SBSearchResultDetailsViewControllerDelegate> actionDelegate;
- (void)loadWithCompletionBlock:(id)arg1;
@property(readonly) _Bool wantsInset;

@optional
@property(retain) UIColor *contentBackgroundColor;
@end

