/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol SBSearchResultsActionManagerDelegate <NSObject>
- (void)actionManager:(id)arg1 dismissAnimated:(_Bool)arg2 completionBlock:(id)arg3;
- (void)actionManager:(id)arg1 dismissViewController:(id)arg2 completion:(id)arg3 animated:(void)arg4;
- (void)actionManager:(id)arg1 presentViewController:(id)arg2 completion:(id)arg3 modally:(void)arg4;
- (struct UIEdgeInsets)actionManagerDetailsViewEdgeInsets:(id)arg1;
@end

