/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBSearchResultsModalViewControllerAction.h"

@class MKMapItem;

@interface SBSearchResultsMapsAction : SBSearchResultsModalViewControllerAction
{
    MKMapItem *_mapItem;
}

- (id)buttonActionTitle;
- (void)dealloc;
- (void)loadModalViewControllerWithCompletionBlock:(id)arg1;
@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
- (void)performButtonAction;

@end

