/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBSearchParsecSimpleCell.h"

@class UIImageView;

@interface SBSearchParsecSimpleChevronCell : SBSearchParsecSimpleCell
{
    UIImageView *_chevronView;
}

+ (_Bool)supportsSection:(id)arg1 result:(id)arg2;
@property(retain, nonatomic) UIImageView *chevronView; // @synthesize chevronView=_chevronView;
- (id)constantConstraints;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)rightViewFrom:(id)arg1;

@end

