/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@interface SBShapeView : UIView
{
}

+ (Class)layerClass;
- (id)_shapeLayer;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)setFillColor:(id)arg1;
- (void)setFillRule:(long long)arg1;
- (void)setPath:(id)arg1;

@end

