/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSString, SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : NSObject
{
    _Bool _isBrickedDevice;
    long long _status;
    SBSIMLockAlertItem *_currentAlert;
    SBSIMLockEntryAlert *_lockEntryAlert;
    NSString *_languageCode;
    _Bool _hasHadSIMWhileNotBricked;
    _Bool _wasActivated;
    _Bool _neededUIM;
}

+ (id)sharedInstance;
- (long long)_CTToSBSIMStatus:(struct __CFString *)arg1;
- (void)_activationDidChange;
- (void)_externalSIMStatusChanged:(id)arg1;
- (void)_handlePromptForUnlock;
- (void)_postponementDidChange;
- (void)_setupAppActivationStateDidChange:(id)arg1;
- (_Bool)_shouldSuppressAlert;
- (long long)_statusFromCT;
- (void)_tearDownAlertAndUpdateStatus;
- (void)_telephonyDidRestart;
- (void)_tryToUpdateStatus;
- (void)_updateSIMStatus:(struct __CFString *)arg1 withOptions:(struct __CFDictionary *)arg2;
- (void)_updateToStatus:(long long)arg1;
- (void)airplaneModeChanged;
- (void)alertItemDismissed:(id)arg1;
- (void)attemptUnlock;
- (void)dealloc;
- (id)init;
- (id)languageCode;
- (void)lockEntryAlertDismissed:(id)arg1;
- (int)pinLockAttemptsRemaining;
- (int)pukLockAttemptsRemaining;
- (void)registerForAlerts;
- (void)repopAlert;
- (long long)status;

@end

