/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIGestureRecognizer.h"

#import "_UISettingsKeyObserver-Protocol.h"

@class NSString, SBSlideToUnlockTriangleView, UIView;

@interface SBSlideToUnlockFailureRecognizer : UIGestureRecognizer <_UISettingsKeyObserver>
{
    struct CGPoint _startingLocation;
    unsigned long long _maxAllowableVerticalOffset;
    double _maxAllowedTopAngle;
    double _minAllowedTopAngle;
    double _effectiveTopAngle;
    double _minAllowedBottomAngle;
    double _maxAllowedBottomAngle;
    double _effectiveBottomAngle;
    _Bool _tracking;
    _Bool _allowMultiTouch;
    _Bool _viewDebugArea;
    UIView *_relativeView;
    UIView *_debugHorizontalView;
    SBSlideToUnlockTriangleView *_debugInclineUpView;
    SBSlideToUnlockTriangleView *_debugInclineDownView;
}

- (long long)_activeTouchCountForEvent:(id)arg1;
- (struct CGPoint)_averagePointFromTouches:(id)arg1;
- (double)_computeEffectiveAngleFromMin:(double)arg1 max:(double)arg2;
- (double)_effectiveBottomAngle;
- (double)_effectiveTopAngle;
- (_Bool)_isLocationOutOfBounds:(struct CGPoint)arg1;
- (_Bool)_isOutOfBounds:(struct CGPoint)arg1 forAngle:(double)arg2;
- (_Bool)_isOutOfBoundsVertically:(struct CGPoint)arg1;
- (void)_loadFromSettings:(id)arg1;
- (void)_setDebugViewsVisible:(_Bool)arg1;
@property(nonatomic) _Bool allowMultiTouch; // @synthesize allowMultiTouch=_allowMultiTouch;
- (_Bool)canBePreventedByGestureRecognizer:(id)arg1;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic) unsigned long long maxAllowableVerticalOffset; // @synthesize maxAllowableVerticalOffset=_maxAllowableVerticalOffset;
@property(nonatomic) double maxAllowedBottomAngle; // @synthesize maxAllowedBottomAngle=_maxAllowedBottomAngle;
@property(nonatomic) double maxAllowedTopAngle; // @synthesize maxAllowedTopAngle=_maxAllowedTopAngle;
@property(nonatomic) double minAllowedBottomAngle; // @synthesize minAllowedBottomAngle=_minAllowedBottomAngle;
@property(nonatomic) double minAllowedTopAngle; // @synthesize minAllowedTopAngle=_minAllowedTopAngle;
@property(retain, nonatomic) UIView *relativeView; // @synthesize relativeView=_relativeView;
- (void)reset;
@property(nonatomic) _Bool viewDebugArea; // @synthesize viewDebugArea=_viewDebugArea;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

