/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UILabel.h"

#import "SBBulletinDateLabel-Protocol.h"

@class NSString, NSTimer;

@interface SBSnoozedAlarmDateLabel : UILabel <SBBulletinDateLabel>
{
    double _fireTime;
    NSTimer *_tickTimer;
    _Bool _allDay;
    _Bool isTimestamp;
    int _labelType;
    id <SBDateLabelDelegate> _delegate;
}

- (id)_formatDuration:(double)arg1;
- (void)_invalidateTimer;
- (void)_tickTimerFired:(id)arg1;
- (void)_updateText;
- (void)dealloc;
@property(nonatomic) id <SBDateLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isAllDay) _Bool allDay; // @synthesize allDay=_allDay;
@property(nonatomic) _Bool isTimestamp; // @synthesize isTimestamp;
@property(nonatomic) int labelType; // @synthesize labelType=_labelType;
- (void)prepareForReuse;
- (void)setEndDate:(id)arg1 withTimeZone:(id)arg2;
- (void)setStartDate:(id)arg1 withTimeZone:(id)arg2;
- (void)startCoalescingUpdates;
- (void)stopCoalescingUpdates;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

