/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@class SBSoftwareUpdateVerifyingUpdateAlertViewController;

@interface SBSoftwareUpdateVerifyingUpdateAlertItem : SBBaseSoftwareUpdateAlertItem
{
    SBSoftwareUpdateVerifyingUpdateAlertViewController *_activityViewController;
}

- (_Bool)allowMenuButtonDismissal;
- (_Bool)behavesSuperModally;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)dealloc;
- (_Bool)dismissOnLock;
- (_Bool)dismissesAutomatically;
- (id)initWithDescriptor:(id)arg1;
- (_Bool)reappearsAfterLock;
- (_Bool)reappearsAfterUnlock;
- (_Bool)shouldShowInLockScreen;
- (_Bool)undimsScreen;

@end

