/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SUManagerClientDelegate-Protocol.h"
#import "SUNetworkObserver-Protocol.h"

@class NSString, SUDownload, SUManagerClient;

@interface SBSoftwareUpdateController : NSObject <SUManagerClientDelegate, SUNetworkObserver>
{
    SUManagerClient *_client;
    SUDownload *_updateToInstall;
    int _currentNetworkType;
    int _iCloudRestoreToken;
    _Bool _showOrScheduleForcedInstallAlertAfterNextUnlock;
    _Bool _scheduleForcedInstallAlertAfterNextUnlock;
    _Bool _scheduleForcedInstallAlertWhenAble;
    _Bool _settingsResetPrefsBadgedFlag;
    _Bool _downloadWasQueuedRemotely;
}

+ (id)sharedInstance;
+ (id)stringFromReasons:(long long)arg1;
- (void)_autoDownloadUnknownToUserFailedForDescriptor:(id)arg1 error:(id)arg2;
- (void)_callCountChanged:(id)arg1;
- (void)_clearLegacyBadgeIfNecessary:(id)arg1;
- (void)_completeMigrationForSettingsReset;
- (_Bool)_forceInstallAfterDownload;
- (void)_handleInstallError:(id)arg1;
- (void)_iCloudStatusChanged;
- (void)_iTunesRestoreStateChanged:(id)arg1;
- (_Bool)_isSettingsActive;
- (_Bool)_isSettingsBadgedForSoftwareUpdate;
- (void)_isUpdateInstallable:(id)arg1;
- (void)_lockStateChanged:(id)arg1;
- (void)_migrateForNewOSVersionIfNecessary;
- (void)_passcodeLockStateChanged:(id)arg1;
- (void)_postDownloadStateChangeNotification:(_Bool)arg1;
- (void)_prepareMigrationForSettingsReset;
- (void)_registerForInstallRelatedNotifications;
- (void)_resetAndCancelExistingScheduledForcedInstallAlerts;
- (void)_resetState;
- (void)_saveLastKnownVersionPreference:(id)arg1;
- (void)_savePreferencesBadgeFlag:(id)arg1;
- (void)_scheduleForcedInstallRepeatAlert:(double)arg1;
- (void)_setUpdateToInstall:(id)arg1;
- (void)_showForcedInstallAlertRequiringInstallationKeybag:(_Bool)arg1;
- (void)_showOrScheduleNextForcedInstallAlert;
- (void)_showOrScheduleNextForcedInstallAlertWithReasons:(long long)arg1;
- (void)_showSUAvailableAlertForDescriptor:(id)arg1;
- (id)_stringForCurrentVersionPreference;
- (void)_syncDidEnd:(id)arg1;
- (void)_syncWillStart:(id)arg1;
- (void)_toggleSettingsBadge:(_Bool)arg1;
- (void)_unregisterForInstallRelatedNotifications;
- (void)client:(id)arg1 automaticDownloadDidFailToStartForNewUpdateAvailable:(id)arg2 withError:(id)arg3;
- (void)client:(id)arg1 downloadDidFail:(id)arg2 withError:(id)arg3;
- (void)client:(id)arg1 downloadDidFinish:(id)arg2;
- (void)client:(id)arg1 downloadDidStart:(id)arg2;
- (void)client:(id)arg1 downloadProgressDidChange:(id)arg2;
- (void)client:(id)arg1 downloadWasInvalidatedForNewUpdateAvailable:(id)arg2;
- (void)client:(id)arg1 installDidFail:(id)arg2 withError:(id)arg3;
- (void)client:(id)arg1 installDidFinish:(id)arg2;
- (void)client:(id)arg1 installDidStart:(id)arg2;
- (void)dealloc;
- (void)delayForcedInstallUntilAble;
- (void)delayForcedInstallWithDefaultDurationAfterNextUnlock;
- (void)delayForcedInstallWithDefaultDurationFromNow;
- (id)init;
- (void)installUpdate;
- (void)isDownloading:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

