/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBStarkAppToAppWorkspaceTransaction.h"

@interface SBStarkAppExitedWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction
{
}

- (void)_begin;
- (id)_setupAnimationFrom:(id)arg1 to:(id)arg2;
- (void)_setupMilestonesFrom:(id)arg1 to:(id)arg2;
- (id)initWithMainScreenAlertManager:(id)arg1 starkScreenController:(id)arg2 exitedApp:(id)arg3;

@end

