/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "_UIRemoteViewController.h"

#import "SBSUICarDisplayNowPlayingHostInterface-Protocol.h"
#import "SBSUICarDisplayNowPlayingInterface-Protocol.h"

@interface SBStarkNowPlayingService : _UIRemoteViewController <SBSUICarDisplayNowPlayingHostInterface, SBSUICarDisplayNowPlayingInterface>
{
    id <SBStarkNowPlayingServiceDelegate> _delegate;
}

+ (id)exportedInterface;
+ (id)serviceViewControllerInterface;
@property(nonatomic) id <SBStarkNowPlayingServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)switchToState:(id)arg1;
- (void)viewServiceDidTerminateWithError:(id)arg1;

@end

