/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBStarkToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerObserver-Protocol.h"

@class NSString, SBApplication, SBUIAnimationController;

@interface SBStarkAppToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerObserver>
{
    SBApplication *_fromApp;
    SBUIAnimationController *_animationController;
    _Bool _animatedActivation;
    _Bool _animatedDeactivation;
}

- (id)_animation;
- (void)_begin;
- (void)_beginAnimation;
- (_Bool)_canBeInterrupted;
- (id)_defaultAnimationFactory;
- (void)_didComplete;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_doCommit;
- (void)_endAnimation;
- (void)_fixupSettingsAndCommit;
- (void)_handleAppDidNotChange;
- (id)_newAnimationFromAppToApp;
- (id)_newAnimationFromAppToLauncher;
- (id)_newAnimationFromAppToNowPlaying;
- (id)_newAnimationFromLauncherToApp;
- (id)_newAnimationFromLauncherToNowPlaying;
- (id)_newAnimationFromNowPlayingToApp;
- (id)_newAnimationFromNowPlayingToLauncher;
- (id)_newAnimationFromNowPlayingToNowPlaying;
- (void)_noteWillActivateApplicationOnMainScreen:(id)arg1 underLock:(_Bool)arg2;
- (id)_setupAnimationFrom:(id)arg1 to:(id)arg2;
- (void)_setupMilestonesFrom:(id)arg1 to:(id)arg2;
- (void)animationController:(id)arg1 willBeginAnimation:(_Bool)arg2;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) SBApplication *fromApp; // @synthesize fromApp=_fromApp;
- (id)initWithMainScreenAlertManager:(id)arg1 starkScreenController:(id)arg2 from:(id)arg3 to:(id)arg4;
- (void)mainScreenApplicationSceneWillCommit:(id)arg1;
- (void)mainScreenApplicationUpdateScenesTransactionCompleted:(id)arg1;
- (id)swizzledToDisplayIfNecessary;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

