/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBStarkBannerItem.h"

@class NSDate, NSString, SBAlertItem, SBUISound;

@interface SBStarkAlertItemBannerItem : SBStarkBannerItem
{
    SBAlertItem *_alertItem;
    NSString *_title;
    NSString *_message;
    SBUISound *_sound;
    NSDate *_originDate;
}

- (id)action;
- (id)category;
- (id)categoryImage;
- (void)dealloc;
- (long long)defaultActionType;
- (id)ignoreAction;
- (id)initWithAlertItem:(id)arg1;
- (_Bool)isSticky;
- (_Bool)matchesContext:(id)arg1;
- (unsigned long long)priority;
- (void)reloadDisplayProperties;
- (id)sound;
- (id)sourceDate;
- (id)subActionLabels;
- (id)subActions;
- (id)title;

@end

