/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMutableArray, NSString, UIScreen;

@interface SBStarkScreenFocusController : NSObject
{
    UIScreen *_screen;
    NSMutableArray *_assertions;
    NSString *_displayID;
}

- (void)_applyAssertion:(id)arg1;
- (void)_updateEventFocus;
- (void)dealloc;
- (id)description;
- (void)dropReason:(id)arg1;
- (id)focusWindow;
- (id)initWithScreen:(id)arg1;
- (void)invalidate;
- (void)takeWithPriority:(double)arg1 reason:(id)arg2 forWindow:(id)arg3 bundleIdentifier:(id)arg4 pid:(int)arg5;

@end

