/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBUIBannerSource-Protocol.h"
#import "SBUIBannerTargetManagerObserver-Protocol.h"

@class NSMutableArray, NSString;

@interface SBStarkBannerSource : NSObject <SBUIBannerSource, SBUIBannerTargetManagerObserver>
{
    id _allowedTargetIdentifier;
    id <SBUIBannerTarget> _target;
    NSMutableArray *_enqueuedItems;
}

- (void)bannerTargetManager:(id)arg1 didAddTarget:(id)arg2;
- (void)bannerTargetManager:(id)arg1 didRemoveTarget:(id)arg2;
- (id)currentItemFromTarget;
- (void)dealloc;
- (id)dequeueNextBannerItemForTarget:(id)arg1;
- (void)dismissCurrentItemFromTarget;
- (void)enqueueItem:(id)arg1;
- (unsigned long long)enumerateAllItemsMatchingContext:(id)arg1 withBlock:(id)arg2;
- (id)indexesOfEnqueuedItemsMatchingContext:(id)arg1;
- (id)init;
- (id)initWithAllowedTargetIdentifier:(void *)arg1;
- (id)newBannerViewForContext:(id)arg1;
- (id)peekNextBannerItemForTarget:(id)arg1;
- (void)removeEnqueuedItemsAtIndexes:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

