/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class CAMutableMeshTransform, UIView;

@interface SBStretchTransformer : NSObject
{
    UIView *m_view;
    int m_anchorEdge;
    long long m_orientation;
    CAMutableMeshTransform *m_mesh;
    double m_stretchFactor;
    id m_animationCompletionHandler;
}

@property(nonatomic) int anchorEdge; // @synthesize anchorEdge=m_anchorEdge;
- (void)animateToZeroStretchFactor;
- (void)animateToZeroStretchFactorWithCompletionHandler:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)dealloc;
- (id)initWithView:(id)arg1 anchorEdge:(int)arg2 orientation:(long long)arg3;
- (id)meshTransform;
@property(nonatomic) long long orientation; // @synthesize orientation=m_orientation;
@property(nonatomic) double stretchFactor; // @synthesize stretchFactor=m_stretchFactor;
@property(retain, nonatomic) UIView *view; // @synthesize view=m_view;
- (void)updateMeshTransform:(id)arg1 stretchFactor:(double)arg2;

@end

