/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@interface SBStarkIconLayoutOverrideStrategy : NSObject
{
    struct UIEdgeInsets _layoutInsets;
    _Bool _preservesCurrentListOrigin;
}

- (id)initWithFullscreenOverrideStrategy:(id)arg1;
@property(readonly, nonatomic) struct UIEdgeInsets layoutInsets; // @synthesize layoutInsets=_layoutInsets;
@property(readonly, nonatomic) _Bool preservesCurrentListOrigin; // @synthesize preservesCurrentListOrigin=_preservesCurrentListOrigin;

@end

