/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBStatusBarStateAggregatorPosting-Protocol.h"
#import "UIStatusBarStateProvider-Protocol.h"

@class NSHashTable, NSString, SBStatusBarStateAggregator;

@interface SBStatusBarStateProvider : NSObject <SBStatusBarStateAggregatorPosting, UIStatusBarStateProvider>
{
    SBStatusBarStateAggregator *_stateAggregator;
    NSHashTable *_stateObservers;
    CDStruct_0e61b686 _aggregatorData;
    int _aggregatorActions;
    CDStruct_0e61b686 _lastPost;
    unsigned long long _coalescentBlockDepth;
    _Bool _itemNeedsPost[25];
    _Bool _anyItemNeedsPost;
    _Bool _nonItemDataNeedsPost;
    _Bool _posting;
    NSHashTable *_stylesWithDetailUpdates;
}

- (void)_composePostActionsFromAggregatorActions:(int *)arg1;
- (void)_composePostDataFromAggregatorData:(CDStruct_0e61b686 *)arg1;
- (void)_didChangeDoubleHeightStatusStringForStyle:(long long)arg1;
- (_Bool)_shouldPostForUpdatesToNonItemData:(const CDStruct_0e61b686 *)arg1;
- (_Bool)_shouldPostForVisitedItem:(int)arg1 withUpdates:(_Bool)arg2 toAggregatorData:(const CDStruct_0e61b686 *)arg3;
- (void)addStatusBarStateObserver:(id)arg1;
- (void)beginCoalescentBlock;
- (void)dealloc;
- (void)endCoalescentBlock;
- (void)getStatusBarData:(CDStruct_0e61b686 *)arg1;
- (id)init;
- (void)removeStatusBarStateObserver:(id)arg1;
- (void)statusBarStateAggregator:(id)arg1 didUpdateNonItemData:(const CDStruct_0e61b686 *)arg2;
- (void)statusBarStateAggregator:(id)arg1 didVisitItem:(int)arg2 withUpdates:(_Bool)arg3 toData:(const CDStruct_0e61b686 *)arg4;
- (void)statusBarStateAggregatorDidFinishPost:(id)arg1 withData:(const CDStruct_0e61b686 *)arg2 actions:(int)arg3;
- (void)statusBarStateAggregatorDidStartPost:(id)arg1;
- (void)updateStatusBarItem:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

