/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

#import "SBDateLabelDelegate-Protocol.h"
#import "SBStarkBannerItemObserver-Protocol.h"
#import "SBUIBannerView-Protocol.h"

@class NSString, SBStarkBannerItem, SBStarkBannerViewButton, SBUIBannerContext, UIImageView, UILabel, UILabel<SBBulletinDateLabel>;

@interface SBStarkBannerView : UIView <SBStarkBannerItemObserver, SBDateLabelDelegate, SBUIBannerView>
{
    SBUIBannerContext *_context;
    SBStarkBannerItem *_bannerItem;
    UIImageView *_categoryImageView;
    UILabel *_titleLabel;
    double _titleAscender;
    UILabel *_subTitleLabel;
    double _subTitleAscender;
    SBStarkBannerViewButton *_okButton;
    SBStarkBannerViewButton *_actionButton;
    struct UIEdgeInsets _contentInsets;
    UILabel<SBBulletinDateLabel> *_relevanceDateLabel;
    unsigned long long _interactionAffordances;
}

- (struct UIEdgeInsets)_categoryImageInsets;
- (struct UIEdgeInsets)_contentInsetsForActionType:(long long)arg1;
- (id)_defaultRelevanceDateFont;
- (_Bool)_hasKnob;
- (_Bool)_hasSubtitle;
- (void)_layoutForButton:(id)arg1 contentFrame:(struct CGRect)arg2;
- (void)_selectControl;
- (void)_setRelevanceDate:(id)arg1;
- (_Bool)_shouldShowOKButton;
- (id)_titleFont;
- (id)bannerContext;
- (_Bool)canBecomeFirstResponder;
- (void)dateLabelDidChange:(id)arg1;
- (void)dealloc;
- (void)didMoveToWindow;
- (id)initWithContext:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (_Bool)shouldBorrowScreen;
- (void)starkBannerItemDidReloadDisplayProperties:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

