/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UICollectionViewLayout.h"

@class NSArray, UICollectionViewLayoutAttributes;

@interface SBStarkNotificationLayout : UICollectionViewLayout
{
    UICollectionViewLayoutAttributes *_notificationAttributes;
    UICollectionViewLayoutAttributes *_previousNotificationAttributes;
    NSArray *_subActionsAttributes;
    NSArray *_previousSubActionsAttributes;
    UICollectionViewLayoutAttributes *_backgroundAttributes;
    UICollectionViewLayoutAttributes *_previousBackgroundAttributes;
    double _notificationHeight;
    double _transitionSpacing;
    struct UIEdgeInsets _subActionsInsets;
    double _subActionPadding;
    double _subActionHeight;
}

- (id)_indexPathsToDeleteForDecorationViewOfKind:(id)arg1;
- (id)_indexPathsToInsertForDecorationViewOfKind:(id)arg1;
- (id)_transitionAttributesForAction:(long long)arg1 withLayoutAttributes:(id)arg2;
- (struct CGSize)collectionViewContentSize;
- (void)dealloc;
- (id)finalLayoutAttributesForDisappearingDecorationElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (void)finalizeCollectionViewUpdates;
- (id)init;
- (id)initialLayoutAttributesForAppearingDecorationElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
@property(nonatomic) double notificationHeight; // @synthesize notificationHeight=_notificationHeight;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (void)prepareLayout;
@property(nonatomic) double subActionHeight; // @synthesize subActionHeight=_subActionHeight;
@property(nonatomic) double subActionPadding; // @synthesize subActionPadding=_subActionPadding;
@property(nonatomic) struct UIEdgeInsets subActionsInsets; // @synthesize subActionsInsets=_subActionsInsets;
@property(nonatomic) double transitionSpacing; // @synthesize transitionSpacing=_transitionSpacing;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;

@end

