/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBFileLogger.h"

@interface SBStatusBarishLogger : SBFileLogger
{
    _Bool _useCustomDestinations;
    unsigned long long _customDestinations;
}

- (void)_setEnabled:(_Bool)arg1;
- (_Bool)isEnabled;
- (unsigned long long)logDestinations;
- (id)logPreferenceName;
- (id)logPrefixForCategory:(id)arg1 destination:(unsigned long long)arg2;
- (id)name;
- (void)reloadFromDefaults;
- (_Bool)shouldEnableOnInternalBuilds;

@end

