/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertItem.h"

@interface SBThermalWarningAlertItem : SBAlertItem
{
    id <SBThermalWarningAlertItemDelegate> _delegate;
    int _actionTaken;
}

- (void)_autoCoolDown;
- (void)_playPresentationSound;
- (void)_tryToSendAction:(int)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)didDeactivateForReason:(int)arg1;
- (id)initWithDelegate:(id)arg1;
@property(readonly, nonatomic, getter=isWaitingForResponse) _Bool waitingForResponse;
- (_Bool)undimsScreen;
- (_Bool)unlocksScreen;
- (void)willActivate;

@end

