/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class CALayer, UIColor, UIImage;

@interface SBTintedImageProvider : NSObject
{
    UIImage *_tintedImage;
    CALayer *_tintedLayer;
    _Bool _wantsTintedLayer;
    UIImage *_originalImage;
    UIColor *_tintColor;
}

- (void)_createOrUpdateTintedImageOrLayer;
- (void)dealloc;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(nonatomic) _Bool wantsTintedLayer; // @synthesize wantsTintedLayer=_wantsTintedLayer;
@property(readonly, nonatomic) UIImage *tintedImage;
@property(readonly, nonatomic) CALayer *tintedLayer;

@end

