/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBToAppsWorkspaceTransaction.h"

@class SBApplication;

@interface SBToAppWorkspaceTransaction : SBToAppsWorkspaceTransaction
{
    SBApplication *_toApp;
}

- (void)dealloc;
- (id)initWithAlertManager:(id)arg1 toApplication:(id)arg2 withResult:(id)arg3;

@end

