/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBWorkspaceTransaction.h"

#import "FBApplicationUpdateScenesTransactionObserver-Protocol.h"
#import "FBSynchronizedTransactionDelegate-Protocol.h"

@class FBUIApplicationResignActiveAssertion, NSArray, NSMutableArray, NSMutableDictionary, NSSet, NSString, SBDisplayLayout, SBSceneBackgroundedStatusAssertion;

@interface SBToAppsWorkspaceTransaction : SBWorkspaceTransaction <FBApplicationUpdateScenesTransactionObserver, FBSynchronizedTransactionDelegate>
{
    NSArray *_toApplications;
    NSSet *_scenesToBackground;
    NSSet *_fromApplicationScenes;
    SBDisplayLayout *_toDisplayLayout;
    _Bool _fromAssistant;
    _Bool _fromSwitcher;
    _Bool _toSpringBoard;
    _Bool _underLockScreenInForeground;
    id _resultBlock;
    SBSceneBackgroundedStatusAssertion *_scenesBackgroundedStatusAssertion;
    NSMutableDictionary *_sceneIDsToApps;
    FBUIApplicationResignActiveAssertion *_resignActiveAssertion;
    NSMutableArray *_appsActivatingForeground;
    NSSet *_trackedProcesses;
}

- (id)_applicationForScene:(id)arg1;
- (void)_begin;
- (void)_beginAnimation;
- (void)_captureApplicationData;
- (void)_childTransactionDidComplete:(id)arg1;
- (id)_customizedDescriptionProperties;
- (void)_didComplete;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_fireAndClearResultBlockIfNecessaryForFailure:(_Bool)arg1;
- (void)_handleApplicationDidNotChange:(id)arg1;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)arg1;
- (void)_relinquishResignActiveAssertion;
- (id)_scenesToBackground;
- (void)_setupAnimation;
- (void)_synchronizeSceneUpdatesNowForScenes:(id)arg1;
- (void)_synchronizeWithSceneUpdates;
- (void)_willBegin;
- (void)activateApplications;
- (void)dealloc;
- (void)enumerateForegroundToApplicationsWithBlock:(id)arg1;
- (void)enumerateToApplicationsWithBlock:(id)arg1;
- (id)initWithAlertManager:(id)arg1 activationRequest:(id)arg2 withResult:(id)arg3;
- (_Bool)isGoingToLauncher;
- (void)performToAppStateCleanup;
- (_Bool)shouldAnimateOrientationChangeOnCompletion;
- (_Bool)shouldDismissSwitcher;
- (_Bool)shouldHideSpringBoardStatusBarOnCleanup;
- (_Bool)shouldPerformToAppStateCleanupOnCompletion;
- (_Bool)shouldPlaceOutgoingScenesUnderLockOnCompletion;
- (_Bool)shouldRestoreSpringBoardContentOnCleanup;
- (_Bool)shouldToggleSpringBoardStatusBarOnCleanup;
- (_Bool)shouldWatchdog:(id *)arg1;
- (void)synchronizedTransaction:(id)arg1 didCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransaction:(id)arg1 willCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransactionReadyToCommit:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *toApplications; // @synthesize toApplications=_toApplications;
- (void)toggleStatusBarForCleanup;
@property(readonly, retain, nonatomic) NSSet *trackedProcesses; // @synthesize trackedProcesses=_trackedProcesses;
- (void)transaction:(id)arg1 didCommitSceneUpdate:(id)arg2;
- (void)transaction:(id)arg1 willCommitSceneUpdate:(id)arg2;
- (double)watchdogTimeout;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

