/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlertAdapter.h"

@interface SBUIFullscreenAlertAdapter : SBAlertAdapter
{
    _Bool _animatingDeactivation;
    _Bool _animatingActivation;
}

+ (id)_adapterForController:(id)arg1;
+ (void)activateAlertForController:(id)arg1 animated:(_Bool)arg2 animateCurrentDisplayOut:(_Bool)arg3 withDelay:(_Bool)arg4 isSlidingDisplay:(_Bool)arg5;
+ (void)alertAdapterDisplayDidDisappear:(id)arg1;
+ (void)deactivateAlertForController:(id)arg1 animated:(_Bool)arg2 animateOldDisplayInWithStyle:(int)arg3 isSlidingDisplay:(_Bool)arg4;
- (void)_pluginViewAnimatedOut:(id)arg1;
- (void)_pluginViewDidAnimatedIn:(id)arg1;
- (_Bool)_shouldDismissSwitcherOnActivation;
- (void)_updateForTransparentDismiss:(id)arg1;
- (void)activate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (_Bool)allowsEventOnlySuspension;
- (_Bool)allowsStackingOfAlert:(id)arg1;
- (void)animateViewIn;
- (void)animateViewOut;
- (_Bool)currentlyAnimatingDeactivation;
- (void)deactivate;
- (void)dealloc;
- (id)display;
- (void)displayDidDisappear;
- (id)effectiveViewController;
- (void)handleAutoLock;
- (_Bool)handleHeadsetButtonPressed:(_Bool)arg1;
- (_Bool)handleLockButtonPressed;
- (_Bool)handleMenuButtonTap;
- (_Bool)handleVolumeDownButtonPressed;
- (_Bool)handleVolumeUpButtonPressed;
- (_Bool)hasTranslucentBackground;
- (id)initWithAlertController:(id)arg1;
- (_Bool)isCurrentlyAnimatingActivation;
- (void)prepareViewToAnimateIn;
- (void)prepareViewToAnimateOut;
- (void)setDisplay:(id)arg1;
- (void)setFlag:(long long)arg1 forStateSetting:(unsigned int)arg2;
- (void)setViewShouldAnimateIn:(_Bool)arg1;
- (_Bool)viewIsReadyToBeRemoved;
- (void)viewWillAppear:(_Bool)arg1;

@end

