/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBAlertManager, SBLockScreenViewController;

@interface SBUIAnimationFadeAlertToLockscreen : SBUIMainScreenAnimationController
{
    SBLockScreenViewController *_lockScreenViewController;
    SBAlert *_deactivatingAlert;
    SBAlertManager *_alertManager;
}

- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)_startAnimation;
- (double)animationDelay;
- (double)animationDuration;
- (void)dealloc;
- (id)initWithLockScreenController:(id)arg1 deactivatingAlert:(id)arg2 alertManager:(id)arg3;

@end

