/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIAnimationControllerObserver-Protocol.h"

@protocol SBUIAnimationControllerGroupObserver <SBUIAnimationControllerObserver>

@optional
- (void)animationControllerGroup:(id)arg1 childController:(id)arg2 willBeginAnimation:(_Bool)arg3;
- (void)animationControllerGroup:(id)arg1 childControllerDidFinishAnimation:(id)arg2;
@end

