/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlertManager, SBUIFullscreenAlertAdapter;

@interface SBUIAnimationFadeHomeToPluginAlert : SBUIMainScreenAnimationController
{
    SBAlertManager *_alertManager;
    SBUIFullscreenAlertAdapter *_alert;
    _Bool _alertIsTransparent;
    _Bool _alertViewIsAnimatingItself;
    _Bool _finishedPrimaryFadeAnimation;
}

- (void)_alertViewFinishedAnimatingItself;
- (void)_animationFinished;
- (void)_cleanupAnimation;
- (void)_evaluateTotalAnimationCompletion;
- (void)_fadeAnimationFinished;
- (void)_prepareAnimation;
- (void)_startAnimation;
- (double)animationDuration;
- (void)dealloc;
- (id)initWithAlertManager:(id)arg1 alert:(id)arg2;

@end

