/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIMainScreenAnimationController.h"

@class SBLockScreenViewControllerBase, UIView, UIView<FBWindowContextAppearance>;

@interface SBUIAnimationPhoneToLockScreenBase : SBUIMainScreenAnimationController
{
    SBLockScreenViewControllerBase *_lockScreenViewController;
    UIView<FBWindowContextAppearance> *_contextHostView;
    _Bool _needsScreenDim;
}

- (void)_cleanupAnimation;
@property(retain, nonatomic, getter=_contextHostView, setter=_setContextHostView:) UIView *contextHostView; // @synthesize contextHostView=_contextHostView;
- (id)_getTransitionWindow;
- (id)_lockScreenViewController;
- (void)_noteAnimationDidFinish;
- (void)_prepareAnimation;
- (void)_setHidden:(_Bool)arg1;
- (_Bool)_shouldHideContextHostViewStatusBar;
- (void)dealloc;
- (id)initWithLockScreenController:(id)arg1 deactivatingApp:(id)arg2;

@end

