/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIAnimationController.h"

#import "SBUIAnimationControllerObserver-Protocol.h"

@class NSArray, NSMutableArray, NSString;

@interface SBUIAnimationControllerGroup : SBUIAnimationController <SBUIAnimationControllerObserver>
{
    NSMutableArray *_animations;
    _Bool _finished;
}

- (void)_forEachAnimation:(id)arg1;
- (void)_startAnimation;
- (_Bool)_willAnimate;
- (void)addAnimation:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)animationController:(id)arg1 willBeginAnimation:(_Bool)arg2;
- (void)animationControllerDidFinishAnimation:(id)arg1;
@property(readonly, nonatomic) NSArray *animations; // @synthesize animations=_animations;
- (void)beginAnimation;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (void)endAnimation;
- (id)init;
- (id)initWithAnimations:(id)arg1;
- (void)removeObserver:(id)arg1;
- (_Bool)waitingToStart;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

