/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIMainScreenAnimationController.h"

@class NSArray, SBAlertManager, SBRemoteAlertAdapter, UIView;

@interface SBUIAnimationFadeAppToRemoteAlert : SBUIMainScreenAnimationController
{
    SBRemoteAlertAdapter *_alert;
    SBAlertManager *_alertManager;
    UIView *_appContextHostView;
    UIView *_alertContextHostView;
    NSArray *_accessoryHostViews;
}

- (void)_animationFinished;
- (void)_cleanupAnimation;
- (id)_getTransitionWindow;
- (void)_prepareAnimation;
- (void)_setHidden:(_Bool)arg1;
- (void)_startAnimation;
- (double)animationDuration;
- (void)dealloc;
- (id)initWithAlert:(id)arg1 deactivatingApp:(id)arg2 alertManager:(id)arg3;

@end

