/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIAnimationZoomUpApp.h"

@interface SBUIAnimationZoomUpAppFromPhone : SBUIAnimationZoomUpApp
{
}

- (void)_cleanupAnimation;
- (void)_cleanupPhonesContextHostView;
- (void)_prepareAnimation;
- (void)animateZoomWithCompletion:(id)arg1;
- (id)appStatusBarTransitionInfoWithStartStyleRequest:(id)arg1 startOrientation:(long long)arg2;
- (void)dealloc;
- (void)prepareZoom;

@end

