/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

@protocol SBUIRemoteAlertServiceInterface

@optional
- (void)handleDoubleHeightStatusBarTap;
- (void)handleHeadsetButtonPressed:(_Bool)arg1;
- (void)handleHomeButtonPressed;
- (void)handleLockButtonPressed;
- (void)handleVolumeDownButtonPressed;
- (void)handleVolumeUpButtonPressed;
- (void)noteActivatedForCustomReason:(id)arg1;
- (void)setUserInfo:(id)arg1;
@end

