/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBUIStarkStartupAnimation.h"

@class FBWindowContextHostManager, UIStatusBar, UIView;

@interface SBUIStarkStartupToAppAnimation : SBUIStarkStartupAnimation
{
    FBWindowContextHostManager *_contextHostManager;
    UIView *_viewToAnimate;
    UIStatusBar *_fakeStatusBar;
    _Bool _finished;
}

- (id)_animationProgressDependency;
- (void)_applicationDependencyStateChanged;
- (void)_cancelAnimation;
- (void)_cleanupAnimation;
- (id)_createViewToAnimate;
- (void)_finishedAnimation:(_Bool)arg1;
- (void)_prepareAnimation;
- (void)_reallyPrepareAnimation;
- (void)_setupStartDependencies;
- (void)_startAnimation;
- (void)dealloc;

@end

