/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBAlert.h"

@interface SBVoiceControlAlert : SBAlert
{
    struct {
        unsigned int shouldBeActivated:1;
        unsigned int isReadyToBeActivated:1;
        unsigned int hasBeenActivated:1;
    } _voiceControlFlags;
    _Bool _expectsFaceContact;
    _Bool _expectsFaceContactInLandscape;
}

+ (_Bool)_bluetoothDevicesPickable;
+ (void)_configureSession:(id)arg1 forAlert:(id)arg2;
+ (void)_setNextRecognitionAudioInputPathForSession:(id)arg1 resetting:(_Bool)arg2;
+ (void)bluetoothDeviceRequestedVoiceControl:(id)arg1;
+ (void)bluetoothDeviceTerminatedVoiceControl:(id)arg1;
+ (id)pendingOrActiveAlert;
+ (void)registerForAlerts;
+ (_Bool)resetVoiceControlIfNecessary:(_Bool)arg1;
+ (void)setNextRecognitionAudioInputPaths:(id)arg1;
+ (_Bool)shouldEnterVoiceControl;
+ (void)unregisterForAlerts;
- (void)_makeActive;
- (void)_proximityChanged:(id)arg1;
- (void)_resign;
- (id)_session;
- (void)_setRoutingAttributesForWiredHeadset:(_Bool)arg1;
- (void)_workspaceActivate;
- (void)activate;
- (void)activateWhenReady;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (_Bool)allowsEventOnlySuspension;
- (double)autoDimTime;
- (void)cancel;
- (void)cancelIfNotActivated;
- (void)deactivate;
- (void)dealloc;
- (_Bool)expectsFaceContact;
- (_Bool)expectsFaceContactInLandscape;
- (void)handleHeadsetButtonUpFromActivation:(_Bool)arg1;
- (_Bool)handleMenuButtonTap;
- (id)init;
- (id)initFromBluetoothDevice:(id)arg1;
- (id)initFromMenuButton;
- (id)initFromWiredHeadsetButton;
- (_Bool)recognitionSessionWillBeginAction:(id)arg1;
- (void)setExpectsFaceContact:(_Bool)arg1;
- (void)setExpectsFaceContact:(_Bool)arg1 inLandscape:(_Bool)arg2;

@end

