/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBIconIndexNodeObserver-Protocol.h"

@class NSString, SBFMappedImageCache;

@interface SBWallpaperPreviewSnapshotCache : NSObject <SBIconIndexNodeObserver>
{
    SBFMappedImageCache *_imageCache;
    long long _invalidatedLocations;
}

- (void)_backlightFadeFinished;
- (id)_homeScreenSnapshotProvider;
- (id)_lockScreenSnapshotProvider;
- (void)_modelDidLayout;
- (void)_modelWillLayout;
- (void)dealloc;
- (id)homeScreenSnapshot;
- (id)initWithImageCache:(id)arg1;
- (void)invalidateSnapshotsForLocations:(long long)arg1;
- (id)lockScreenSnapshot;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)regenerateSnapshotsForLocations:(long long)arg1 withCompletion:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

