/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

#import "SBFWallpaperViewInternalObserver-Protocol.h"
#import "SBFWallpaperViewLegibilityObserver-Protocol.h"
#import "SBUIActiveOrientationObserver-Protocol.h"
#import "UIWindowDelegate-Protocol.h"

@class NSHashTable, NSMutableSet, NSString, SBFWallpaperView, SBWallpaperEffectView, SBWallpaperPreviewSnapshotCache, UIImage, UIView, UIWindow;

@interface SBWallpaperController : NSObject <SBFWallpaperViewLegibilityObserver, SBFWallpaperViewInternalObserver, SBUIActiveOrientationObserver, UIWindowDelegate>
{
    UIWindow *_wallpaperWindow;
    UIView *_wallpaperContainerView;
    long long _orientation;
    SBFWallpaperView *_lockscreenWallpaperView;
    SBFWallpaperView *_homescreenWallpaperView;
    SBFWallpaperView *_sharedWallpaperView;
    NSHashTable *_lockscreenObservers;
    NSHashTable *_homescreenObservers;
    CDStruct_e838e30c _lockscreenPriorityInfo[3];
    CDStruct_e838e30c _homescreenPriorityInfo[7];
    CDStruct_059c2b36 _lockscreenStyleTransitionState;
    CDStruct_059c2b36 _homescreenStyleTransitionState;
    SBWallpaperEffectView *_lockscreenEffectView;
    SBWallpaperEffectView *_homescreenEffectView;
    NSMutableSet *_suspendColorSamplingReasons;
    NSMutableSet *_suspendWallpaperAnimationReasons;
    NSMutableSet *_requireWallpaperReasons;
    NSMutableSet *_hideHomescreenWallpaperReasons;
    NSMutableSet *_hideLockscreenWallpaperReasons;
    long long _displayedVariant;
    double _lockscreenOnlyWallpaperAlpha;
    NSHashTable *_lockscreenBlurViews;
    NSHashTable *_homescreenBlurViews;
    long long _disallowRasterizationBlockCount;
    NSMutableSet *_disallowRasterizationReasonsHomeVariant;
    NSMutableSet *_disallowRasterizationReasonsLockVariant;
    UIImage *_homescreenLightForegroundBlurImage;
    struct CGColor *_homescreenLightForegroundBlurColor;
    struct CGRect _homescreenLightForegroundBlurColorRect;
    NSMutableSet *_homescreenLightForegroundBlurCachedKeys;
    _Bool _creatingHomescreenLightForegroundBlurColor;
    _Bool _isSuspendingMotionEffectsForBlur;
    SBWallpaperPreviewSnapshotCache *_previewCache;
    long long _activeOrientationSource;
    _Bool _coalescingGeometryChanges;
    long long _locationsWithCoalescedGeometryChanges;
    double _homescreenWallpaperScale;
    double _lockscreenWallpaperScale;
}

+ (id)_homescreenLightForegroundBlurMappedImageCache;
+ (id)sharedInstance;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)arg1;
- (void)_beginDisallowRasterizationBlock;
- (void)_beginSuspendingMotionEffectsForBlurIfNeeded;
- (id)_blurViewsForVariant:(long long)arg1;
- (void)_clearHomescreenLightForegroundBlurColor;
- (void)_clearWallpaperEffectView:(id *)arg1;
- (void)_clearWallpaperView:(id *)arg1;
- (void)_createHomescreenLightForegroundBlurColorIfNecessary;
- (void)_endDisallowRasterizationBlock;
- (void)_endSuspendingMotionEffectsForBlurIfNeeded;
- (id)_getImageInRect:(struct CGRect)arg1 withZoomFactor:(double)arg2 forVariant:(long long)arg3 style:(inout long long *)arg4;
- (void)_handleWallpaperChangedForVariant:(long long)arg1;
- (void)_handleWallpaperGeometryChangedForVariant:(long long)arg1;
- (void)_handleWallpaperLegibilitySettingsChanged:(id)arg1 forVariant:(long long)arg2;
- (_Bool)_isAcceptingOrientationChangesFromSource:(long long)arg1;
- (_Bool)_isRasterizationDisallowedForCurrentVariant;
- (_Bool)_isWallpaperHiddenForVariant:(long long)arg1;
- (_Bool)_isWallpaperView:(id)arg1 displayingWallpaper:(id)arg2 forVariant:(long long)arg3;
- (void)_motionEffectsChanged;
- (id)_newFakeBlurViewForVariant:(long long)arg1;
- (id)_newWallpaperEffectViewForVariant:(long long)arg1 transitionState:(CDStruct_059c2b36)arg2;
- (id)_newWallpaperViewForProcedural:(id)arg1 orImage:(id)arg2 forVariant:(long long)arg3;
- (id)_observersForVariant:(long long)arg1;
- (void)_reconfigureBlurViewsForVariant:(long long)arg1;
- (void)_registerFakeBlurView:(id)arg1;
- (_Bool)_setDisallowRasterization:(_Bool)arg1 withReason:(id)arg2 reasons:(id)arg3;
- (void)_setWallpaperHidden:(_Bool)arg1 variant:(long long)arg2 reason:(id)arg3;
- (_Bool)_shouldSuspendMotionEffectsForState:(CDStruct_059c2b36)arg1;
- (id)_sourceForFakeBlurView:(id)arg1;
- (void)_suspendOrResumeColorSampling;
- (void)_suspendOrResumeWallpaperAnimation;
- (void)_unregisterFakeBlurView:(id)arg1;
- (void)_updateBlurGeneration;
- (void)_updateBlurImagesForVariant:(long long)arg1;
- (_Bool)_updateEffectViewForVariant:(long long)arg1 oldState:(CDStruct_059c2b36 *)arg2 newState:(CDStruct_059c2b36 *)arg3 oldEffectView:(id *)arg4 newEffectView:(id *)arg5;
- (_Bool)_updateEffectViewForVariant:(long long)arg1 withFactory:(id)arg2;
- (id)_updateEffectViewViaAnimationStepperForVariant:(long long)arg1 homescreenPriority:(long long)arg2;
- (void)_updateMotionEffectsForState:(CDStruct_059c2b36)arg1;
- (void)_updateRasterizationState;
- (void)_updateScreenBlanked;
- (void)_updateSeparateWallpaper;
- (void)_updateSharedWallpaper;
- (void)_updateWallpaperForLocations:(long long)arg1 withCompletion:(id)arg2;
- (void)_updateWallpaperHidden;
- (void)_updateWallpaperParallax;
- (id)_wallpaperViewForVariant:(long long)arg1;
- (id)_window;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
- (void)addObserver:(id)arg1 forVariant:(long long)arg2;
- (id)averageColorForVariant:(long long)arg1;
- (id)averageColorInRect:(struct CGRect)arg1 forVariant:(long long)arg2;
- (id)averageColorInRect:(struct CGRect)arg1 forVariant:(long long)arg2 withSmudgeRadius:(double)arg3;
- (void)beginRequiringWithReason:(id)arg1;
- (double)contrastInRect:(struct CGRect)arg1 contrastWithinBoxes:(double *)arg2 contrastBetweenBoxes:(double *)arg3 forVariant:(long long)arg4;
- (CDStruct_059c2b36)currentHomescreenStyleTransitionState;
- (void)dealloc;
- (id)debuggingDescription;
- (void)didFinishWallpaperStepAnimation:(id)arg1;
- (void)endRequiringWithReason:(id)arg1;
- (struct CGColor *)homescreenLightForegroundBlurColor;
- (struct CGSize)homescreenLightForegroundBlurColorPhaseForRect:(struct CGRect)arg1;
@property(nonatomic) double homescreenWallpaperScale; // @synthesize homescreenWallpaperScale=_homescreenWallpaperScale;
- (id)initWithOrientation:(long long)arg1 variant:(long long)arg2;
- (id)legibilitySettingsForVariant:(long long)arg1;
@property(nonatomic) double lockscreenWallpaperScale; // @synthesize lockscreenWallpaperScale=_lockscreenWallpaperScale;
- (void)orientationSource:(long long)arg1 didRotateFromInterfaceOrientation:(long long)arg2;
- (void)orientationSource:(long long)arg1 willAnimateRotationToInterfaceOrientation:(long long)arg2 duration:(double)arg3;
- (void)orientationSource:(long long)arg1 willRotateToInterfaceOrientation:(long long)arg2 duration:(double)arg3;
- (id)previewCache;
- (void)removeHomescreenStyleForGuidedAccessPriorityWithAnimationFactory:(id)arg1;
- (_Bool)removeHomescreenStyleForPriority:(long long)arg1 withAnimationFactory:(id)arg2;
- (id)removeHomescreenStyleViaAnimationStepperForPriority:(long long)arg1;
- (_Bool)removeLockscreenStyleForPriority:(long long)arg1 withAnimationFactory:(id)arg2;
- (void)removeObserver:(id)arg1 forVariant:(long long)arg2;
- (void)resumeColorSamplingForReason:(id)arg1;
- (void)resumeWallpaperAnimationForReason:(id)arg1;
- (void)setActiveOrientationSource:(long long)arg1 andUpdateToOrientation:(long long)arg2 usingCrossfadeToBlack:(_Bool)arg3;
- (void)setDisallowsRasterization:(_Bool)arg1 forVariant:(long long)arg2 withReason:(id)arg3;
- (_Bool)setHomescreenStyle:(long long)arg1 forPriority:(long long)arg2 withAnimationFactory:(id)arg3;
- (id)setHomescreenStyle:(long long)arg1 viaAnimationStepperForPriority:(long long)arg2;
- (void)setHomescreenStyleForGuidedAccessPriorityWithAnimationFactory:(id)arg1;
- (_Bool)setHomescreenStyleTransitionState:(CDStruct_059c2b36)arg1 forPriority:(long long)arg2 withAnimationFactory:(id)arg3;
- (id)setHomescreenStyleTransitionState:(CDStruct_059c2b36)arg1 viaAnimationStepperForPriority:(long long)arg2;
- (void)setLockscreenOnlyWallpaperAlpha:(double)arg1;
- (_Bool)setLockscreenStyle:(long long)arg1 forPriority:(long long)arg2 withAnimationFactory:(id)arg3;
- (_Bool)setLockscreenStyleTransitionState:(CDStruct_059c2b36)arg1 forPriority:(long long)arg2 withAnimationFactory:(id)arg3;
- (void)setLockscreenWallpaperContentsRect:(struct CGRect)arg1;
- (_Bool)setStyleTransitionState:(CDStruct_059c2b36)arg1 forVariant:(long long)arg2 priority:(long long)arg3 withAnimationFactory:(id)arg4;
@property(nonatomic) long long variant;
- (void)setVariant:(long long)arg1 withOutAnimationFactory:(id)arg2 inAnimationFactory:(id)arg3 completion:(id)arg4;
@property(nonatomic) double windowLevel;
- (void)suspendColorSamplingForReason:(id)arg1;
- (void)suspendWallpaperAnimationForReason:(id)arg1;
- (_Bool)variantsShareWallpaper;
- (void)wallpaperView:(id)arg1 didChangeZoomFactor:(double)arg2;
- (void)wallpaperView:(id)arg1 legibilitySettingsDidChange:(id)arg2;
- (void)wallpaperViewDidChangeWantsRasterization:(id)arg1;
- (void)wallpaperViewDidInvalidateBlurs:(id)arg1;
- (void)wallpaperViewDidInvalidateGeometry:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

