/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBApplication.h"

@class SBBookmarkIcon;

@interface SBWebApplication : SBApplication
{
    SBBookmarkIcon *_bookmarkIcon;
}

+ (id)_dataContainerURL;
+ (id)_snapshotDirectory;
+ (id)_webAppIdentifierFromWebClipIdentifier:(id)arg1;
+ (id)_webClipIdentifierFromWebAppIdentifier:(id)arg1;
- (id)_customStartupImageForLaunchingOrientation:(long long)arg1;
- (id)_defaultImageInfoForSceneID:(id)arg1 size:(struct CGSize)arg2 scale:(double)arg3 launchingOrientation:(long long)arg4;
- (_Bool)_isSnapshotPresentForLaunchingInterfaceOrientation:(long long)arg1;
- (id)_snapshotContainerName;
- (id)_snapshotSceneContainerNameForSceneID:(id)arg1;
@property(retain, nonatomic) SBBookmarkIcon *bookmarkIcon;
- (void)dealloc;
- (Class)iconClass;
- (_Bool)isWebApplication;
- (id)objectForActivationSetting:(unsigned int)arg1;
- (id)objectForDeactivationSetting:(unsigned int)arg1;
- (id)sandboxPath;

@end

