/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "SBBulletinViewController.h"

#import "SBNotificationCenterWidgetHost-Protocol.h"

@class NSArray, NSMutableDictionary, NSSet, NSString;

@interface SBWidgetHandlingBulletinViewController : SBBulletinViewController <SBNotificationCenterWidgetHost>
{
    NSMutableDictionary *_identifiersToWidgets;
    id _owedWillAppearBlock;
    struct CGRect _endDraggingTargetFrame;
    NSMutableDictionary *_outstandingWidgetUpdateRequests;
    id _cancelTouchesForHitWidgetAssertion;
    id <SBWidgetViewControllerDelegate> _widgetDelegate;
}

- (void)_cancelTouchesForHitWidgetIfNecessary;
- (void)_captureSnapshot:(_Bool)arg1 andInsert:(_Bool)arg2 disconnectingRemoteViewController:(_Bool)arg3 forceDisconnection:(_Bool)arg4 forWidget:(id)arg5 completion:(id)arg6;
- (void)_captureSnapshot:(_Bool)arg1 forWidget:(id)arg2 withCompletion:(id)arg3;
- (id)_completionHandlerForUpdateRequestForWidget:(SEL)arg1;
- (void)_disconnectRemoteViewController:(_Bool)arg1 forWidget:(id)arg2 withCompletion:(id)arg3;
- (void)_insertRemoteViewForWidget:(id)arg1 completion:(id)arg2;
- (void)_insertRemoteViewsForWidgetsWithIDs:(id)arg1 animated:(_Bool)arg2;
- (void)_insertSnapshot:(_Bool)arg1 forWidget:(id)arg2 withCompletion:(id)arg3;
- (void)_insertSnapshotsForWidgetsWithIDs:(id)arg1 animated:(_Bool)arg2;
- (void)_invokeBlockWithAllVisibleWidgets:(id)arg1;
- (void)_noteOutstandingUpdateRequestForWidget:(id)arg1;
- (void)_registerUpdateRequestCompletionHandler:(id)arg1 forWidget:(void)arg2;
- (void)_updateWidgetViewStateAfterScroll;
- (_Bool)_widgetHasOutstandingUpdateRequest:(id)arg1;
- (void)addChildBulletinIfPossible:(id)arg1;
@property(readonly, nonatomic) NSArray *allEnabledWidgetIDs;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)makeVisibleWidgetInSection:(id)arg1 andReconnect:(_Bool)arg2 animated:(_Bool)arg3 completion:(id)arg4;
- (void)removeChildBulletinIfPossible:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
@property(nonatomic) id <SBWidgetViewControllerDelegate> widgetDelegate; // @synthesize widgetDelegate=_widgetDelegate;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
@property(readonly, nonatomic) NSSet *visibleWidgetIDs;
- (void)widgetViewController:(id)arg1 beginAppearanceTransitionIfNecessary:(_Bool)arg2 animated:(_Bool)arg3;
- (void)widgetViewControllerEndAppearanceTransitionIfNecessary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

