/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UITableViewCell.h"

@class UIButton, UIImageView;

@interface SBWidgetsSettingsTableViewCell : UITableViewCell
{
    UIImageView *_dotImageView;
    _Bool _widgetEnabled;
    _Bool _showsDot;
    UIButton *_insertWidgetAccessoryButton;
}

- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(readonly, nonatomic) UIButton *insertWidgetAccessoryButton; // @synthesize insertWidgetAccessoryButton=_insertWidgetAccessoryButton;
@property(nonatomic, getter=isWidgetEnabled) _Bool widgetEnabled; // @synthesize widgetEnabled=_widgetEnabled;
- (void)layoutSubviews;
@property(nonatomic) _Bool showsDot; // @synthesize showsDot=_showsDot;

@end

