/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSMapTable;

@interface SBWindowHidingManager : NSObject
{
    NSMapTable *_windowStateMap;
    NSMapTable *_hidingContextMap;
    struct SBWindowLevelRange_struct _hideRange;
}

+ (id)sharedInstance;
+ (void)start;
- (void)_adjustWindowsForActiveHideRange;
- (void)_captureWindow:(id)arg1;
- (_Bool)_isHidingWindowLevel:(double)arg1;
- (_Bool)_isHidingWindows;
- (void)_recomputeHideRangeAndAdjustWindows;
- (void)_releaseWindow:(id)arg1;
- (void)_takeNoteOfWindow:(id)arg1 onScreen:(id)arg2;
- (id)dumpHidingState;
- (id)dumpKnownWindows;
- (id)init;
- (void)setAlpha:(double)arg1 forWindow:(id)arg2;
- (void)startHidingWindowsExclusivelyFromLevel:(double)arg1 toLevel:(double)arg2 forContext:(id)arg3 reason:(id)arg4;
- (void)stopHidingWindowsForContext:(id)arg1;

@end

