/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject-Protocol.h"

@protocol SBWidgetViewControllerDelegate <NSObject>

@optional
- (long long)activeLayoutModeForWidget:(id)arg1;
- (void)contentAvailabilityDidChangeForWidget:(id)arg1;
- (void)remoteViewControllerDidConnectForWidget:(id)arg1;
- (_Bool)shouldRequestWidgetRemoteViewControllers;
- (id)widget:(SEL)arg1 didUpdatePreferredHeight:(id)arg2 completion:(double)arg3;
- (void)widget:(id)arg1 requestsLaunchOfURL:(id)arg2;
- (void)widget:(id)arg1 requestsPresentationOfViewController:(id)arg2 presentationStyle:(long long)arg3 context:(id)arg4 completion:(id)arg5;
- (_Bool)widgetShouldAttemptReconnectionAfterUnanticipatedDisconnection:(id)arg1;
@end

