/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIViewController.h"

@class BSAuditToken, NSString;

@interface SBWidgetViewController : UIViewController
{
    _Bool _hasContent;
    long long _requestState;
    _Bool _implementsPerformUpdate;
    NSString *_appBundleID;
    NSString *_widgetIdentifier;
    BSAuditToken *_auditToken;
    id <SBWidgetViewControllerDelegate> _delegate;
}

+ (id)_requestLocalViewControllerOfClass:(Class)arg1 context:(id)arg2 handler:(id)arg3;
+ (id)displayNameForWidgetWithExtension:(id)arg1 containerBundleIdentifier:(id)arg2;
+ (id)requestViewController:(id)arg1 context:(id)arg2 handler:(id)arg3;
+ (id)widgetViewControllerWithIdentifier:(id)arg1 bundlePath:(id)arg2;
- (id)_cancelTouches;
- (void)_disconnectRemoteViewControllerImmediatelyWithCompletionHandler:(id)arg1;
- (void)_requestLaunchOfURL:(id)arg1;
- (void)_requestPresentationOfViewController:(id)arg1 presentationStyle:(long long)arg2 context:(id)arg3 completion:(id)arg4;
@property(copy, nonatomic) NSString *appBundleID; // @synthesize appBundleID=_appBundleID;
@property(readonly, nonatomic) BSAuditToken *auditToken; // @synthesize auditToken=_auditToken;
- (void)captureSnapshotWithCompletionHandler:(id)arg1;
- (void)connectRemoteViewControllerWithCompletionHandler:(id)arg1;
- (void)dealloc;
@property(nonatomic) id <SBWidgetViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disconnectRemoteViewControllerWithCompletionHandler:(id)arg1;
@property(nonatomic) _Bool hasContent; // @synthesize hasContent=_hasContent;
- (void)hostDidDismiss;
- (void)hostDidPresent;
- (void)hostWillDismiss;
- (void)hostWillPresent;
@property(readonly, nonatomic) _Bool implementsPerformUpdate; // @synthesize implementsPerformUpdate=_implementsPerformUpdate;
- (id)initWithWidgetIdentifier:(id)arg1 bundlePath:(id)arg2;
- (void)insertSnapshotWithCompletionHandler:(id)arg1;
- (void)invalidateCachedSnapshotWithCompletionHandler:(id)arg1;
@property(readonly, nonatomic, getter=isInternal) _Bool internal;
- (void)performUpdateWithCompletionHandler:(id)arg1;
- (void)requestInsertionOfRemoteViewWithCompletionHandler:(id)arg1;
- (void)requestPreferredViewHeightWithHandler:(id)arg1;
@property(nonatomic) long long requestState; // @synthesize requestState=_requestState;
- (void)updateContentWidth:(double)arg1;
- (void)validateSnapshotViewForActiveLayoutMode;
@property(readonly, nonatomic) NSString *widgetIdentifier; // @synthesize widgetIdentifier=_widgetIdentifier;

@end

