/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UITableViewCell.h"

#import "SBModalLayoutCaching-Protocol.h"

@class NSString, SBBBWidgetBulletinInfo;

@interface SBWidgetBulletinCell : UITableViewCell <SBModalLayoutCaching>
{
    SBBBWidgetBulletinInfo *_representedWidgetBulletinInfo;
    long long _layoutMode;
}

- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) long long layoutMode; // @synthesize layoutMode=_layoutMode;
@property(retain, nonatomic) SBBBWidgetBulletinInfo *representedWidgetBulletinInfo; // @synthesize representedWidgetBulletinInfo=_representedWidgetBulletinInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

