/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSDate;

@interface SBWorkItem : NSObject
{
    id _workBlock;
    NSDate *_creationDate;
}

@property(readonly, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
- (void)dealloc;
- (id)initWithWork:(id)arg1;
@property(readonly, nonatomic) id work; // @synthesize work=_workBlock;

@end

