/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "NSObject.h"

@class NSArray, SBDisplayLayout;

@interface SBWorkspaceAppsActivationRequest : NSObject
{
    NSArray *_applications;
    SBDisplayLayout *_displayLayout;
}

+ (id)fullScreenActivationRequestForApp:(id)arg1;
+ (id)homeScreenActivationRequest;
@property(readonly, nonatomic) NSArray *applications; // @synthesize applications=_applications;
- (void)dealloc;
@property(readonly, nonatomic) SBDisplayLayout *displayLayout; // @synthesize displayLayout=_displayLayout;
- (id)initWithApplications:(id)arg1 displayLayout:(id)arg2;

@end

