/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.sdk
 */

#import "UIView.h"

@interface UIView (SpringBoardAdditions)
- (void)_printLayer:(id)arg1 level:(int)arg2;
- (_Bool)hasActiveKeyboardOnScreen;
- (void)sb_removeAllSubviews;
- (void)sb_removeAnimationsForKeys:(id)arg1 update:(id)arg2;
- (id)sb_snapshotImage;
- (void)sbs_printLayerHierarchy;
@end

